package cellmanifest

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"sigs.k8s.io/yaml"
)

const FileName = "zz_generated_cell.yaml"

//go:embed cell.schema.json
var schema []byte

func Schema() []byte {
	out := make([]byte, len(schema))
	copy(out, schema)

	return out
}

type Manifest struct {
	Cell      string   `json:"cell" yaml:"cell"`
	Generator string   `json:"generator" yaml:"generator"`
	Provides  Provides `json:"provides" yaml:"provides"`
	Requires  Requires `json:"requires" yaml:"requires"`
}

type Provides struct {
	Drivers     []Driver     `json:"drivers,omitempty" yaml:"drivers,omitempty"`
	Adapters    []Adapter    `json:"adapters,omitempty" yaml:"adapters,omitempty"`
	Controllers []Controller `json:"controllers,omitempty" yaml:"controllers,omitempty"`
	Ports       []Port       `json:"ports,omitempty" yaml:"ports,omitempty"`
}

type Requires struct {
	Ports []string `json:"ports" yaml:"ports"`
}

type Driver struct {
	Name     string                 `json:"name" yaml:"name"`
	Type     string                 `json:"type" yaml:"type"`
	Module   string                 `json:"module,omitempty" yaml:"module,omitempty"`
	Requires []string               `json:"requires,omitempty" yaml:"requires,omitempty"`
	Config   map[string]ConfigField `json:"config,omitempty" yaml:"config,omitempty"`
}

type Adapter struct {
	Name       string                 `json:"name" yaml:"name"`
	Type       string                 `json:"type" yaml:"type"`
	Module     string                 `json:"module,omitempty" yaml:"module,omitempty"`
	Implements string                 `json:"implements" yaml:"implements"`
	Config     map[string]ConfigField `json:"config,omitempty" yaml:"config,omitempty"`
}

type Controller struct {
	Trait  string   `json:"trait" yaml:"trait"`
	Impl   string   `json:"impl" yaml:"impl"`
	Module string   `json:"module,omitempty" yaml:"module,omitempty"`
	Ports  []string `json:"ports" yaml:"ports"`
}

type Port struct {
	Trait  string `json:"trait" yaml:"trait"`
	Module string `json:"module,omitempty" yaml:"module,omitempty"`
}

type ConfigField struct {
	Type        string `json:"type" yaml:"type"`
	Required    bool   `json:"required,omitempty" yaml:"required,omitempty"`
	Default     any    `json:"default,omitempty" yaml:"default,omitempty"`
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
}

const (
	FieldTypeString   = "string"
	FieldTypeInteger  = "integer"
	FieldTypeBoolean  = "boolean"
	FieldTypeDuration = "duration"
)

func FieldTypes() []string {
	return []string{FieldTypeString, FieldTypeInteger, FieldTypeBoolean, FieldTypeDuration}
}

func knownFieldType(fieldType string) bool {
	for _, known := range FieldTypes() {
		if fieldType == known {
			return true
		}
	}

	return false
}

func Parse(data []byte) (Manifest, error) {
	var m Manifest

	if err := yaml.UnmarshalStrict(data, &m); err != nil {
		return Manifest{}, fmt.Errorf("parsing cell manifest: %w", err)
	}

	if err := m.Validate(); err != nil {
		return Manifest{}, fmt.Errorf("parsing cell manifest: %w", err)
	}

	return m, nil
}

func Read(path string) (Manifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Manifest{}, fmt.Errorf("reading cell manifest %q: %w", path, err)
	}

	m, err := Parse(data)
	if err != nil {
		return Manifest{}, fmt.Errorf("reading cell manifest %q: %w", path, err)
	}

	return m, nil
}

func Write(path string, m Manifest) error {
	data, err := Marshal(m)
	if err != nil {
		return fmt.Errorf("writing cell manifest %q: %w", path, err)
	}

	if dir := filepath.Dir(path); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("writing cell manifest %q: %w", path, err)
		}
	}

	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("writing cell manifest %q: %w", path, err)
	}

	return nil
}

func Marshal(m Manifest) ([]byte, error) {
	if err := m.Validate(); err != nil {
		return nil, fmt.Errorf("marshalling cell manifest: %w", err)
	}

	body, err := yaml.Marshal(m)
	if err != nil {
		return nil, fmt.Errorf("marshalling cell manifest: %w", err)
	}

	header := fmt.Sprintf("# Code generated by %s. DO NOT EDIT.\n", m.Generator)

	return append([]byte(header), body...), nil
}

func (m Manifest) Validate() error {
	if m.Cell == "" {
		return fmt.Errorf("cell name is empty")
	}

	if m.Generator == "" {
		return fmt.Errorf("cell %q names no generator", m.Cell)
	}

	for _, driver := range m.Provides.Drivers {
		if err := driver.validate(m.Cell); err != nil {
			return err
		}
	}

	for _, adapter := range m.Provides.Adapters {
		if err := adapter.validate(m.Cell); err != nil {
			return err
		}
	}

	return nil
}

func (d Driver) validate(cell string) error {
	if d.Name == "" {
		return fmt.Errorf("cell %q provides a driver with no name", cell)
	}

	if len(d.Requires) == 0 {
		return fmt.Errorf("driver %q in cell %q requires no controller trait", d.Name, cell)
	}

	return validateConfig(fmt.Sprintf("driver %q in cell %q", d.Name, cell), d.Config)
}

func (a Adapter) validate(cell string) error {
	if a.Name == "" {
		return fmt.Errorf("cell %q provides an adapter with no name", cell)
	}

	if a.Implements == "" {
		return fmt.Errorf("adapter %q in cell %q implements no port", a.Name, cell)
	}

	return validateConfig(fmt.Sprintf("adapter %q in cell %q", a.Name, cell), a.Config)
}

func validateConfig(owner string, config map[string]ConfigField) error {
	names := make([]string, 0, len(config))
	for name := range config {
		names = append(names, name)
	}

	sort.Strings(names)

	for _, name := range names {
		if !knownFieldType(config[name].Type) {
			return fmt.Errorf(
				"config field %q of %s has type %q which is not one of string, integer, boolean, duration",
				name, owner, config[name].Type,
			)
		}
	}

	return nil
}
