// Code generated by cli-go-cobra (forge-dev-codegen). DO NOT EDIT.
// Source: forge-dev.yaml
// SourceChecksum: sha256:ed4221c6ab05d51c7b564878d73a510d113e634aa744cadc0ff25546c5aaa584

package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// demo-cli-go-cobra v0.1.0: a cli kind program dispatched by cobra. The
// author contract is the builtin cell's, so the generator is swappable:
//
//	func NewCLIHandlers() CLIHandlers {
//		return CLIHandlers{
//			Fail: func(args []string) int { ... },
//			Greet: func(args []string) int { ... },
//		}
//	}

// CLIHandlers holds one handler per declared command. Every field is
// required: a nil handler fails at dispatch, loud, naming the command.
type CLIHandlers struct {
	// Fail runs the fail command. Exit with the given code.
	Fail func(args []string) int
	// Greet runs the greet command. Print the greeting and the args.
	Greet func(args []string) int
}

// Dispatch routes args through cobra and answers the process exit code.
// Flag parsing is disabled on every subcommand: the handler owns its args,
// exactly as the builtin cell hands them over.
func Dispatch(handlers CLIHandlers, args []string) int {
	code := 0

	root := &cobra.Command{
		Use:           "demo-cli-go-cobra",
		Short:         "A cli whose dispatcher is emitted by cli-go-cobra. The living proof that a generator cell is a drop-in swap.",
		Version:       "0.1.0",
		SilenceUsage:  true,
		SilenceErrors: true,
	}

	root.AddCommand(&cobra.Command{
		Use:                "fail",
		Short:              "Exit with the given code.",
		DisableFlagParsing: true,
		RunE: func(_ *cobra.Command, commandArgs []string) error {
			if handlers.Fail == nil {
				return fmt.Errorf("command fail has no handler")
			}

			code = handlers.Fail(commandArgs)

			return nil
		},
	})

	root.AddCommand(&cobra.Command{
		Use:                "greet",
		Short:              "Print the greeting and the args.",
		DisableFlagParsing: true,
		RunE: func(_ *cobra.Command, commandArgs []string) error {
			if handlers.Greet == nil {
				return fmt.Errorf("command greet has no handler")
			}

			code = handlers.Greet(commandArgs)

			return nil
		},
	})

	root.SetArgs(args)

	if err := root.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "demo-cli-go-cobra: %v\n", err)

		return 2
	}

	return code
}

func main() {
	os.Exit(Dispatch(NewCLIHandlers(), os.Args[1:]))
}
