// Code generated by tui-rust (forge-dev-codegen). DO NOT EDIT.

pub mod zz_generated_board_controller;

mod board_controller;

pub use zz_generated_board_controller::{
    BoardController, BoardControllerError, BoardControllerImpl, TuiPorts,
};
