// Code generated by tui-rust (forge-dev-codegen). DO NOT EDIT.

use std::sync::Arc;

use crate::tui::port::keyboard::Keyboard;
use crate::tui::port::screen::Screen;
use crate::tui::types::frame::{Frame, Step};
use crate::tui::types::key::Key;

#[derive(Debug, thiserror::Error)]
pub enum BoardControllerError {
    #[error("validating {field:?}: {reason}")]
    Invalid { field: String, reason: String },
    #[error("running {operation:?}: not implemented")]
    NotImplemented { operation: String },
}

pub trait TuiPorts: Send + Sync {
    fn screen(&self) -> Arc<dyn Screen + Send + Sync>;
    fn keyboard(&self) -> Arc<dyn Keyboard + Send + Sync>;
}

pub trait BoardController: TuiPorts + Send + Sync {
    fn on_key(&self, frame: &Frame, key: Key) -> Result<Step, BoardControllerError>;
    fn on_line(&self, frame: &Frame, line: &str) -> Result<Step, BoardControllerError>;
    fn on_tick(&self, frame: &Frame) -> Result<Frame, BoardControllerError>;
}

pub struct BoardControllerImpl {
    pub(crate) screen: Arc<dyn Screen + Send + Sync>,
    pub(crate) keyboard: Arc<dyn Keyboard + Send + Sync>,
}

impl BoardControllerImpl {
    pub fn new(
        screen: Arc<dyn Screen + Send + Sync>,
        keyboard: Arc<dyn Keyboard + Send + Sync>,
    ) -> Self {
        Self { screen, keyboard }
    }
}

impl TuiPorts for BoardControllerImpl {
    fn screen(&self) -> Arc<dyn Screen + Send + Sync> {
        self.screen.clone()
    }

    fn keyboard(&self) -> Arc<dyn Keyboard + Send + Sync> {
        self.keyboard.clone()
    }
}
