// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package grpcrust_test

import (
	"reflect"
	"strings"
	"testing"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/grpcrust"
)

func TestGeneratingTheHelloProtoEmitsTheWholeFileSet(t *testing.T) {
	files, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello"})
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	wantPaths := []string{
		"adapter/mod.rs",
		"adapter/zz_generated_hello_grpc_client.rs",
		"controller/mod.rs",
		"controller/zz_generated_hello_controller.rs",
		"driver/mod.rs",
		"driver/zz_generated_hello_grpc_driver.rs",
		"hand/hello_controller.rs",
		"hand/mod.rs",
		"mod.rs",
		"port/mod.rs",
		"port/zz_generated_hello_client.rs",
		"proto/zz_generated_hello.proto",
		"types/mod.rs",
		"types/zz_generated_hello_messages.rs",
		"zz_generated_build.rs",
	}

	gotPaths := []string{}
	byPath := map[string]grpcrust.File{}

	for _, f := range files {
		gotPaths = append(gotPaths, f.Path)
		byPath[f.Path] = f
	}

	if !reflect.DeepEqual(gotPaths, wantPaths) {
		t.Fatalf("emitted paths\n got %q\nwant %q", gotPaths, wantPaths)
	}

	tests := []struct {
		name string
		path string
		want []string
	}{
		{
			name: "the cell mod file lists one layer per module directory",
			path: "mod.rs",
			want: []string{
				"pub mod adapter;",
				"pub mod controller;",
				"pub mod driver;",
				"pub mod hand;",
				"pub mod port;",
				"pub mod types;",
			},
		},
		{
			name: "a layer mod file mounts the generated module and aliases it without a path attribute",
			path: "controller/mod.rs",
			want: []string{
				"pub mod zz_generated_hello_controller;",
				"pub use zz_generated_hello_controller as hello_controller;",
			},
		},
		{
			name: "the proto file is copied verbatim behind the generated header",
			path: "proto/zz_generated_hello.proto",
			want: []string{
				"// Code generated by grpc-rust-tonic (forge-dev-codegen). DO NOT EDIT.",
				"service Hello {",
				"message PingRequest {",
			},
		},
		{
			name: "the messages file holds plain serde structs",
			path: "types/zz_generated_hello_messages.rs",
			want: []string{
				"#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]",
				"pub struct PingRequest {",
				"    pub message: String,",
				"    pub count: u64,",
				"pub struct PingReply {",
			},
		},
		{
			name: "the port trait is mockable and returns the client error",
			path: "port/zz_generated_hello_client.rs",
			want: []string{
				"use crate::grpc::types::hello_messages::{PingRequest, PingReply};",
				"#[cfg_attr(test, mockall::automock)]",
				"pub trait HelloClient: Send + Sync {",
				"    fn ping(&self, request: PingRequest) -> Result<PingReply, HelloClientError>;",
				"pub enum HelloClientError {",
				"        source: Box<dyn std::error::Error + Send + Sync>,",
			},
		},
		{
			name: "the adapter wraps a tonic channel behind the port trait",
			path: "adapter/zz_generated_hello_grpc_client.rs",
			want: []string{
				"use songe_hello_core::grpc::port::hello_client::{HelloClient, HelloClientError};",
				"mod pb {",
				`    tonic::include_proto!("songe.hello.v1");`,
				"pub struct HelloGrpcClient {",
				"    channel: tonic::transport::Channel,",
				"impl HelloClient for HelloGrpcClient {",
				"    fn ping(&self, request: PingRequest) -> Result<PingReply, HelloClientError> {",
				"let mut client = pb::hello_client::HelloClient::new(channel);",
				"impl From<PingRequest> for pb::PingRequest {",
				"impl From<pb::PingReply> for PingReply {",
			},
		},
		{
			name: "the driver forwards each rpc to the core controller",
			path: "driver/zz_generated_hello_grpc_driver.rs",
			want: []string{
				"use songe_hello_core::grpc::controller::hello_controller::HelloController;",
				"pub struct HelloGrpcDriver {",
				"    controller: Arc<dyn HelloController>,",
				"pub fn into_server(self) -> pb::hello_server::HelloServer<Self> {",
				"#[tonic::async_trait]",
				"impl pb::hello_server::Hello for HelloGrpcDriver {",
				"    async fn ping(&self, request: tonic::Request<pb::PingRequest>) -> Result<tonic::Response<pb::PingReply>, tonic::Status> {",
				".controller",
				".ping(core_request)",
			},
		},
		{
			name: "the controller trait carries one method per rpc over the proto derived types",
			path: "controller/zz_generated_hello_controller.rs",
			want: []string{
				"use crate::grpc::types::hello_messages::{PingRequest, PingReply};",
				"#[cfg_attr(test, mockall::automock)]",
				"pub trait HelloController: Send + Sync {",
				"    fn ping(&self, request: PingRequest) -> Result<PingReply, HelloControllerError>;",
				"pub enum HelloControllerError {",
				`    #[error("running {operation:?}: not implemented")]`,
				"pub struct HelloControllerImpl;",
				"impl HelloController for HelloControllerImpl {",
				"crate::grpc::hand::hello_controller::ping(request)",
			},
		},
		{
			name: "the hand controller skeleton answers not implemented for every rpc",
			path: "hand/hello_controller.rs",
			want: []string{
				"use crate::grpc::controller::hello_controller::HelloControllerError;",
				"use crate::grpc::types::hello_messages::{PingRequest, PingReply};",
				"pub fn ping(request: PingRequest) -> Result<PingReply, HelloControllerError> {",
				"    let _ = request;",
				"    Err(HelloControllerError::NotImplemented {",
				`        operation: "ping".to_string(),`,
			},
		},
		{
			name: "the build script compiles the proto without a protoc binary",
			path: "zz_generated_build.rs",
			want: []string{
				`["src/grpc/proto/zz_generated_hello.proto"],`,
				`["src/grpc/proto"],`,
				"tonic_prost_build::configure()",
				".compile_fds(file_descriptors)?;",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			content, ok := byPath[tt.path]
			if !ok {
				t.Fatalf("no file at %s", tt.path)
			}

			for _, line := range tt.want {
				if !strings.Contains(content.Content, line) {
					t.Errorf("%s lacks %q\n%s", tt.path, line, content.Content)
				}
			}
		})
	}
}

func TestEveryGeneratedFileStartsWithTheHeaderLine(t *testing.T) {
	files, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello"})
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	const header = "// Code generated by grpc-rust-tonic (forge-dev-codegen). DO NOT EDIT.\n"

	for _, f := range files {
		if f.WriteOnce == strings.HasPrefix(f.Content, header) {
			t.Errorf("%s: the header belongs on every file but a hand file", f.Path)
		}
	}
}

func TestGeneratingRefusesAnEmptyServiceName(t *testing.T) {
	_, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{})
	if err == nil || !strings.Contains(err.Error(), "the service name is required") {
		t.Fatalf("want an error requiring the service name, got %v", err)
	}
}

func TestGeneratingRefusesAProtoWithNoService(t *testing.T) {
	const doc = `
syntax = "proto3";
package demo;
message Empty {}
`

	_, err := grpcrust.Generate([]byte(doc), grpcrust.Options{Service: "svc"})
	if err == nil || !strings.Contains(err.Error(), "declares no service") {
		t.Fatalf("want an error requiring a service, got %v", err)
	}
}

func TestASideAnswersOnlyItsOwnLayersInsideTheCell(t *testing.T) {
	tests := []struct {
		side string
		opts grpcrust.Options
		want []string
	}{
		{
			side: "core",
			opts: grpcrust.Options{Service: "songe-hello", Side: "core"},
			want: []string{
				"controller/mod.rs",
				"controller/zz_generated_hello_controller.rs",
				"hand/hello_controller.rs",
				"hand/mod.rs",
				"mod.rs",
				"port/mod.rs",
				"port/zz_generated_hello_client.rs",
				"types/mod.rs",
				"types/zz_generated_hello_messages.rs",
			},
		},
		{
			side: "app",
			opts: grpcrust.Options{Service: "songe-hello", Side: "app"},
			want: []string{
				"adapter/mod.rs",
				"adapter/zz_generated_hello_grpc_client.rs",
				"driver/mod.rs",
				"driver/zz_generated_hello_grpc_driver.rs",
				"mod.rs",
				"proto/zz_generated_hello.proto",
				"zz_generated_build.rs",
			},
		},
	}

	for _, tt := range tests {
		t.Run("the "+tt.side+" side answers only its own files", func(t *testing.T) {
			files, err := grpcrust.Generate([]byte(helloProto), tt.opts)
			if err != nil {
				t.Fatalf("generating: %v", err)
			}

			got := []string{}
			for _, f := range files {
				got = append(got, f.Path)
			}

			if !reflect.DeepEqual(got, tt.want) {
				t.Fatalf("emitted paths\n got %q\nwant %q", got, tt.want)
			}
		})
	}
}

func TestGeneratingRefusesASideThatNamesNeitherCrate(t *testing.T) {
	_, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello", Side: "both"})
	if err == nil || !strings.Contains(err.Error(), "side must be core, app or empty") {
		t.Fatalf("want an error refusing the side, got %v", err)
	}
}

func TestTheHandControllerSkeletonIsTheOnlyWriteOnceFile(t *testing.T) {
	files, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello"})
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	writeOnce := []string{}

	for _, f := range files {
		if f.WriteOnce {
			writeOnce = append(writeOnce, f.Path)
		}
	}

	want := []string{"hand/hello_controller.rs"}
	if !reflect.DeepEqual(writeOnce, want) {
		t.Fatalf("write once files\n got %q\nwant %q", writeOnce, want)
	}
}

func TestEveryEmittedPathStaysInsideTheCellDirectory(t *testing.T) {
	files, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello"})
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	for _, f := range files {
		if strings.HasPrefix(f.Path, "/") || strings.HasPrefix(f.Path, "..") {
			t.Errorf("%s reaches above the cell directory", f.Path)
		}
	}
}

func TestTheCellNamesTheModuleTheCrateMountsAndDefaultsToGrpc(t *testing.T) {
	files, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello", Cell: "wire"})
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	for _, f := range files {
		if f.Path != "port/zz_generated_hello_client.rs" {
			continue
		}

		if !strings.Contains(f.Content, "use crate::wire::types::hello_messages::") {
			t.Fatalf("the port file does not read the cell name\n%s", f.Content)
		}
	}
}

func TestACellNameRustCannotSpellIsRefused(t *testing.T) {
	for _, cell := range []string{"Grpc", "grpc-cell", "mod", "1grpc"} {
		if _, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello", Cell: cell}); err == nil {
			t.Errorf("cell %q was accepted", cell)
		}
	}
}
