// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package grpcrust_test

import (
	"reflect"
	"strings"
	"testing"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/grpcrust"
	"github.com/alexandremahdhaoui/forge-dev-codegen/pkg/cellmanifest"
)

func TestGeneratingTheHelloProtoEmitsTheWholeFileSet(t *testing.T) {
	files, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello"})
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	wantPaths := []string{
		"adapter/mod.rs",
		"adapter/zz_generated_hello_grpc_client.rs",
		"controller/mod.rs",
		"controller/zz_generated_hello_controller.rs",
		"driver/mod.rs",
		"driver/zz_generated_hello_grpc_driver.rs",
		"mod.rs",
		"port/mod.rs",
		"port/zz_generated_hello_client.rs",
		"proto/zz_generated_hello.proto",
		"types/mod.rs",
		"types/zz_generated_hello_messages.rs",
		"zz_generated_build.rs",
		"zz_generated_cell.yaml",
	}

	gotPaths := []string{}
	byPath := map[string]grpcrust.File{}

	for _, f := range files {
		gotPaths = append(gotPaths, f.Path)
		byPath[f.Path] = f
	}

	if !reflect.DeepEqual(gotPaths, wantPaths) {
		t.Fatalf("emitted paths\n got %q\nwant %q", gotPaths, wantPaths)
	}

	tests := []struct {
		name string
		path string
		want []string
	}{
		{
			name: "the cell mod file lists one layer per module directory",
			path: "mod.rs",
			want: []string{
				"pub mod adapter;",
				"pub mod controller;",
				"pub mod driver;",
				"pub mod port;",
				"pub mod types;",
			},
		},
		{
			name: "the controller layer mounts the user impl file and re exports the trait and the struct",
			path: "controller/mod.rs",
			want: []string{
				"pub mod zz_generated_hello_controller;",
				"mod hello_controller;",
				"pub use zz_generated_hello_controller::{HelloController, HelloControllerError, HelloControllerImpl};",
			},
		},
		{
			name: "the adapter and the driver layers allow the io lint table",
			path: "driver/mod.rs",
			want: []string{
				"#![allow(clippy::disallowed_methods, clippy::disallowed_types)]",
			},
		},
		{
			name: "the proto file is copied verbatim behind the generated header",
			path: "proto/zz_generated_hello.proto",
			want: []string{
				"// Code generated by grpc-rust-tonic (forge-dev-codegen). DO NOT EDIT.",
				"service Hello {",
				"message PingRequest {",
			},
		},
		{
			name: "the messages file holds plain serde structs",
			path: "types/zz_generated_hello_messages.rs",
			want: []string{
				"#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]",
				"pub struct PingRequest {",
				"    pub message: String,",
				"    pub count: u64,",
				"pub struct PingReply {",
			},
		},
		{
			name: "the port trait is mockable and returns the client error",
			path: "port/zz_generated_hello_client.rs",
			want: []string{
				"use crate::grpc::types::hello_messages::{PingRequest, PingReply};",
				"#[cfg_attr(test, mockall::automock)]",
				"pub trait HelloClient: Send + Sync {",
				"    fn ping(&self, request: PingRequest) -> Result<PingReply, HelloClientError>;",
				"pub enum HelloClientError {",
				"        source: Box<dyn std::error::Error + Send + Sync>,",
			},
		},
		{
			name: "the adapter builds its channel from its own config struct",
			path: "adapter/zz_generated_hello_grpc_client.rs",
			want: []string{
				"use crate::grpc::port::hello_client::{HelloClient, HelloClientError};",
				"mod pb {",
				`    tonic::include_proto!("songe.hello.v1");`,
				"pub struct HelloGrpcClientConfig {",
				"    pub endpoint: String,",
				"pub struct HelloGrpcClient {",
				"    channel: tonic::transport::Channel,",
				"    pub fn new(config: HelloGrpcClientConfig) -> Result<Self, HelloGrpcClientError> {",
				"impl HelloClient for HelloGrpcClient {",
				"    fn ping(&self, request: PingRequest) -> Result<PingReply, HelloClientError> {",
				"let mut client = pb::hello_client::HelloClient::new(channel);",
				"impl From<PingRequest> for pb::PingRequest {",
				"impl From<pb::PingReply> for PingReply {",
			},
		},
		{
			name: "the driver takes a config and a boxed controller, binds, announces and serves",
			path: "driver/zz_generated_hello_grpc_driver.rs",
			want: []string{
				"use crate::grpc::controller::HelloController;",
				"pub struct HelloGrpcDriverConfig {",
				"    pub addr: String,",
				"pub struct HelloGrpcService {",
				"    controller: Arc<dyn HelloController + Send + Sync>,",
				"    pub fn new(config: HelloGrpcDriverConfig, controller: Arc<dyn HelloController + Send + Sync>) -> Self {",
				"    pub async fn bind(&mut self) -> Result<(), HelloGrpcDriverError> {",
				`        println!("LISTENING_GRPC {}", self.local_port()?);`,
				"            .serve_with_incoming(incoming)",
				"#[tonic::async_trait]",
				"impl pb::hello_server::Hello for HelloGrpcService {",
				"    async fn ping(&self, request: tonic::Request<pb::PingRequest>) -> Result<tonic::Response<pb::PingReply>, tonic::Status> {",
				".controller",
				".ping(core_request)",
			},
		},
		{
			name: "the controller trait carries one method per rpc and the struct the user implements",
			path: "controller/zz_generated_hello_controller.rs",
			want: []string{
				"use crate::grpc::types::hello_messages::{PingRequest, PingReply};",
				"#[cfg_attr(test, mockall::automock)]",
				"pub trait HelloController: Send + Sync {",
				"    fn ping(&self, request: PingRequest) -> Result<PingReply, HelloControllerError>;",
				"pub enum HelloControllerError {",
				`    #[error("running {operation:?}: not implemented")]`,
				"pub struct HelloControllerImpl;",
				"    pub fn new() -> Self {",
			},
		},
		{
			name: "the build script compiles the proto without a protoc binary",
			path: "zz_generated_build.rs",
			want: []string{
				`["src/grpc/proto/zz_generated_hello.proto"],`,
				`["src/grpc/proto"],`,
				"tonic_prost_build::configure()",
				".compile_fds(file_descriptors)?;",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			content, ok := byPath[tt.path]
			if !ok {
				t.Fatalf("no file at %s", tt.path)
			}

			for _, line := range tt.want {
				if !strings.Contains(content.Content, line) {
					t.Errorf("%s lacks %q\n%s", tt.path, line, content.Content)
				}
			}
		})
	}
}

func TestTheGeneratedControllerNeverCallsAHandFunction(t *testing.T) {
	files, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello"})
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	for _, f := range files {
		if strings.Contains(f.Path, "hand") || strings.Contains(f.Content, "::hand::") {
			t.Errorf("%s still reaches for a hand module", f.Path)
		}
	}
}

func TestTheCellManifestNamesTheDriverTheAdapterTheControllerAndThePort(t *testing.T) {
	files, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello"})
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	var body string

	for _, f := range files {
		if f.Path == cellmanifest.FileName {
			body = f.Content
		}
	}

	if body == "" {
		t.Fatal("no cell manifest was emitted")
	}

	m, err := cellmanifest.Parse([]byte(body))
	if err != nil {
		t.Fatalf("parsing the manifest: %v\n%s", err, body)
	}

	if m.Cell != "grpc" {
		t.Errorf("cell = %q, want grpc", m.Cell)
	}

	if len(m.Provides.Drivers) != 1 {
		t.Fatalf("drivers = %+v", m.Provides.Drivers)
	}

	driver := m.Provides.Drivers[0]
	if driver.Name != "grpc" || driver.Type != "HelloGrpcDriver" || driver.Module != "grpc::driver::hello_grpc_driver" {
		t.Errorf("driver = %+v", driver)
	}

	if !reflect.DeepEqual(driver.Requires, []string{"HelloController"}) {
		t.Errorf("driver requires = %+v", driver.Requires)
	}

	if driver.Config["addr"].Default != "127.0.0.1:0" {
		t.Errorf("driver config = %+v", driver.Config)
	}

	if len(m.Provides.Adapters) != 1 {
		t.Fatalf("adapters = %+v", m.Provides.Adapters)
	}

	adapter := m.Provides.Adapters[0]
	if adapter.Name != "grpc_client" || adapter.Implements != "HelloClient" || adapter.Type != "HelloGrpcClient" {
		t.Errorf("adapter = %+v", adapter)
	}

	if len(m.Provides.Controllers) != 1 {
		t.Fatalf("controllers = %+v", m.Provides.Controllers)
	}

	controller := m.Provides.Controllers[0]
	if controller.Trait != "HelloController" || controller.Impl != "HelloControllerImpl" || controller.Module != "grpc::controller" {
		t.Errorf("controller = %+v", controller)
	}

	if len(controller.Ports) != 0 {
		t.Errorf("a grpc controller consumes no port, got %+v", controller.Ports)
	}

	if len(m.Provides.Ports) != 1 || m.Provides.Ports[0].Trait != "HelloClient" {
		t.Errorf("ports = %+v", m.Provides.Ports)
	}
}

func TestEveryGeneratedRustFileStartsWithTheHeaderLine(t *testing.T) {
	files, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello"})
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	const header = "// Code generated by grpc-rust-tonic (forge-dev-codegen). DO NOT EDIT.\n"

	for _, f := range files {
		if !strings.HasSuffix(f.Path, ".rs") {
			continue
		}

		if !strings.HasPrefix(f.Content, header) {
			t.Errorf("%s does not open with the generated header", f.Path)
		}
	}
}

func TestGeneratingRefusesAnEmptyServiceName(t *testing.T) {
	_, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{})
	if err == nil || !strings.Contains(err.Error(), "the service name is required") {
		t.Fatalf("want an error requiring the service name, got %v", err)
	}
}

func TestGeneratingRefusesAProtoWithNoService(t *testing.T) {
	const doc = `
syntax = "proto3";
package demo;
message Empty {}
`

	_, err := grpcrust.Generate([]byte(doc), grpcrust.Options{Service: "svc"})
	if err == nil || !strings.Contains(err.Error(), "declares no service") {
		t.Fatalf("want an error requiring a service, got %v", err)
	}
}

func TestEveryEmittedPathStaysInsideTheCellDirectory(t *testing.T) {
	files, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello"})
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	for _, f := range files {
		if strings.HasPrefix(f.Path, "/") || strings.HasPrefix(f.Path, "..") {
			t.Errorf("%s reaches above the cell directory", f.Path)
		}
	}
}

func TestTheCellNamesTheModuleTheCrateMountsAndDefaultsToGrpc(t *testing.T) {
	files, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello", Cell: "wire"})
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	for _, f := range files {
		if f.Path != "port/zz_generated_hello_client.rs" {
			continue
		}

		if !strings.Contains(f.Content, "use crate::wire::types::hello_messages::") {
			t.Fatalf("the port file does not read the cell name\n%s", f.Content)
		}
	}
}

func TestACellNameRustCannotSpellIsRefused(t *testing.T) {
	for _, cell := range []string{"Grpc", "grpc-cell", "mod", "1grpc"} {
		if _, err := grpcrust.Generate([]byte(helloProto), grpcrust.Options{Service: "songe-hello", Cell: cell}); err == nil {
			t.Errorf("cell %q was accepted", cell)
		}
	}
}
