// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package grpcrust

import (
	"bytes"
	"fmt"
	"path"
	"regexp"
	"sort"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/pkg/cellmanifest"
)

const header = "// Code generated by grpc-rust-tonic (forge-dev-codegen). DO NOT EDIT."

const Generator = "grpc-rust-tonic (forge-dev-codegen)"

const DefaultCell = "grpc"

const DefaultAddress = "127.0.0.1:0"

const DefaultEndpoint = "http://127.0.0.1:50051"

var Layers = []string{"adapter", "controller", "driver", "port", "types"}

var allowingLayers = map[string]bool{"adapter": true, "driver": true}

var cellIdent = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

func checkCell(name string) error {
	if cellIdent.MatchString(name) && !rustKeywords[name] {
		return nil
	}

	return fmt.Errorf("emitting the skeleton: cell %q is not a name Rust can spell as a module, use lowercase letters, digits and underscores and start with a letter", name)
}

type modEntry struct {
	Module  string
	Alias   string
	Exports []string
}

type layerMod struct {
	Header   string
	Allow    bool
	Entries  []modEntry
	UserMods []string
}

func Generate(doc []byte, opts Options) ([]File, error) {
	if opts.Service == "" {
		return nil, fmt.Errorf("emitting the skeleton: the service name is required")
	}

	if opts.Cell == "" {
		opts.Cell = DefaultCell
	}

	if err := checkCell(opts.Cell); err != nil {
		return nil, err
	}

	spec, err := Parse(doc)
	if err != nil {
		return nil, err
	}

	if len(spec.Services) == 0 {
		return nil, fmt.Errorf("emitting the skeleton: the proto document declares no service")
	}

	files := []File{}

	add := func(p, name string, data any) error {
		content, err := render(name, data)
		if err != nil {
			return err
		}

		files = append(files, File{Path: p, Content: content})

		return nil
	}

	entries := map[string][]modEntry{}
	userMods := map[string][]string{}

	mount := func(layer string, entry modEntry) {
		entries[layer] = append(entries[layer], entry)
	}

	manifest := cellmanifest.Manifest{
		Version:   cellmanifest.Version,
		Cell:      opts.Cell,
		Generator: Generator,
	}

	only := len(spec.Services) == 1

	for _, svc := range spec.Services {
		v, err := buildServiceView(spec, svc, opts, only)
		if err != nil {
			return nil, err
		}

		steps := []func() error{
			func() error {
				return add(path.Join("adapter", "zz_generated_"+v.ClientModule+".rs"), "adapter", v)
			},
			func() error {
				return add(path.Join("driver", "zz_generated_"+v.DriverModule+".rs"), "driver", v)
			},
			func() error {
				return add(path.Join("port", "zz_generated_"+v.ServiceSnake+"_client.rs"), "port", v)
			},
			func() error {
				return add(path.Join("types", "zz_generated_"+v.ServiceSnake+"_messages.rs"), "types", v)
			},
			func() error {
				return add(path.Join("controller", "zz_generated_"+v.ControllerSnake+"_controller.rs"), "controller", v)
			},
		}

		for _, step := range steps {
			if err := step(); err != nil {
				return nil, err
			}
		}

		mount("adapter", modEntry{Module: "zz_generated_" + v.ClientModule, Alias: v.ClientModule})
		mount("driver", modEntry{Module: "zz_generated_" + v.DriverModule, Alias: v.DriverModule})
		mount("port", modEntry{Module: "zz_generated_" + v.ServiceSnake + "_client", Alias: v.ServiceSnake + "_client"})
		mount("types", modEntry{Module: "zz_generated_" + v.ServiceSnake + "_messages", Alias: v.ServiceSnake + "_messages"})
		mount("controller", modEntry{
			Module:  "zz_generated_" + v.ControllerSnake + "_controller",
			Exports: []string{v.ControllerTrait, v.ControllerError, v.ControllerTrait + "Impl"},
		})
		userMods["controller"] = append(userMods["controller"], v.ControllerSnake+"_controller")

		addServiceToManifest(&manifest, v)
	}

	for _, layer := range Layers {
		mod := layerMod{
			Header:   header,
			Allow:    allowingLayers[layer],
			Entries:  entries[layer],
			UserMods: userMods[layer],
		}
		sort.Slice(mod.Entries, func(i, j int) bool { return mod.Entries[i].Module < mod.Entries[j].Module })
		sort.Strings(mod.UserMods)

		if err := add(path.Join(layer, "mod.rs"), "layer_mod", mod); err != nil {
			return nil, err
		}
	}

	cell, err := render("cell_mod", map[string]any{"Header": header, "Layers": Layers})
	if err != nil {
		return nil, err
	}

	files = append(files, File{Path: "mod.rs", Content: cell})

	protoName := Snake(spec.Services[0].Name)
	buildData := map[string]any{"Header": header, "Cell": opts.Cell, "Name": protoName}

	if err := add("zz_generated_build.rs", "build", buildData); err != nil {
		return nil, err
	}

	files = append(files, File{
		Path:    path.Join("proto", "zz_generated_"+protoName+".proto"),
		Content: header + "\n" + string(doc),
	})

	body, err := cellmanifest.Marshal(manifest)
	if err != nil {
		return nil, fmt.Errorf("emitting the skeleton: %w", err)
	}

	files = append(files, File{Path: cellmanifest.FileName, Content: string(body)})

	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })

	return files, nil
}

func addServiceToManifest(m *cellmanifest.Manifest, v serviceView) {
	m.Provides.Controllers = append(m.Provides.Controllers, cellmanifest.Controller{
		Trait:  v.ControllerTrait,
		Impl:   v.ControllerTrait + "Impl",
		Module: v.ModulePrefix + "controller",
		Ports:  []string{},
	})

	m.Provides.Drivers = append(m.Provides.Drivers, cellmanifest.Driver{
		Name:     v.DriverName,
		Type:     v.DriverStruct,
		Module:   v.ModulePrefix + "driver::" + v.DriverModule,
		Requires: []string{v.ControllerTrait},
		Config: map[string]cellmanifest.ConfigField{
			"addr": {
				Type:        cellmanifest.FieldTypeString,
				Default:     DefaultAddress,
				Description: "The host and port the " + v.ServiceSnake + " grpc driver binds",
			},
		},
	})

	m.Provides.Ports = append(m.Provides.Ports, cellmanifest.Port{
		Trait:  v.ClientTrait,
		Module: v.ModulePrefix + "port::" + v.ServiceSnake + "_client",
	})

	m.Provides.Adapters = append(m.Provides.Adapters, cellmanifest.Adapter{
		Name:       v.ClientName,
		Type:       v.ClientStruct,
		Module:     v.ModulePrefix + "adapter::" + v.ClientModule,
		Implements: v.ClientTrait,
		Fallible:   true,
		Config: map[string]cellmanifest.ConfigField{
			"endpoint": {
				Type:        cellmanifest.FieldTypeString,
				Default:     DefaultEndpoint,
				Description: "The grpc endpoint the " + v.ServiceSnake + " client dials",
			},
		},
	})
}

func render(name string, data any) (string, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", fmt.Errorf("rendering %s: %w", name, err)
	}

	return buf.String(), nil
}

var templates = template.Must(template.New("grpcrust").Parse(`
{{- define "cell_mod" -}}
{{ .Header }}
{{ range .Layers }}
pub mod {{ . }};
{{- end }}
{{ end -}}

{{- define "layer_mod" -}}
{{ .Header }}
{{- if .Allow }}
#![allow(clippy::disallowed_methods, clippy::disallowed_types)]
{{- end }}
{{ range .Entries }}
pub mod {{ .Module }};
{{- end }}
{{- range .UserMods }}

mod {{ . }};
{{- end }}
{{- range .Entries }}{{ if .Alias }}

pub use {{ .Module }} as {{ .Alias }};
{{- end }}{{ if .Exports }}

pub use {{ .Module }}::{{ "{" }}{{ range $i, $e := .Exports }}{{ if $i }}, {{ end }}{{ $e }}{{ end }}{{ "}" }};
{{- end }}{{ end }}
{{ end -}}

{{- define "types" -}}
{{ .Header }}
{{ range .Messages }}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct {{ .Name }} {
{{- range .Fields }}
    pub {{ .Ident }}: {{ .CoreType }},
{{- end }}
}
{{ end -}}
{{ end -}}

{{- define "port" -}}
{{ .Header }}

use {{ .CratePath }}types::{{ .ServiceSnake }}_messages::{{ "{" }}{{ range $i, $t := .TraitTypes }}{{ if $i }}, {{ end }}{{ $t }}{{ end }}{{ "}" }};

#[derive(Debug, thiserror::Error)]
pub enum {{ .ClientError }} {
{{- range .Rpcs }}
    #[error("calling {{ .Ident }}")]
    {{ .Pascal }} {
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
{{- end }}
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ .ClientTrait }}: Send + Sync {
{{- range .Rpcs }}
    fn {{ .Ident }}(&self, request: {{ .Request }}) -> Result<{{ .Response }}, {{ $.ClientError }}>;
{{- end }}
}
{{ end -}}

{{- define "controller" -}}
{{ .Header }}

use {{ .CratePath }}types::{{ .ServiceSnake }}_messages::{{ "{" }}{{ range $i, $t := .TraitTypes }}{{ if $i }}, {{ end }}{{ $t }}{{ end }}{{ "}" }};

#[derive(Debug, thiserror::Error)]
pub enum {{ .ControllerError }} {
    #[error("validating {field:?}: {reason}")]
    Invalid { field: String, reason: String },
    #[error("running {operation:?}: not implemented")]
    NotImplemented { operation: String },
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ .ControllerTrait }}: Send + Sync {
{{- range .Rpcs }}
    fn {{ .Ident }}(&self, request: {{ .Request }}) -> Result<{{ .Response }}, {{ $.ControllerError }}>;
{{- end }}
}

pub struct {{ .ControllerTrait }}Impl;

impl {{ .ControllerTrait }}Impl {
    pub fn new() -> Self {
        Self
    }
}

impl Default for {{ .ControllerTrait }}Impl {
    fn default() -> Self {
        Self::new()
    }
}
{{ end -}}

{{- define "adapter" -}}
{{ .Header }}

use {{ .CratePath }}port::{{ .ServiceSnake }}_client::{{ "{" }}{{ .ClientTrait }}, {{ .ClientError }}{{ "}" }};
use {{ .CratePath }}types::{{ .ServiceSnake }}_messages::{{ "{" }}{{ range $i, $t := .AllTypes }}{{ if $i }}, {{ end }}{{ $t }}{{ end }}{{ "}" }};

mod pb {
    tonic::include_proto!("{{ .Package }}");
}
{{ range .Messages }}
impl From<{{ .Name }}> for pb::{{ .Name }} {
    fn from(v: {{ .Name }}) -> Self {
        Self {
{{- range .Fields }}
            {{ .Ident }}: {{ .ToPb }},
{{- end }}
        }
    }
}

impl From<pb::{{ .Name }}> for {{ .Name }} {
    fn from(v: pb::{{ .Name }}) -> Self {
        Self {
{{- range .Fields }}
            {{ .Ident }}: {{ .ToCore }},
{{- end }}
        }
    }
}
{{ end }}
pub struct {{ .ClientConfig }} {
    pub endpoint: String,
}

impl Default for {{ .ClientConfig }} {
    fn default() -> Self {
        Self {
            endpoint: "{{ .DefaultEndpoint }}".to_string(),
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum {{ .ClientSetupError }} {
    #[error("reading the grpc endpoint {endpoint:?}")]
    Endpoint {
        endpoint: String,
        #[source]
        source: tonic::transport::Error,
    },
}

pub struct {{ .ClientStruct }} {
    channel: tonic::transport::Channel,
}

impl {{ .ClientStruct }} {
    pub fn new(config: {{ .ClientConfig }}) -> Result<Self, {{ .ClientSetupError }}> {
        let endpoint = config.endpoint;

        let channel = tonic::transport::Endpoint::from_shared(endpoint.clone())
            .map_err(|source| {{ .ClientSetupError }}::Endpoint {
                endpoint,
                source,
            })?
            .connect_lazy();

        Ok(Self { channel })
    }
}

impl {{ .ClientTrait }} for {{ .ClientStruct }} {
{{- range .Rpcs }}
    fn {{ .Ident }}(&self, request: {{ .Request }}) -> Result<{{ .Response }}, {{ $.ClientError }}> {
        let channel = self.channel.clone();

        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let mut client = pb::{{ $.PbClientMod }}::{{ $.ServicePascal }}Client::new(channel);

                client
                    .{{ .Ident }}({{ .PbRequest }}::from(request))
                    .await
                    .map(|response| {{ .Response }}::from(response.into_inner()))
                    .map_err(|source| {{ $.ClientError }}::{{ .Pascal }} {
                        source: Box::new(source),
                    })
            })
        })
    }
{{ end -}}
}
{{ end -}}

{{- define "driver" -}}
{{ .Header }}

use std::sync::Arc;

use {{ .CratePath }}controller::{{ .ControllerTrait }};
use {{ .CratePath }}types::{{ .ServiceSnake }}_messages::{{ "{" }}{{ range $i, $t := .AllTypes }}{{ if $i }}, {{ end }}{{ $t }}{{ end }}{{ "}" }};

mod pb {
    tonic::include_proto!("{{ .Package }}");
}
{{ range .Messages }}
impl From<pb::{{ .Name }}> for {{ .Name }} {
    fn from(v: pb::{{ .Name }}) -> Self {
        Self {
{{- range .Fields }}
            {{ .Ident }}: {{ .ToCore }},
{{- end }}
        }
    }
}

impl From<{{ .Name }}> for pb::{{ .Name }} {
    fn from(v: {{ .Name }}) -> Self {
        Self {
{{- range .Fields }}
            {{ .Ident }}: {{ .ToPb }},
{{- end }}
        }
    }
}
{{ end }}
pub struct {{ .DriverConfig }} {
    pub addr: String,
}

impl Default for {{ .DriverConfig }} {
    fn default() -> Self {
        Self {
            addr: "{{ .DefaultAddress }}".to_string(),
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum {{ .DriverError }} {
    #[error("binding the {{ .ServiceSnake }} grpc driver to {address:?}")]
    Bind {
        address: String,
        #[source]
        source: std::io::Error,
    },
    #[error("reading the port the {{ .ServiceSnake }} grpc driver bound on {address:?}")]
    Port {
        address: String,
        #[source]
        source: std::io::Error,
    },
    #[error("serving {{ .ServiceSnake }} grpc on {address:?}")]
    Serve {
        address: String,
        #[source]
        source: tonic::transport::Error,
    },
    #[error("using the {{ .ServiceSnake }} grpc driver for {address:?}: it is not bound yet")]
    NotBound { address: String },
}

#[derive(Clone)]
pub struct {{ .DriverService }} {
    controller: Arc<dyn {{ .ControllerTrait }} + Send + Sync>,
}

pub struct {{ .DriverStruct }} {
    config: {{ .DriverConfig }},
    service: {{ .DriverService }},
    incoming: Option<tonic::transport::server::TcpIncoming>,
}

impl {{ .DriverStruct }} {
    pub fn new(config: {{ .DriverConfig }}, controller: Arc<dyn {{ .ControllerTrait }} + Send + Sync>) -> Self {
        Self {
            config,
            service: {{ .DriverService }} { controller },
            incoming: None,
        }
    }

    pub async fn bind(&mut self) -> Result<(), {{ .DriverError }}> {
        let listener = tokio::net::TcpListener::bind(&self.config.addr)
            .await
            .map_err(|source| {{ .DriverError }}::Bind {
                address: self.config.addr.clone(),
                source,
            })?;

        self.incoming = Some(tonic::transport::server::TcpIncoming::from(listener));

        Ok(())
    }

    pub fn local_port(&self) -> Result<u16, {{ .DriverError }}> {
        let incoming = self
            .incoming
            .as_ref()
            .ok_or_else(|| {{ .DriverError }}::NotBound {
                address: self.config.addr.clone(),
            })?;

        incoming
            .local_addr()
            .map(|addr| addr.port())
            .map_err(|source| {{ .DriverError }}::Port {
                address: self.config.addr.clone(),
                source,
            })
    }

    pub fn announce(&self) -> Result<(), {{ .DriverError }}> {
        println!("LISTENING_GRPC {}", self.local_port()?);

        Ok(())
    }

    pub async fn serve(self) -> Result<(), {{ .DriverError }}> {
        let address = self.config.addr.clone();

        let incoming = self.incoming.ok_or({{ .DriverError }}::NotBound {
            address: address.clone(),
        })?;

        tonic::transport::Server::builder()
            .add_service(pb::{{ .PbServerMod }}::{{ .ServicePascal }}Server::new(self.service))
            .serve_with_incoming(incoming)
            .await
            .map_err(|source| {{ .DriverError }}::Serve { address, source })
    }
}

#[tonic::async_trait]
impl pb::{{ .PbServerMod }}::{{ .ServicePascal }} for {{ .DriverService }} {
{{- range .Rpcs }}
    async fn {{ .Ident }}(&self, request: tonic::Request<{{ .PbRequest }}>) -> Result<tonic::Response<{{ .PbResponse }}>, tonic::Status> {
        let core_request = {{ .Request }}::from(request.into_inner());

        let out = self
            .controller
            .{{ .Ident }}(core_request)
            .map_err(|source| tonic::Status::internal(source.to_string()))?;

        Ok(tonic::Response::new({{ .PbResponse }}::from(out)))
    }
{{ end -}}
}
{{ end -}}

{{- define "build" -}}
{{ .Header }}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let file_descriptors = protox::compile(
        ["src/{{ .Cell }}/proto/zz_generated_{{ .Name }}.proto"],
        ["src/{{ .Cell }}/proto"],
    )?;

    tonic_prost_build::configure()
        .build_client(true)
        .build_server(true)
        .compile_fds(file_descriptors)?;

    Ok(())
}
{{ end -}}
`))
