// Generated by forge-factory. DO NOT EDIT. Source: forge-factory.yaml

module github.com/alexandremahdhaoui/forge-dev-codegen

go 1.26.5

require (
	github.com/alexandremahdhaoui/forge v0.43.0
	github.com/modelcontextprotocol/go-sdk v1.7.0
	github.com/spf13/cobra v1.10.2
	sigs.k8s.io/yaml v1.6.0
)

require (
	github.com/google/jsonschema-go v0.4.3 // indirect
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/segmentio/asm v1.1.3 // indirect
	github.com/segmentio/encoding v0.5.4 // indirect
	github.com/spf13/pflag v1.0.10 // indirect
	github.com/stretchr/testify v1.12.1 // indirect
	github.com/yosida95/uritemplate/v3 v3.0.2 // indirect
	go.yaml.in/yaml/v2 v2.4.3 // indirect
	go.yaml.in/yaml/v3 v3.0.5 // indirect
	golang.org/x/oauth2 v0.35.0 // indirect
	golang.org/x/sync v0.20.0 // indirect
	golang.org/x/sys v0.47.0 // indirect
	golang.org/x/time v0.15.0 // indirect
)
