// Code generated by tui-rust (forge-dev-codegen). DO NOT EDIT.

pub mod zz_generated_keyboard;
pub mod zz_generated_screen;

pub use zz_generated_keyboard as keyboard;

pub use zz_generated_screen as screen;
