// Code generated by tui-rust (forge-dev-codegen). DO NOT EDIT.

use crate::tui::types::frame::{Frame, Prompt};

#[derive(Debug, thiserror::Error)]
pub enum ScreenError {
    #[error("entering the screen")]
    Enter {
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
    #[error("drawing a frame of {width}x{height}")]
    Draw {
        width: u16,
        height: u16,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
    #[error("leaving the screen")]
    Leave {
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
}

#[cfg_attr(test, mockall::automock)]
pub trait Screen: Send + Sync {
    fn enter(&self) -> Result<(), ScreenError>;
    fn draw(&self, frame: &Frame, prompt: &Prompt) -> Result<(), ScreenError>;
    fn leave(&self) -> Result<(), ScreenError>;
}
