// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package taxonomy

import (
	"fmt"
	"sort"
	"strings"
)

const OwnerSlot = "{owner}"

const VectorFiller = "generated by vectors-rust"

type Field struct {
	Name string
	Type string
}

type Member struct {
	Variant        string
	Fields         []Field
	Display        string
	Wire           string
	RestStatus     int
	RestStatusExpr string
	GrpcMethod     string
	GrpcCode       string
	Generic        bool
}

func (m Member) FieldList() string {
	parts := make([]string, 0, len(m.Fields))
	for _, f := range m.Fields {
		parts = append(parts, f.Name+": "+f.Type)
	}

	return strings.Join(parts, ", ")
}

func (m Member) Literal(errorType, subject, filler string) string {
	parts := make([]string, 0, len(m.Fields))

	for i, f := range m.Fields {
		value := filler
		if i == 0 {
			value = subject
		}

		parts = append(parts, fmt.Sprintf("%s: %q.to_string()", f.Name, value))
	}

	return fmt.Sprintf("%s::%s { %s }", errorType, m.Variant, strings.Join(parts, ", "))
}

func (m Member) DetailExpr() string {
	if m.Generic {
		return `"internal error".to_string()`
	}

	return "error.to_string()"
}

type WireMember struct {
	Type    string
	Variant string
	Display string
}

const wireRuntime = "runtime"

var runtime = Member{
	Variant:        "Runtime",
	Fields:         []Field{{Name: "operation", Type: "String"}},
	Display:        "running {operation:?}",
	Wire:           wireRuntime,
	RestStatus:     500,
	RestStatusExpr: "StatusCode::INTERNAL_SERVER_ERROR",
	GrpcMethod:     "internal",
	GrpcCode:       "Internal",
	Generic:        true,
}

var detailed = []Member{
	{
		Variant:        "Authentication",
		Fields:         []Field{{Name: "subject", Type: "String"}, {Name: "reason", Type: "String"}},
		Display:        "authenticating {subject:?}: {reason}",
		Wire:           "authentication",
		RestStatus:     401,
		RestStatusExpr: "StatusCode::UNAUTHORIZED",
		GrpcMethod:     "unauthenticated",
		GrpcCode:       "Unauthenticated",
	},
	{
		Variant:        "Authorization",
		Fields:         []Field{{Name: "subject", Type: "String"}, {Name: "reason", Type: "String"}},
		Display:        "authorizing {subject:?}: {reason}",
		Wire:           "authorization",
		RestStatus:     403,
		RestStatusExpr: "StatusCode::FORBIDDEN",
		GrpcMethod:     "permission_denied",
		GrpcCode:       "PermissionDenied",
	},
	{
		Variant:        "NotFound",
		Fields:         []Field{{Name: "id", Type: "String"}},
		Display:        "finding " + OwnerSlot + " {id:?}: not found",
		Wire:           "semantic",
		RestStatus:     404,
		RestStatusExpr: "StatusCode::NOT_FOUND",
		GrpcMethod:     "not_found",
		GrpcCode:       "NotFound",
	},
	{
		Variant:        "Invalid",
		Fields:         []Field{{Name: "field", Type: "String"}, {Name: "reason", Type: "String"}},
		Display:        "validating {field:?}: {reason}",
		Wire:           "validation",
		RestStatus:     0,
		RestStatusExpr: "invalid",
		GrpcMethod:     "invalid_argument",
		GrpcCode:       "InvalidArgument",
	},
	{
		Variant:        "Semantic",
		Fields:         []Field{{Name: "resource", Type: "String"}, {Name: "reason", Type: "String"}},
		Display:        "reconciling {resource:?}: {reason}",
		Wire:           "semantic",
		RestStatus:     409,
		RestStatusExpr: "StatusCode::CONFLICT",
		GrpcMethod:     "failed_precondition",
		GrpcCode:       "FailedPrecondition",
	},
	{
		Variant:        "RateLimited",
		Fields:         []Field{{Name: "subject", Type: "String"}, {Name: "reason", Type: "String"}},
		Display:        "rate limiting {subject:?}: {reason}",
		Wire:           "rateLimiting",
		RestStatus:     429,
		RestStatusExpr: "StatusCode::TOO_MANY_REQUESTS",
		GrpcMethod:     "resource_exhausted",
		GrpcCode:       "ResourceExhausted",
	},
	{
		Variant:        "NotImplemented",
		Fields:         []Field{{Name: "operation", Type: "String"}},
		Display:        "running {operation:?}: not implemented",
		Wire:           wireRuntime,
		RestStatus:     501,
		RestStatusExpr: "StatusCode::NOT_IMPLEMENTED",
		GrpcMethod:     "unimplemented",
		GrpcCode:       "Unimplemented",
	},
}

var wire = []WireMember{
	{Type: wireRuntime, Variant: "Runtime", Display: "calling {operation:?}: {message}"},
	{Type: "authentication", Variant: "Authentication", Display: "calling {operation:?}: authentication refused: {message}"},
	{Type: "authorization", Variant: "Authorization", Display: "calling {operation:?}: authorization refused: {message}"},
	{Type: "validation", Variant: "Validation", Display: "calling {operation:?}: validation failed: {message}"},
	{Type: "semantic", Variant: "Semantic", Display: "calling {operation:?}: {message}"},
	{Type: "rateLimiting", Variant: "RateLimiting", Display: "calling {operation:?}: rate limited: {message}"},
}

func Detailed(owner string) []Member {
	out := make([]Member, 0, len(detailed))

	for _, m := range detailed {
		m.Display = strings.ReplaceAll(m.Display, OwnerSlot, owner)
		out = append(out, m)
	}

	return out
}

func Runtime(owner string) Member {
	m := runtime
	m.Display = strings.ReplaceAll(m.Display, OwnerSlot, owner)

	return m
}

func All(owner string) []Member {
	return append([]Member{Runtime(owner)}, Detailed(owner)...)
}

func WireRuntime() WireMember {
	return wire[0]
}

func WireDetailed() []WireMember {
	return append([]WireMember(nil), wire[1:]...)
}

func ByVariant(variant string) (Member, bool) {
	for _, m := range All("") {
		if m.Variant == variant {
			return m, true
		}
	}

	return Member{}, false
}

func ByRestStatus(status int) (Member, bool) {
	for _, m := range detailed {
		if m.RestStatus != 0 && m.RestStatus == status {
			return m, true
		}
	}

	return Member{}, false
}

func Invalid() Member {
	m, _ := ByVariant("Invalid")

	return m
}

func VariantNames() []string {
	out := make([]string, 0, len(detailed)+1)
	for _, m := range All("") {
		out = append(out, m.Variant)
	}

	sort.Strings(out)

	return out
}

func DetailedVariantNames() []string {
	out := make([]string, 0, len(detailed))
	for _, m := range detailed {
		out = append(out, m.Variant)
	}

	sort.Strings(out)

	return out
}

func RestStatusList() string {
	parts := make([]string, 0, len(detailed))

	for _, m := range detailed {
		if m.RestStatus == 0 {
			parts = append(parts, m.Variant+" (the operation's invalid status)")

			continue
		}

		parts = append(parts, fmt.Sprintf("%s (%d)", m.Variant, m.RestStatus))
	}

	return strings.Join(parts, ", ")
}
