// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/restspec"
)

// NewHandlers wires the generate tool: the model's OpenAPI paths decide
// the routes, fastapi serves them. Same contract as forge-dev's builtin
// go cell - the paths are the surface, one handler per operation, a
// LISTENING line on bind, a missing handler answers 501.
func NewHandlers() Handlers {
	return Handlers{
		Generate: func(_ context.Context, input GenerateInput) (*GenerateOutput, error) {
			if input.Kind != "rest-api" {
				return nil, fmt.Errorf("emitting %q: rest-python-fastapi fills the rest-api cell only", input.Kind)
			}

			if input.Language != "python" {
				return nil, fmt.Errorf("emitting for %q: rest-python-fastapi generates python only", input.Language)
			}

			operations, err := restspec.Operations([]byte(input.OpenapiSpec))
			if err != nil {
				return nil, fmt.Errorf("reading the paths for %q: %w", input.Name, err)
			}

			var buf bytes.Buffer
			if err := fastapiTmpl.Execute(&buf, map[string]any{
				"Name":       input.Name,
				"Version":    input.Version,
				"EnvPrefix":  envPrefix(input.Name),
				"Checksum":   input.Checksum,
				"Operations": operations,
			}); err != nil {
				return nil, fmt.Errorf("rendering the fastapi server for %q: %w", input.Name, err)
			}

			return &GenerateOutput{
				Files: []GeneratedFile{{Path: "zz_generated_rest.py", Content: buf.String()}},
			}, nil
		},
	}
}

// envPrefix turns rest-demo into REST_DEMO.
func envPrefix(name string) string {
	return strings.ToUpper(strings.NewReplacer("-", "_", ".", "_").Replace(name))
}

var fastapiTmpl = template.Must(template.New("fastapi").Parse(`# Code generated by rest-python-fastapi (forge-dev-codegen). DO NOT EDIT.
# Source: forge-dev.yaml
# SourceChecksum: {{ .Checksum }}

"""{{ .Name }} v{{ .Version }}: a rest-api kind program served by fastapi.

The author writes new_rest_handlers() in handlers.py beside this module;
the routes derive from the OpenAPI paths verbatim, so the server cannot
drift from the spec. Binds {{ .EnvPrefix }}_ADDR (default 127.0.0.1:0)
and prints LISTENING <port> once bound.
"""

import os
import socket
import sys

import uvicorn
from fastapi import FastAPI, Request, Response

from handlers import new_rest_handlers

_handlers = new_rest_handlers()

app = FastAPI()


def _route(name: str):
    def endpoint(request: Request) -> Response:
        handler = _handlers.get(name)
        if handler is None:
            return Response(
                status_code=501,
                content=f"operation {name} is not implemented",
                media_type="text/plain",
            )
        status, body = handler(dict(request.path_params))
        return Response(status_code=status, content=body, media_type="text/plain")

    return endpoint

{{ range .Operations }}
app.add_api_route("{{ .Path }}", _route("{{ .CamelName }}"), methods=["{{ .Method }}"])
{{- end }}


def main() -> int:
    addr = os.environ.get("{{ .EnvPrefix }}_ADDR", "127.0.0.1:0")
    host, _, port_s = addr.partition(":")

    sock = socket.socket()
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind((host or "127.0.0.1", int(port_s or 0)))
    # Listen before announcing: a bound socket refuses connections until
    # someone listens, and the announcement is a promise.
    sock.listen(2048)

    print(f"LISTENING {sock.getsockname()[1]}", flush=True)

    uvicorn.run(app, fd=sock.fileno(), log_level="warning")
    return 0


if __name__ == "__main__":
    sys.exit(main())
`))
