// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"context"
	"fmt"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/surface"
)

// NewHandlers wires the generate tool: the model's surface.commands decide
// the subcommands, commander does the dispatch. The emitted module keeps
// the cli cell's behavior contract - raw args to the handler, exit codes
// pass through, an unknown command exits 2 naming itself.
func NewHandlers() Handlers {
	return Handlers{
		Generate: func(_ context.Context, input GenerateInput) (*GenerateOutput, error) {
			if input.Kind != "cli" {
				return nil, fmt.Errorf("emitting %q: cli-typescript-commander fills the cli cell only", input.Kind)
			}

			if input.Language != "typescript" {
				return nil, fmt.Errorf("emitting for %q: cli-typescript-commander generates typescript only", input.Language)
			}

			commands, err := surface.Commands(input.Surface)
			if err != nil {
				return nil, fmt.Errorf("reading surface.commands for %q: %w", input.Name, err)
			}

			var buf bytes.Buffer
			if err := commanderTmpl.Execute(&buf, map[string]any{
				"Name":        input.Name,
				"Version":     input.Version,
				"Description": input.Description,
				"Checksum":    input.Checksum,
				"Commands":    commands,
			}); err != nil {
				return nil, fmt.Errorf("rendering the commander dispatcher for %q: %w", input.Name, err)
			}

			return &GenerateOutput{
				Files: []GeneratedFile{{Path: "zz_generated.cli.ts", Content: buf.String()}},
			}, nil
		},
	}
}

var commanderTmpl = template.Must(template.New("commander").Parse(`// Code generated by cli-typescript-commander (forge-dev-codegen). DO NOT EDIT.
// Source: forge-dev.yaml
// SourceChecksum: {{ .Checksum }}

// {{ .Name }} v{{ .Version }}: a cli kind program dispatched by commander.
// The author writes newCLIHandlers() in handlers.ts beside this module; the
// behavior contract is every cli cell's - raw args to the handler, exit
// codes pass through, an unknown command exits 2 naming itself.

import { Command, CommanderError } from "commander";

import { newCLIHandlers } from "./handlers";

// One handler per declared command. The type makes every field required.
export interface CLIHandlers {
{{- range .Commands }}
  // Runs the {{ .Name }} command. {{ .Description }}
  {{ .GoName }}: (args: readonly string[]) => number;
{{- end }}
}

// dispatch routes argv through commander and answers the process exit
// code. Every subcommand takes its args raw, exactly as the builtin cell
// hands them over.
export function dispatch(handlers: CLIHandlers, argv: readonly string[]): number {
  let code = 0;

  const program = new Command("{{ .Name }}")
    .description("{{ .Description }}")
    .version("{{ .Version }}")
    .exitOverride()
    .configureOutput({ writeErr: () => undefined });
{{ range .Commands }}
  program
    .command("{{ .Name }}")
    .description("{{ .Description }}")
    .helpOption(false)
    .allowUnknownOption(true)
    .allowExcessArguments(true)
    .argument("[args...]")
    .action((args: string[]) => {
      code = handlers.{{ .GoName }}(args);
    });
{{ end }}
  try {
    program.parse([...argv], { from: "user" });
  } catch (err) {
    if (err instanceof CommanderError && err.code === "commander.unknownCommand") {
      process.stderr.write('{{ .Name }}: unknown command "' + String(argv[0] ?? "") + '"\n');

      return 2;
    }

    if (
      err instanceof CommanderError &&
      (err.code === "commander.helpDisplayed" || err.code === "commander.version")
    ) {
      return 0;
    }

    const message = err instanceof Error ? err.message : String(err);
    process.stderr.write("{{ .Name }}: " + message + "\n");

    return 2;
  }

  return code;
}

process.exit(dispatch(newCLIHandlers(), process.argv.slice(2)));
`))
