// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/restspec"
)

// NewHandlers wires the generate tool: the model's OpenAPI paths decide
// the routes, fastify serves them. Same contract as forge-dev's builtin
// go cell - the paths are the surface, one typed handler per operation, a
// LISTENING line on bind.
func NewHandlers() Handlers {
	return Handlers{
		Generate: func(_ context.Context, input GenerateInput) (*GenerateOutput, error) {
			if input.Kind != "rest-api" {
				return nil, fmt.Errorf("emitting %q: rest-typescript-fastify fills the rest-api cell only", input.Kind)
			}

			if input.Language != "typescript" {
				return nil, fmt.Errorf("emitting for %q: rest-typescript-fastify generates typescript only", input.Language)
			}

			operations, err := restspec.Operations([]byte(input.OpenapiSpec))
			if err != nil {
				return nil, fmt.Errorf("reading the paths for %q: %w", input.Name, err)
			}

			var buf bytes.Buffer
			if err := fastifyTmpl.Execute(&buf, map[string]any{
				"Name":       input.Name,
				"Version":    input.Version,
				"EnvPrefix":  envPrefix(input.Name),
				"Checksum":   input.Checksum,
				"Operations": operations,
			}); err != nil {
				return nil, fmt.Errorf("rendering the fastify server for %q: %w", input.Name, err)
			}

			return &GenerateOutput{
				Files: []GeneratedFile{{Path: "zz_generated.rest.ts", Content: buf.String()}},
			}, nil
		},
	}
}

// envPrefix turns rest-demo into REST_DEMO.
func envPrefix(name string) string {
	return strings.ToUpper(strings.NewReplacer("-", "_", ".", "_").Replace(name))
}

var fastifyTmpl = template.Must(template.New("fastify").Parse(`// Code generated by rest-typescript-fastify (forge-dev-codegen). DO NOT EDIT.
// Source: forge-dev.yaml
// SourceChecksum: {{ .Checksum }}

// {{ .Name }} v{{ .Version }}: a rest-api kind program served by fastify.
// The author writes newRESTHandlers() in handlers.ts beside this module;
// the routes derive from the OpenAPI paths verbatim, so the server cannot
// drift from the spec. Binds {{ .EnvPrefix }}_ADDR (default 127.0.0.1:0)
// and prints LISTENING <port> once bound.

import Fastify from "fastify";

import { newRESTHandlers } from "./handlers";

// The answer of one operation: a status and a plain text body.
export interface RESTAnswer {
  status: number;
  body: string;
}

// One handler per operation of the OpenAPI paths. The type makes every
// field required.
export interface RESTHandlers {
{{- range .Operations }}
  // Serves {{ .Method }} {{ .Path }}. {{ .Description }}
  {{ .GoName }}: (params: Record<string, string>) => RESTAnswer;
{{- end }}
}

async function main(): Promise<void> {
  const handlers = newRESTHandlers();
  const app = Fastify({ logger: false });
{{ range .Operations }}
  app.route({
    method: "{{ .Method }}",
    url: "{{ .ColonPath }}",
    handler: async (request, reply) => {
      const out = handlers.{{ .GoName }}(request.params as Record<string, string>);
      await reply.status(out.status).type("text/plain").send(out.body);
    },
  });
{{ end }}
  const addr = process.env.{{ .EnvPrefix }}_ADDR ?? "127.0.0.1:0";
  const [host, portRaw] = addr.split(":");

  await app.listen({ host: host || "127.0.0.1", port: Number(portRaw ?? "0") });

  const bound = app.server.address();
  const port = typeof bound === "object" && bound !== null ? bound.port : 0;
  process.stdout.write(` + "`LISTENING ${port}\\n`" + `);
}

void main();
`))
