// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package restrust

import (
	"bytes"
	"fmt"
	"path"
	"sort"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/crateports"
	"github.com/alexandremahdhaoui/forge-dev-codegen/pkg/cellmanifest"
	"github.com/alexandremahdhaoui/forge-dev-codegen/pkg/rustname"
)

const header = "// Code generated by rest-rust (forge-dev-codegen). DO NOT EDIT."

const Generator = "rest-rust (forge-dev-codegen)"

const DefaultCell = "rest"

const DefaultAddress = "127.0.0.1:0"

const DefaultStorePath = ":memory:"

const DefaultStoreCapacity = 100

const DefaultBaseURL = "http://127.0.0.1:8080"

const (
	SideServer = "server"
	SideClient = "client"
	SideBoth   = "both"
)

var Layers = []string{"adapter", "controller", "driver", "port", "types"}

var allowingLayers = map[string]bool{"adapter": true, "driver": true}

type Options struct {
	Service   string
	Cell      string
	Side      string
	Header    string
	Generator string
}

type File struct {
	Path    string
	Content string
}

type modEntry struct {
	Module  string
	Alias   string
	Exports []string
}

type layerMod struct {
	Header   string
	Allow    bool
	Entries  []modEntry
	UserMods []string
}

func checkSide(side string) error {
	switch side {
	case SideServer, SideClient, SideBoth:
		return nil
	default:
		return fmt.Errorf("emitting the rest cell: side %q is not one of %s, %s and %s", side, SideServer, SideClient, SideBoth)
	}
}

func Generate(doc []byte, opts Options) ([]File, error) {
	if opts.Service == "" {
		return nil, fmt.Errorf("emitting the rest cell: the service name is required")
	}

	if err := checkName("service", opts.Service); err != nil {
		return nil, fmt.Errorf("emitting the rest cell: %w", err)
	}

	if opts.Cell == "" {
		opts.Cell = DefaultCell
	}

	if !rustname.IsModuleName(opts.Cell) {
		return nil, fmt.Errorf("emitting the rest cell: cell %q is not a name Rust can spell as a module, use lowercase letters, digits and underscores and start with a letter", opts.Cell)
	}

	if opts.Side == "" {
		opts.Side = SideServer
	}

	if err := checkSide(opts.Side); err != nil {
		return nil, err
	}

	spec, err := Parse(doc)
	if err != nil {
		return nil, err
	}

	v := buildView(spec, opts)

	if opts.Header != "" {
		v.Header = opts.Header
	}

	files := []File{}

	add := func(p, name string, data any) error {
		content, err := render(name, data)
		if err != nil {
			return err
		}

		files = append(files, File{Path: p, Content: content})

		return nil
	}

	entries := map[string][]modEntry{}
	userMods := map[string][]string{}

	mount := func(layer string, entry modEntry) {
		entries[layer] = append(entries[layer], entry)
	}

	steps := []func() error{}

	for _, t := range v.Types {
		t := t

		mount("types", modEntry{Module: "zz_generated_" + t.Snake, Alias: t.Snake})

		steps = append(steps, func() error {
			return add(path.Join("types", "zz_generated_"+t.Snake+".rs"), "type", map[string]any{"Header": v.Header, "Type": t})
		})
	}

	if v.Server {
		steps = append(steps, serverSteps(v, add, mount, userMods)...)
	}

	if v.Client {
		steps = append(steps, clientSteps(v, add, mount)...)
	}

	for _, layer := range Layers {
		layer := layer

		mod := layerMod{
			Header:   v.Header,
			Allow:    allowingLayers[layer],
			Entries:  entries[layer],
			UserMods: userMods[layer],
		}
		sort.Slice(mod.Entries, func(i, j int) bool { return mod.Entries[i].Module < mod.Entries[j].Module })
		sort.Strings(mod.UserMods)

		steps = append(steps, func() error {
			return add(path.Join(layer, "mod.rs"), "layer_mod", mod)
		})
	}

	steps = append(steps, func() error {
		return add("mod.rs", "cell_mod", map[string]any{"Header": v.Header, "Layers": Layers})
	})

	for _, step := range steps {
		if err := step(); err != nil {
			return nil, err
		}
	}

	manifest := BuildManifest(v)
	if opts.Generator != "" {
		manifest.Generator = opts.Generator
	}

	body, err := cellmanifest.Marshal(manifest)
	if err != nil {
		return nil, fmt.Errorf("emitting the rest cell: %w", err)
	}

	files = append(files, File{Path: cellmanifest.FileName, Content: string(body)})

	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })

	return files, nil
}

type adder func(p, name string, data any) error

type mounter func(layer string, entry modEntry)

func serverSteps(v view, add adder, mount mounter, userMods map[string][]string) []func() error {
	mount("driver", modEntry{Module: "zz_generated_wire", Alias: "wire"})
	mount("driver", modEntry{Module: "zz_generated_http_driver", Alias: "http_driver"})

	steps := []func() error{
		func() error { return add(path.Join("driver", "zz_generated_wire.rs"), "wire", v) },
		func() error {
			return add(path.Join("driver", "zz_generated_http_driver.rs"), "http_driver", v)
		},
	}

	for _, s := range v.Stores {
		s := s

		mount("port", modEntry{Module: "zz_generated_" + s.PortSnake, Alias: s.PortSnake})

		steps = append(steps, func() error {
			return add(path.Join("port", "zz_generated_"+s.PortSnake+".rs"), "port", map[string]any{"Header": v.Header, "Store": s, "CratePath": v.CratePath})
		})

		if s.HasSqlite {
			mount("adapter", modEntry{Module: "zz_generated_" + s.Module, Alias: s.Module})

			steps = append(steps, func() error {
				return add(path.Join("adapter", "zz_generated_"+s.Module+".rs"), "sqlite", map[string]any{"Header": v.Header, "Store": s, "CratePath": v.CratePath})
			})
		}

		if s.HasMemory {
			mount("adapter", modEntry{Module: "zz_generated_" + s.MemoryModule, Alias: s.MemoryModule})

			steps = append(steps, func() error {
				return add(path.Join("adapter", "zz_generated_"+s.MemoryModule+".rs"), "memory_store", map[string]any{"Header": v.Header, "Store": s, "CratePath": v.CratePath})
			})
		}
	}

	for _, e := range v.Events {
		e := e

		mount("port", modEntry{Module: "zz_generated_" + e.PortSnake, Alias: e.PortSnake})

		steps = append(steps, func() error {
			return add(path.Join("port", "zz_generated_"+e.PortSnake+".rs"), "subscribe_port", map[string]any{"Header": v.Header, "Event": e, "CratePath": v.CratePath})
		})

		if e.HasMemory {
			mount("adapter", modEntry{Module: "zz_generated_" + e.MemoryModule, Alias: e.MemoryModule})

			steps = append(steps, func() error {
				return add(path.Join("adapter", "zz_generated_"+e.MemoryModule+".rs"), "memory_feed", map[string]any{"Header": v.Header, "Event": e, "CratePath": v.CratePath})
			})
		}
	}

	for _, h := range v.HandPorts {
		h := h

		mount("port", modEntry{Module: "zz_generated_" + h.PortSnake, Alias: h.PortSnake})

		steps = append(steps, func() error {
			return add(path.Join("port", "zz_generated_"+h.PortSnake+".rs"), "hand_port", map[string]any{"Header": v.Header, "Port": h, "CratePath": v.CratePath})
		})

		for _, a := range h.Adapters {
			a := a

			mount("adapter", modEntry{Module: "zz_generated_" + a.Module, Alias: a.Module})

			steps = append(steps, func() error {
				return add(path.Join("adapter", "zz_generated_"+a.Module+".rs"), a.Template, map[string]any{"Header": v.Header, "Port": h, "Adapter": a, "CratePath": v.CratePath})
			})
		}
	}

	for _, c := range v.Controllers {
		c := c

		mount("controller", modEntry{
			Module: "zz_generated_" + c.Snake + "_controller",
			Exports: []string{
				c.Pascal + "Controller",
				c.Pascal + "ControllerError",
				c.Pascal + "ControllerImpl",
			},
		})
		userMods["controller"] = append(userMods["controller"], c.Snake+"_controller")

		steps = append(steps, func() error {
			return add(path.Join("controller", "zz_generated_"+c.Snake+"_controller.rs"), "controller", map[string]any{"Header": v.Header, "Controller": c, "CratePath": v.CratePath})
		})
	}

	return steps
}

func clientSteps(v view, add adder, mount mounter) []func() error {
	mount("adapter", modEntry{Module: "zz_generated_wire", Alias: "wire"})

	steps := []func() error{
		func() error { return add(path.Join("adapter", "zz_generated_wire.rs"), "wire", v) },
	}

	for _, c := range v.Clients {
		c := c

		mount("port", modEntry{Module: "zz_generated_" + c.PortModule, Alias: c.PortModule})
		mount("adapter", modEntry{Module: "zz_generated_" + c.Module, Alias: c.Module})

		steps = append(steps,
			func() error {
				return add(path.Join("port", "zz_generated_"+c.PortModule+".rs"), "client_port", map[string]any{"Header": v.Header, "Client": c, "CratePath": v.CratePath})
			},
			func() error {
				return add(path.Join("adapter", "zz_generated_"+c.Module+".rs"), "rest_client", map[string]any{"Header": v.Header, "Client": c, "CratePath": v.CratePath, "DefaultBaseURL": v.DefaultBaseURL})
			},
		)
	}

	return steps
}

func BuildManifest(v view) cellmanifest.Manifest {
	m := cellmanifest.Manifest{
		Version:   cellmanifest.Version,
		Cell:      v.Cell,
		Generator: Generator,
	}

	if v.Server {
		addServerToManifest(&m, v)
	}

	if v.Client {
		addClientToManifest(&m, v)
	}

	return m
}

func addServerToManifest(m *cellmanifest.Manifest, v view) {
	requires := make([]string, 0, len(v.Controllers))

	for _, c := range v.Controllers {
		ports := make([]string, 0, len(c.Ports))
		for _, p := range c.Ports {
			ports = append(ports, p.Port)
		}

		m.Provides.Controllers = append(m.Provides.Controllers, cellmanifest.Controller{
			Trait:  c.Pascal + "Controller",
			Impl:   c.Pascal + "ControllerImpl",
			Module: v.ModulePrefix + "controller",
			Ports:  ports,
		})

		requires = append(requires, c.Pascal+"Controller")
	}

	driverPorts := []string{}
	if v.Auth {
		driverPorts = append(driverPorts, crateports.TicketVerifierPort)
	}

	if len(v.Controllers) > 0 {
		m.Provides.Drivers = append(m.Provides.Drivers, cellmanifest.Driver{
			Name:     v.DriverName,
			Type:     "HttpDriver",
			Module:   v.ModulePrefix + "driver::http_driver",
			Requires: requires,
			Ports:    driverPorts,
			Config: map[string]cellmanifest.ConfigField{
				"addr": {
					Type:        cellmanifest.FieldTypeString,
					Default:     DefaultAddress,
					Description: "The host and port the http driver binds",
				},
			},
		})
	}

	if v.Auth {
		m.Requires.Ports = append(m.Requires.Ports, crateports.TicketVerifierPort)
	}

	for _, s := range v.Stores {
		m.Provides.Ports = append(m.Provides.Ports, cellmanifest.Port{
			Trait:  s.Port,
			Module: v.ModulePrefix + "port::" + s.PortSnake,
		})

		consumed := []string{}
		if s.Publishes != nil {
			consumed = append(consumed, s.Publishes.Port)
		}

		if s.HasSqlite {
			m.Provides.Adapters = append(m.Provides.Adapters, cellmanifest.Adapter{
				Name:       s.AdapterName,
				Type:       s.Struct,
				Module:     v.ModulePrefix + "adapter::" + s.Module,
				Implements: s.Port,
				Fallible:   true,
				Ports:      consumed,
				Config: map[string]cellmanifest.ConfigField{
					"path": {
						Type:        cellmanifest.FieldTypeString,
						Default:     DefaultStorePath,
						Description: "The sqlite file the " + s.Snake + " store opens",
					},
				},
			})
		}

		if s.HasMemory {
			m.Provides.Adapters = append(m.Provides.Adapters, cellmanifest.Adapter{
				Name:       s.MemoryAdapterName,
				Type:       s.MemoryStruct,
				Module:     v.ModulePrefix + "adapter::" + s.MemoryModule,
				Implements: s.Port,
				Fallible:   true,
				Ports:      consumed,
				Config: map[string]cellmanifest.ConfigField{
					"capacity": {
						Type:        cellmanifest.FieldTypeInteger,
						Default:     DefaultStoreCapacity,
						Description: "How many " + s.Snake + " rows the memory store holds before it refuses a new one",
					},
				},
			})
		}
	}

	for _, e := range v.Events {
		m.Provides.Ports = append(m.Provides.Ports, cellmanifest.Port{
			Trait:  e.Port,
			Module: v.ModulePrefix + "port::" + e.PortSnake,
		})

		if !e.HasMemory {
			m.Requires.Ports = append(m.Requires.Ports, e.Port)

			continue
		}

		m.Provides.Adapters = append(m.Provides.Adapters, cellmanifest.Adapter{
			Name:       e.MemoryAdapterName,
			Type:       e.MemoryStruct,
			Module:     v.ModulePrefix + "adapter::" + e.MemoryModule,
			Implements: e.Port,
			Config:     map[string]cellmanifest.ConfigField{},
		})
	}

	for _, h := range v.HandPorts {
		m.Provides.Ports = append(m.Provides.Ports, cellmanifest.Port{
			Trait:  h.Name,
			Module: v.ModulePrefix + "port::" + h.PortSnake,
		})

		if len(h.Adapters) == 0 {
			m.Requires.Ports = append(m.Requires.Ports, h.Name)

			continue
		}

		for _, a := range h.Adapters {
			m.Provides.Adapters = append(m.Provides.Adapters, cellmanifest.Adapter{
				Name:       a.AdapterName,
				Type:       a.Struct,
				Module:     v.ModulePrefix + "adapter::" + a.Module,
				Implements: h.Name,
				Config:     handAdapterConfig(h, a),
			})
		}
	}
}

func handAdapterConfig(h handPortView, a handAdapterView) map[string]cellmanifest.ConfigField {
	config := map[string]cellmanifest.ConfigField{}

	switch {
	case h.Kind == ClockPortKind && a.Kind == ClockAdapterMemory:
		config[h.InstantField] = cellmanifest.ConfigField{
			Type:        cellmanifest.FieldTypeInteger,
			Default:     0,
			Description: "The moment the " + h.Snake + " memory clock starts at, read as the " + h.Instant + " the port answers",
		}
	case h.Kind == VerifierPortKind && a.Kind == VerifierAdapterSecret:
		config["secret"] = cellmanifest.ConfigField{
			Type:        cellmanifest.FieldTypeString,
			Description: "The one string the " + h.Snake + " secret verifier accepts",
		}

		for _, field := range h.SubjectFields {
			config[field.Ident] = cellmanifest.ConfigField{
				Type:        cellmanifest.FieldTypeString,
				Description: "The " + field.Name + " of the " + h.Subject + " the " + h.Snake + " secret verifier answers on a match",
			}
		}
	}

	return config
}

func addClientToManifest(m *cellmanifest.Manifest, v view) {
	needsToken := false

	for _, c := range v.Clients {
		ports := []string{}
		if c.Auth {
			ports = append(ports, crateports.TokenSourcePort)
			needsToken = true
		}

		m.Provides.Ports = append(m.Provides.Ports, cellmanifest.Port{
			Trait:  c.Trait,
			Module: v.ModulePrefix + "port::" + c.PortModule,
		})

		m.Provides.Adapters = append(m.Provides.Adapters, cellmanifest.Adapter{
			Name:       c.AdapterName,
			Type:       c.Struct,
			Module:     v.ModulePrefix + "adapter::" + c.Module,
			Implements: c.Trait,
			Ports:      ports,
			Config: map[string]cellmanifest.ConfigField{
				"base_url": {
					Type:        cellmanifest.FieldTypeString,
					Default:     DefaultBaseURL,
					Description: "The base url the " + c.Snake + " rest client calls",
				},
			},
		})
	}

	if needsToken {
		m.Requires.Ports = append(m.Requires.Ports, crateports.TokenSourcePort)
	}
}

func render(name string, data any) (string, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", fmt.Errorf("rendering %s: %w", name, err)
	}

	return buf.String(), nil
}

var templates = template.Must(template.New("restrust").Parse(`
{{- define "cell_mod" -}}
{{ .Header }}
{{ range .Layers }}
pub mod {{ . }};
{{- end }}
{{ end -}}

{{- define "layer_mod" -}}
{{ .Header }}
{{- if .Allow }}
#![allow(clippy::disallowed_methods, clippy::disallowed_types)]
{{- end }}
{{ range .Entries }}
pub mod {{ .Module }};
{{- end }}
{{- range .UserMods }}

mod {{ . }};
{{- end }}
{{- range .Entries }}{{ if .Alias }}

pub use {{ .Module }} as {{ .Alias }};
{{- end }}{{ if .Exports }}

pub use {{ .Module }}::{{ "{" }}{{ range $i, $e := .Exports }}{{ if $i }}, {{ end }}{{ $e }}{{ end }}{{ "}" }};
{{- end }}{{ end }}
{{ end -}}

{{- define "type" -}}
{{ .Header }}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct {{ .Type.Name }} {
{{- range .Type.Fields }}
{{- if .Renamed }}
    #[serde(rename = "{{ .Name }}")]
{{- end }}
{{- if .Optional }}
    #[serde(default, skip_serializing_if = "Option::is_none")]
{{- end }}
    pub {{ .Ident }}: {{ .CoreType }},
{{- end }}
}
{{ end -}}

{{- define "port" -}}
{{ .Header }}

use {{ .CratePath }}types::{{ .Store.Snake }}::{{ .Store.Name }};

#[derive(Debug, thiserror::Error)]
pub enum {{ .Store.Port }}Error {
    #[error("putting {{ .Store.Snake }} {id:?}")]
    Put {
        id: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
    #[error("getting {{ .Store.Snake }} {id:?}")]
    Get {
        id: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
    #[error("looking {{ .Store.Snake }} up by {by} {value:?}")]
    Lookup {
        by: String,
        value: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
}

{{ if .Store.Lookups }}#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum {{ .Store.Name }}Column {
{{- range .Store.Lookups }}
    {{ .Variant }},
{{- end }}
}

impl {{ .Store.Name }}Column {
    pub fn property(&self) -> &'static str {
        match self {
{{- range .Store.Lookups }}
            Self::{{ .Variant }} => "{{ .By }}",
{{- end }}
        }
    }
}
{{ end }}
#[cfg_attr(test, mockall::automock)]
pub trait {{ .Store.Port }}: Send + Sync {
    fn put(&self, v: {{ .Store.Name }}) -> Result<(), {{ .Store.Port }}Error>;
    fn get(&self, {{ .Store.KeyIdent }}: &str) -> Result<Option<{{ .Store.Name }}>, {{ .Store.Port }}Error>;
{{- range .Store.Lookups }}
{{- if .Page }}
    fn {{ .Method }}(&self, {{ .Ident }}: &str, after: Option<String>, limit: Option<i64>) -> Result<Vec<{{ $.Store.Name }}>, {{ $.Store.Port }}Error>;
{{- else }}
    fn {{ .Method }}(&self, {{ .Ident }}: &str) -> Result<Option<{{ $.Store.Name }}>, {{ $.Store.Port }}Error>;
{{- end }}
{{- end }}
}
{{ end -}}

{{- define "subscribe_port" -}}
{{ .Header }}

use {{ .CratePath }}types::{{ .Event.Snake }}::{{ .Event.Name }};

#[derive(Debug, thiserror::Error)]
pub enum {{ .Event.Port }}Error {
    #[error("subscribing to {{ .Event.Snake }} events for {key:?}")]
    Subscribe {
        key: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
    #[error("publishing a {{ .Event.Snake }} event for {key:?}")]
    Publish {
        key: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ .Event.Port }}: Send + Sync {
    fn subscribe(&self, key: &str) -> Result<std::sync::mpsc::Receiver<{{ .Event.Name }}>, {{ .Event.Port }}Error>;
    fn publish(&self, key: &str, event: {{ .Event.Name }}) -> Result<(), {{ .Event.Port }}Error>;
}
{{ end -}}

{{- define "hand_port" -}}
{{ .Header }}
{{ $p := .Port }}
{{ range $p.Imports -}}
use {{ $.CratePath }}types::{{ .Snake }}::{{ .Name }};
{{ end }}
#[derive(Debug, thiserror::Error)]
pub enum {{ $p.Error }} {
    #[error("calling {method:?} on the {{ $p.Snake }} port: refused: {reason}")]
    Refused { method: String, reason: String },
    #[error("calling {method:?} on the {{ $p.Snake }} port")]
    Call {
        method: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ $p.Name }}: Send + Sync {
{{- range $p.Methods }}
    fn {{ .Ident }}(&self{{ if .Args }}, {{ .Args }}{{ end }}) -> Result<{{ .Return }}, {{ $p.Error }}>;
{{- end }}
}
{{ end -}}

{{- define "client_port" -}}
{{ .Header }}
{{ $c := .Client }}
{{ range $c.TypeImports -}}
use {{ $.CratePath }}types::{{ .Snake }}::{{ .Name }};
{{ end }}
#[derive(Debug, thiserror::Error)]
pub enum {{ $c.Error }} {
    #[error("{{ $c.WireRuntime.Display }}")]
    {{ $c.WireRuntime.Variant }} {
        operation: String,
        message: String,
        #[source]
        source: Option<Box<dyn std::error::Error + Send + Sync>>,
    },
{{- range $c.WireTaxonomy }}
    #[error("{{ .Display }}")]
    {{ .Variant }} { operation: String, message: String },
{{- end }}
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ $c.Trait }}: Send + Sync {
{{- range $c.Ops }}
    fn {{ .Ident }}(&self{{ if .ClientArgs }}, {{ .ClientArgs }}{{ end }}) -> Result<{{ .ClientReturn }}, {{ $c.Error }}>;
{{- end }}
}
{{ end -}}

{{- define "controller" -}}
{{ .Header }}
{{ $c := .Controller }}
use std::sync::Arc;

{{ range $c.Ports -}}
use {{ $.CratePath }}port::{{ .PortSnake }}::{{ "{" }}{{ .Port }}, {{ .Port }}Error{{ "}" }};
{{ end -}}
{{ if $c.Auth -}}
use crate::types::subject::Subject;
{{ end -}}
{{ range $c.TypeImports -}}
use {{ $.CratePath }}types::{{ .Snake }}::{{ .Name }};
{{ end }}
#[derive(Debug, thiserror::Error)]
pub enum {{ $c.Pascal }}ControllerError {
{{- range $c.Ports }}
    #[error("{{ .Reaching }} {id:?}")]
    {{ .Port }} {
        id: String,
        #[source]
        source: {{ .Port }}Error,
    },
{{- end }}
{{- range $c.Taxonomy }}
    #[error("{{ .Display }}")]
    {{ .Variant }} { {{ .FieldList }} },
{{- end }}
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ $c.Pascal }}Controller: Send + Sync {
{{- range $c.Ops }}
    fn {{ .Ident }}(&self{{ if .TraitArgs }}, {{ .TraitArgs }}{{ end }}) -> Result<{{ .ReturnType }}, {{ $c.Pascal }}ControllerError>;
{{- end }}
}

pub struct {{ $c.Pascal }}ControllerImpl {
{{- range $c.Ports }}
    pub(crate) {{ .PortSnake }}: Arc<dyn {{ .Port }} + Send + Sync>,
{{- end }}
}

impl {{ $c.Pascal }}ControllerImpl {
    pub fn new({{ range $i, $p := $c.Ports }}{{ if $i }}, {{ end }}{{ $p.PortSnake }}: Arc<dyn {{ $p.Port }} + Send + Sync>{{ end }}) -> Self {
        Self {{ "{" }}{{ range $i, $p := $c.Ports }}{{ if $i }},{{ end }} {{ $p.PortSnake }}{{ end }} {{ "}" }}
    }
}
{{ end -}}

{{- define "sqlite" -}}
{{ .Header }}
{{ $s := .Store }}
use std::sync::Mutex;
{{- if $s.Publishes }}
use std::sync::Arc;
{{- end }}

use rusqlite::OptionalExtension;

use {{ .CratePath }}port::{{ $s.PortSnake }}::{{ "{" }}{{ $s.Port }}, {{ $s.Port }}Error{{ if $s.Lookups }}, {{ $s.Name }}Column{{ end }}{{ "}" }};
use {{ .CratePath }}types::{{ $s.Snake }}::{{ $s.Name }};
{{- if $s.Publishes }}
use {{ .CratePath }}port::{{ $s.Publishes.PortSnake }}::{{ $s.Publishes.Port }};
use {{ .CratePath }}types::{{ $s.Publishes.Snake }}::{{ $s.Publishes.Name }};
{{- end }}

const SCHEMA: &str = "CREATE TABLE IF NOT EXISTS {{ $s.Snake }} ({{ $s.Key }} TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit (at TEXT NOT NULL, table_name TEXT NOT NULL, key TEXT NOT NULL, op TEXT NOT NULL, before TEXT, after TEXT);";

pub struct {{ $s.ConfigStruct }} {
    pub path: String,
}

#[derive(Debug, thiserror::Error)]
pub enum {{ $s.Name }}SqliteError {
    #[error("opening sqlite {path:?}")]
    Open {
        path: String,
        #[source]
        source: rusqlite::Error,
    },
    #[error("creating the schema in sqlite {path:?}")]
    Schema {
        path: String,
        #[source]
        source: rusqlite::Error,
    },
    #[error("locking the sqlite connection: poisoned")]
    Poisoned,
    #[error("running sql for {{ $s.Snake }} {id:?}")]
    Sql {
        id: String,
        #[source]
        source: rusqlite::Error,
    },
    #[error("encoding {{ $s.Snake }} {id:?}")]
    Json {
        id: String,
        #[source]
        source: serde_json::Error,
    },
}

pub struct {{ $s.Struct }} {
    connection: Mutex<rusqlite::Connection>,
{{- if $s.Publishes }}
    {{ $s.Publishes.PortSnake }}: Arc<dyn {{ $s.Publishes.Port }} + Send + Sync>,
{{- end }}
}

impl {{ $s.Struct }} {
    pub fn new(config: {{ $s.ConfigStruct }}{{ if $s.Publishes }}, {{ $s.Publishes.PortSnake }}: Arc<dyn {{ $s.Publishes.Port }} + Send + Sync>{{ end }}) -> Result<Self, {{ $s.Name }}SqliteError> {
        let path = config.path;
        let connection = rusqlite::Connection::open(&path).map_err(|source| {{ $s.Name }}SqliteError::Open {
            path: path.clone(),
            source,
        })?;
        connection
            .execute_batch(SCHEMA)
            .map_err(|source| {{ $s.Name }}SqliteError::Schema { path, source })?;
        Ok(Self {
            connection: Mutex::new(connection),
{{- if $s.Publishes }}
            {{ $s.Publishes.PortSnake }},
{{- end }}
        })
    }

{{- if $s.Lookups }}

    fn rows_where(&self, column: {{ $s.Name }}Column, value: &str, after: Option<&str>, limit: Option<i64>) -> Result<Vec<{{ $s.Name }}>, {{ $s.Name }}SqliteError> {
        let sql = |source| {{ $s.Name }}SqliteError::Sql {
            id: value.to_string(),
            source,
        };
        let connection = self.connection.lock().map_err(|_| {{ $s.Name }}SqliteError::Poisoned)?;
        let statement = format!(
            "SELECT body FROM {{ $s.Snake }} WHERE json_extract(body, '$.{}') = ?1 AND {{ $s.Key }} > ?2 ORDER BY {{ $s.Key }} LIMIT ?3",
            column.property()
        );
        let mut prepared = connection.prepare(&statement).map_err(sql)?;
        let bodies = prepared
            .query_map(
                rusqlite::params![value, after.unwrap_or(""), limit.unwrap_or(-1)],
                |row| row.get::<_, String>(0),
            )
            .map_err(sql)?
            .collect::<Result<Vec<String>, rusqlite::Error>>()
            .map_err(sql)?;

        bodies
            .iter()
            .map(|text| serde_json::from_str(text))
            .collect::<Result<Vec<{{ $s.Name }}>, serde_json::Error>>()
            .map_err(|source| {{ $s.Name }}SqliteError::Json {
                id: value.to_string(),
                source,
            })
    }
{{- end }}

    fn put_row(&self, v: &{{ $s.Name }}) -> Result<(), {{ $s.Name }}SqliteError> {
        let id = v.{{ $s.KeyIdent }}.clone();
        let sql = |source| {{ $s.Name }}SqliteError::Sql {
            id: id.clone(),
            source,
        };
        let after = serde_json::to_string(v).map_err(|source| {{ $s.Name }}SqliteError::Json {
            id: id.clone(),
            source,
        })?;
        let mut connection = self.connection.lock().map_err(|_| {{ $s.Name }}SqliteError::Poisoned)?;
        let tx = connection.transaction().map_err(sql)?;
        let before: Option<String> = tx
            .query_row("SELECT body FROM {{ $s.Snake }} WHERE {{ $s.Key }} = ?1", [&id], |row| row.get(0))
            .optional()
            .map_err(sql)?;
        tx.execute(
            "INSERT INTO {{ $s.Snake }} ({{ $s.Key }}, body) VALUES (?1, ?2) ON CONFLICT({{ $s.Key }}) DO UPDATE SET body = excluded.body",
            (&id, &after),
        )
        .map_err(sql)?;
        tx.execute(
            "INSERT INTO audit (at, table_name, key, op, before, after) VALUES (datetime('now'), '{{ $s.Snake }}', ?1, 'put', ?2, ?3)",
            (&id, &before, &after),
        )
        .map_err(sql)?;
        tx.commit().map_err(sql)?;
        Ok(())
    }

{{- if $s.HasOneLookup }}

    fn one_where(&self, column: {{ $s.Name }}Column, value: &str) -> Result<Option<{{ $s.Name }}>, {{ $s.Name }}SqliteError> {
        Ok(self.rows_where(column, value, None, Some(1))?.into_iter().next())
    }
{{- end }}

    fn get_row(&self, id: &str) -> Result<Option<{{ $s.Name }}>, {{ $s.Name }}SqliteError> {
        let connection = self.connection.lock().map_err(|_| {{ $s.Name }}SqliteError::Poisoned)?;
        let body: Option<String> = connection
            .query_row("SELECT body FROM {{ $s.Snake }} WHERE id = ?1", [id], |row| row.get(0))
            .optional()
            .map_err(|source| {{ $s.Name }}SqliteError::Sql {
                id: id.to_string(),
                source,
            })?;
        body.map(|text| serde_json::from_str(&text))
            .transpose()
            .map_err(|source| {{ $s.Name }}SqliteError::Json {
                id: id.to_string(),
                source,
            })
    }
}

impl {{ $s.Port }} for {{ $s.Struct }} {
    fn put(&self, v: {{ $s.Name }}) -> Result<(), {{ $s.Port }}Error> {
        let id = v.{{ $s.KeyIdent }}.clone();
        self.put_row(&v).map_err(|source| {{ $s.Port }}Error::Put {
            id: id.clone(),
            source: Box::new(source),
        })?;
{{- if $s.Publishes }}
        self.{{ $s.Publishes.PortSnake }}
            .publish(
                &id,
                {{ $s.Publishes.Name }} {
{{- range $s.Publishes.Assigns }}
                    {{ . }}
{{- end }}
                },
            )
            .map_err(|source| {{ $s.Port }}Error::Put {
                id,
                source: Box::new(source),
            })?;
{{- end }}
        Ok(())
    }

    fn get(&self, {{ $s.KeyIdent }}: &str) -> Result<Option<{{ $s.Name }}>, {{ $s.Port }}Error> {
        self.get_row({{ $s.KeyIdent }}).map_err(|source| {{ $s.Port }}Error::Get {
            id: {{ $s.KeyIdent }}.to_string(),
            source: Box::new(source),
        })
    }
{{- range $s.Lookups }}
{{- if .Page }}

    fn {{ .Method }}(&self, {{ .Ident }}: &str, after: Option<String>, limit: Option<i64>) -> Result<Vec<{{ $s.Name }}>, {{ $s.Port }}Error> {
        self.rows_where({{ $s.Name }}Column::{{ .Variant }}, {{ .Ident }}, after.as_deref(), limit)
            .map_err(|source| {{ $s.Port }}Error::Lookup {
                by: "{{ .By }}".to_string(),
                value: {{ .Ident }}.to_string(),
                source: Box::new(source),
            })
    }
{{- else }}

    fn {{ .Method }}(&self, {{ .Ident }}: &str) -> Result<Option<{{ $s.Name }}>, {{ $s.Port }}Error> {
        self.one_where({{ $s.Name }}Column::{{ .Variant }}, {{ .Ident }})
            .map_err(|source| {{ $s.Port }}Error::Lookup {
                by: "{{ .By }}".to_string(),
                value: {{ .Ident }}.to_string(),
                source: Box::new(source),
            })
    }
{{- end }}
{{- end }}
}
{{ end -}}

{{- define "memory_store" -}}
{{ .Header }}
{{ $s := .Store }}
use std::collections::BTreeMap;
use std::sync::{Mutex, MutexGuard};
{{- if $s.Publishes }}
use std::sync::Arc;
{{- end }}

use {{ .CratePath }}port::{{ $s.PortSnake }}::{{ "{" }}{{ $s.Port }}, {{ $s.Port }}Error{{ if $s.Lookups }}, {{ $s.Name }}Column{{ end }}{{ "}" }};
use {{ .CratePath }}types::{{ $s.Snake }}::{{ $s.Name }};
{{- if $s.Publishes }}
use {{ .CratePath }}port::{{ $s.Publishes.PortSnake }}::{{ $s.Publishes.Port }};
use {{ .CratePath }}types::{{ $s.Publishes.Snake }}::{{ $s.Publishes.Name }};
{{- end }}

pub struct {{ $s.MemoryConfigStruct }} {
    pub capacity: i64,
}

#[derive(Debug, thiserror::Error)]
pub enum {{ $s.Name }}MemoryError {
    #[error("sizing the {{ $s.Snake }} memory store: capacity {capacity} is below 1")]
    CapacityBelowOne { capacity: i64 },
    #[error("locking the {{ $s.Snake }} memory store: poisoned")]
    Poisoned,
    #[error("the {{ $s.Snake }} memory store holds its capacity of {capacity} rows and {{ $s.Key }} {key:?} is a new one")]
    Full { capacity: usize, key: String },
}

type Rows = BTreeMap<String, {{ $s.Name }}>;

pub struct {{ $s.MemoryStruct }} {
    capacity: usize,
    rows: Mutex<Rows>,
{{- if $s.Publishes }}
    {{ $s.Publishes.PortSnake }}: Arc<dyn {{ $s.Publishes.Port }} + Send + Sync>,
{{- end }}
}

impl {{ $s.MemoryStruct }} {
    pub fn new(config: {{ $s.MemoryConfigStruct }}{{ if $s.Publishes }}, {{ $s.Publishes.PortSnake }}: Arc<dyn {{ $s.Publishes.Port }} + Send + Sync>{{ end }}) -> Result<Self, {{ $s.Name }}MemoryError> {
        let capacity = usize::try_from(config.capacity)
            .ok()
            .filter(|capacity| *capacity >= 1)
            .ok_or({{ $s.Name }}MemoryError::CapacityBelowOne {
                capacity: config.capacity,
            })?;

        Ok(Self {
            capacity,
            rows: Mutex::new(BTreeMap::new()),
{{- if $s.Publishes }}
            {{ $s.Publishes.PortSnake }},
{{- end }}
        })
    }

    fn rows(&self) -> Result<MutexGuard<'_, Rows>, {{ $s.Name }}MemoryError> {
        self.rows.lock().map_err(|_| {{ $s.Name }}MemoryError::Poisoned)
    }

    fn put_row(&self, v: &{{ $s.Name }}) -> Result<(), {{ $s.Name }}MemoryError> {
        let mut rows = self.rows()?;
        let key = v.{{ $s.KeyIdent }}.clone();

        if rows.len() >= self.capacity && !rows.contains_key(&key) {
            return Err({{ $s.Name }}MemoryError::Full {
                capacity: self.capacity,
                key,
            });
        }

        rows.insert(key, v.clone());

        Ok(())
    }

{{- if $s.Lookups }}

    fn rows_where(&self, column: {{ $s.Name }}Column, value: &str, after: Option<&str>, limit: Option<i64>) -> Result<Vec<{{ $s.Name }}>, {{ $s.Name }}MemoryError> {
        let rows = self.rows()?;
        let taken = usize::try_from(limit.unwrap_or(-1)).unwrap_or(usize::MAX);

        Ok(rows
            .iter()
            .filter(|(key, _)| after.is_none_or(|cursor| key.as_str() > cursor))
            .map(|(_, row)| row)
            .filter(|row| field_of(row, column) == value)
            .take(taken)
            .cloned()
            .collect())
    }
{{- end }}
}
{{ if $s.Lookups }}
fn field_of(row: &{{ $s.Name }}, column: {{ $s.Name }}Column) -> String {
    match column {
{{- range $s.Lookups }}
        {{ $s.Name }}Column::{{ .Variant }} => row.{{ .Ident }}.clone(),
{{- end }}
    }
}
{{ end }}

impl {{ $s.Port }} for {{ $s.MemoryStruct }} {
    fn put(&self, v: {{ $s.Name }}) -> Result<(), {{ $s.Port }}Error> {
        let id = v.{{ $s.KeyIdent }}.clone();
        self.put_row(&v).map_err(|source| {{ $s.Port }}Error::Put {
            id: id.clone(),
            source: Box::new(source),
        })?;
{{- if $s.Publishes }}
        self.{{ $s.Publishes.PortSnake }}
            .publish(
                &id,
                {{ $s.Publishes.Name }} {
{{- range $s.Publishes.Assigns }}
                    {{ . }}
{{- end }}
                },
            )
            .map_err(|source| {{ $s.Port }}Error::Put {
                id,
                source: Box::new(source),
            })?;
{{- end }}
        Ok(())
    }

    fn get(&self, {{ $s.KeyIdent }}: &str) -> Result<Option<{{ $s.Name }}>, {{ $s.Port }}Error> {
        let rows = self.rows().map_err(|source| {{ $s.Port }}Error::Get {
            id: {{ $s.KeyIdent }}.to_string(),
            source: Box::new(source),
        })?;

        Ok(rows.get({{ $s.KeyIdent }}).cloned())
    }
{{- range $s.Lookups }}
{{- if .Page }}

    fn {{ .Method }}(&self, {{ .Ident }}: &str, after: Option<String>, limit: Option<i64>) -> Result<Vec<{{ $s.Name }}>, {{ $s.Port }}Error> {
        self.rows_where({{ $s.Name }}Column::{{ .Variant }}, {{ .Ident }}, after.as_deref(), limit)
            .map_err(|source| {{ $s.Port }}Error::Lookup {
                by: "{{ .By }}".to_string(),
                value: {{ .Ident }}.to_string(),
                source: Box::new(source),
            })
    }
{{- else }}

    fn {{ .Method }}(&self, {{ .Ident }}: &str) -> Result<Option<{{ $s.Name }}>, {{ $s.Port }}Error> {
        self.rows_where({{ $s.Name }}Column::{{ .Variant }}, {{ .Ident }}, None, Some(1))
            .map(|found| found.into_iter().next())
            .map_err(|source| {{ $s.Port }}Error::Lookup {
                by: "{{ .By }}".to_string(),
                value: {{ .Ident }}.to_string(),
                source: Box::new(source),
            })
    }
{{- end }}
{{- end }}
}
{{ end -}}

{{- define "clock_memory" -}}
{{ .Header }}
{{ $p := .Port }}{{ $a := .Adapter }}
use std::sync::atomic::{AtomicI64, Ordering};

use {{ .CratePath }}port::{{ $p.PortSnake }}::{{ "{" }}{{ $p.Name }}, {{ $p.Error }}{{ "}" }};
use {{ .CratePath }}types::{{ $p.InstantSnake }}::{{ $p.Instant }};
use {{ .CratePath }}types::{{ $p.SpanSnake }}::{{ $p.Span }};

const STEP: i64 = 1;

#[derive(Default)]
pub struct {{ $a.ConfigStruct }} {
    pub {{ $p.InstantField }}: i64,
}

pub struct {{ $a.Struct }} {
    {{ $p.InstantField }}: AtomicI64,
}

impl {{ $a.Struct }} {
    pub fn new(config: {{ $a.ConfigStruct }}) -> Self {
        Self {
            {{ $p.InstantField }}: AtomicI64::new(config.{{ $p.InstantField }}),
        }
    }
}

impl {{ $p.Name }} for {{ $a.Struct }} {
    fn now(&self) -> Result<{{ $p.Instant }}, {{ $p.Error }}> {
        Ok({{ $p.Instant }} {
            {{ $p.InstantField }}: self.{{ $p.InstantField }}.fetch_add(STEP, Ordering::Relaxed),
        })
    }

    fn elapsed(&self, request: {{ $p.Instant }}) -> Result<{{ $p.Span }}, {{ $p.Error }}> {
        let now = self.{{ $p.InstantField }}.load(Ordering::Relaxed);

        let {{ $p.SpanField }} = now
            .checked_sub(request.{{ $p.InstantField }})
            .filter(|{{ $p.SpanField }}| *{{ $p.SpanField }} >= 0)
            .ok_or_else(|| {{ $p.Error }}::Refused {
                method: "elapsed".to_string(),
                reason: format!("{} is not a moment this clock has reached", request.{{ $p.InstantField }}),
            })?;

        Ok({{ $p.Span }} { {{ $p.SpanField }} })
    }
}
{{ end -}}

{{- define "clock_system" -}}
{{ .Header }}
{{ $p := .Port }}{{ $a := .Adapter }}
use std::time::{SystemTime, UNIX_EPOCH};

use {{ .CratePath }}port::{{ $p.PortSnake }}::{{ "{" }}{{ $p.Name }}, {{ $p.Error }}{{ "}" }};
use {{ .CratePath }}types::{{ $p.InstantSnake }}::{{ $p.Instant }};
use {{ .CratePath }}types::{{ $p.SpanSnake }}::{{ $p.Span }};

#[derive(Default)]
pub struct {{ $a.ConfigStruct }} {}

#[derive(Default)]
pub struct {{ $a.Struct }} {}

impl {{ $a.Struct }} {
    pub fn new(_config: {{ $a.ConfigStruct }}) -> Self {
        Self {}
    }
}

impl {{ $p.Name }} for {{ $a.Struct }} {
    fn now(&self) -> Result<{{ $p.Instant }}, {{ $p.Error }}> {
        let since_epoch = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_err(|source| {{ $p.Error }}::Call {
                method: "now".to_string(),
                source: Box::new(source),
            })?;

        let {{ $p.InstantField }} = i64::try_from(since_epoch.as_millis()).map_err(|source| {{ $p.Error }}::Call {
            method: "now".to_string(),
            source: Box::new(source),
        })?;

        Ok({{ $p.Instant }} { {{ $p.InstantField }} })
    }

    fn elapsed(&self, request: {{ $p.Instant }}) -> Result<{{ $p.Span }}, {{ $p.Error }}> {
        let now = self.now()?;

        let {{ $p.SpanField }} = now
            .{{ $p.InstantField }}
            .checked_sub(request.{{ $p.InstantField }})
            .filter(|{{ $p.SpanField }}| *{{ $p.SpanField }} >= 0)
            .ok_or_else(|| {{ $p.Error }}::Refused {
                method: "elapsed".to_string(),
                reason: format!("{} is not a moment this clock has reached", request.{{ $p.InstantField }}),
            })?;

        Ok({{ $p.Span }} { {{ $p.SpanField }} })
    }
}
{{ end -}}

{{- define "verifier_secret" -}}
{{ .Header }}
{{ $p := .Port }}{{ $a := .Adapter }}
use {{ .CratePath }}port::{{ $p.PortSnake }}::{{ "{" }}{{ $p.Name }}, {{ $p.Error }}{{ "}" }};
use {{ .CratePath }}types::{{ $p.SubjectSnake }}::{{ $p.Subject }};

#[derive(Default)]
pub struct {{ $a.ConfigStruct }} {
    pub secret: String,
{{- range $p.SubjectFields }}
    pub {{ .Ident }}: String,
{{- end }}
}

pub struct {{ $a.Struct }} {
    secret: String,
    subject: {{ $p.Subject }},
}

impl {{ $a.Struct }} {
    pub fn new(config: {{ $a.ConfigStruct }}) -> Self {
        Self {
            secret: config.secret,
            subject: {{ $p.Subject }} {
{{- range $p.SubjectFields }}
                {{ .Ident }}: config.{{ .Ident }},
{{- end }}
            },
        }
    }
}

impl {{ $p.Name }} for {{ $a.Struct }} {
    fn verify(&self, offered: &str) -> Result<{{ $p.Subject }}, {{ $p.Error }}> {
        if offered != self.secret {
            return Err({{ $p.Error }}::Refused {
                method: "verify".to_string(),
                reason: "the offered string does not match the configured secret".to_string(),
            });
        }

        Ok(self.subject.clone())
    }
}
{{ end -}}

{{- define "memory_feed" -}}
{{ .Header }}
{{ $e := .Event }}
use std::collections::HashMap;
use std::sync::mpsc::{channel, Receiver, Sender};
use std::sync::{Mutex, MutexGuard};

use {{ .CratePath }}port::{{ $e.PortSnake }}::{{ "{" }}{{ $e.Port }}, {{ $e.Port }}Error{{ "}" }};
use {{ .CratePath }}types::{{ $e.Snake }}::{{ $e.Name }};

#[derive(Default)]
pub struct {{ $e.MemoryConfigStruct }} {}

#[derive(Debug, thiserror::Error)]
pub enum {{ $e.Name }}MemoryError {
    #[error("locking the {{ $e.Snake }} memory feed: poisoned")]
    Poisoned,
    #[error("opening the {{ $e.Snake }} memory feed: the key is empty")]
    EmptyKey,
}

type Listeners = HashMap<String, Vec<Sender<{{ $e.Name }}>>>;

pub struct {{ $e.MemoryStruct }} {
    listeners: Mutex<Listeners>,
}

impl {{ $e.MemoryStruct }} {
    pub fn new(config: {{ $e.MemoryConfigStruct }}) -> Self {
        let {{ $e.MemoryConfigStruct }} {} = config;

        Self {
            listeners: Mutex::new(HashMap::new()),
        }
    }

    fn listeners(&self) -> Result<MutexGuard<'_, Listeners>, {{ $e.Name }}MemoryError> {
        self.listeners
            .lock()
            .map_err(|_| {{ $e.Name }}MemoryError::Poisoned)
    }
}

impl {{ $e.Port }} for {{ $e.MemoryStruct }} {
    fn subscribe(&self, key: &str) -> Result<Receiver<{{ $e.Name }}>, {{ $e.Port }}Error> {
        let refuse = |source: {{ $e.Name }}MemoryError| {{ $e.Port }}Error::Subscribe {
            key: key.to_string(),
            source: Box::new(source),
        };

        if key.is_empty() {
            return Err(refuse({{ $e.Name }}MemoryError::EmptyKey));
        }

        let (sender, receiver) = channel();

        self.listeners()
            .map_err(refuse)?
            .entry(key.to_string())
            .or_default()
            .push(sender);

        Ok(receiver)
    }

    fn publish(&self, key: &str, event: {{ $e.Name }}) -> Result<(), {{ $e.Port }}Error> {
        let mut listeners = self
            .listeners()
            .map_err(|source| {{ $e.Port }}Error::Publish {
                key: key.to_string(),
                source: Box::new(source),
            })?;

        let Some(senders) = listeners.get_mut(key) else {
            return Ok(());
        };

        senders.retain(|sender| sender.send(event.clone()).is_ok());

        if senders.is_empty() {
            listeners.remove(key);
        }

        Ok(())
    }
}
{{ end -}}

{{- define "wire" -}}
{{ .Header }}
{{ $v := . }}
{{ range .Types -}}
use {{ $v.CratePath }}types::{{ .Snake }}::{{ .Name }};
{{ end }}
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RejectionWire {
    pub r#type: String,
    pub message: String,
}
{{- range .Types }}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct {{ .Name }}Wire {
{{- range .Fields }}
{{- if .Renamed }}
    #[serde(rename = "{{ .Name }}")]
{{- end }}
{{- if .Optional }}
    #[serde(default, skip_serializing_if = "Option::is_none")]
{{- end }}
    pub {{ .Ident }}: {{ .WireType }},
{{- end }}
}

impl From<{{ .Name }}Wire> for {{ .Name }} {
    fn from(w: {{ .Name }}Wire) -> Self {
        Self {
{{- range .Fields }}
            {{ .Ident }}: {{ .ToCore }},
{{- end }}
        }
    }
}

impl From<{{ .Name }}> for {{ .Name }}Wire {
    fn from(v: {{ .Name }}) -> Self {
        Self {
{{- range .Fields }}
            {{ .Ident }}: {{ .ToWire }},
{{- end }}
        }
    }
}
{{- end }}
{{ end -}}

{{- define "http_driver" -}}
{{ .Header }}
{{ $v := . }}
use std::sync::Arc;

{{ if .HasStream -}}
use axum::body::{Body, Bytes};
{{ end -}}
use axum::extract::{Json, {{ if .UsesPath }}Path, {{ end }}{{ if .UsesQuery }}Query, {{ end }}State};
{{ if .Auth -}}
use axum::http::HeaderMap;
{{ end -}}
use axum::http::StatusCode;
{{ if .HasStream -}}
use axum::http::{header, HeaderValue};
use axum::response::Response;
{{ end -}}
use axum::routing;
use axum::Router;

{{ range .Controllers -}}
use {{ $v.CratePath }}controller::{{ "{" }}{{ .Pascal }}Controller, {{ .Pascal }}ControllerError{{ "}" }};
{{ end -}}
{{ if .Auth -}}
use crate::port::ticket_verifier::{TicketVerifier, TicketVerifierError};
use crate::types::subject::Subject;
{{ end -}}
{{ range .Events -}}
use {{ $v.CratePath }}types::{{ .Snake }}::{{ .Name }};
{{ end -}}
use super::wire::RejectionWire;
{{- range .WireImports }}
use super::wire::{{ . }}Wire;
{{- end }}

type Rejection = (StatusCode, Json<RejectionWire>);

fn reject(status: StatusCode, kind: &str, message: String) -> Rejection {
    (
        status,
        Json(RejectionWire {
            r#type: kind.to_string(),
            message,
        }),
    )
}

{{- if .UsesQuery }}
type QueryMap = std::collections::HashMap<String, String>;

#[allow(dead_code)]
fn required_query(query: &QueryMap, name: &str, invalid: StatusCode) -> Result<String, Rejection> {
    query.get(name).cloned().ok_or_else(|| {
        reject(
            invalid,
            "validation",
            format!("validating {name:?}: the query parameter is required"),
        )
    })
}

#[allow(dead_code)]
fn required_integer(query: &QueryMap, name: &str, invalid: StatusCode) -> Result<i64, Rejection> {
    parse_integer(name, &required_query(query, name, invalid)?, invalid)
}

#[allow(dead_code)]
fn optional_integer(query: &QueryMap, name: &str, invalid: StatusCode) -> Result<Option<i64>, Rejection> {
    query
        .get(name)
        .map(|raw| parse_integer(name, raw, invalid))
        .transpose()
}

#[allow(dead_code)]
fn parse_integer(name: &str, raw: &str, invalid: StatusCode) -> Result<i64, Rejection> {
    raw.parse().map_err(|_| {
        reject(
            invalid,
            "validation",
            format!("validating {name:?}: {raw:?} is not an integer"),
        )
    })
}
{{ end }}
pub struct HttpDriverConfig {
    pub addr: String,
}

impl Default for HttpDriverConfig {
    fn default() -> Self {
        Self {
            addr: "{{ .DefaultAddress }}".to_string(),
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum HttpDriverError {
    #[error("binding the http driver to {address:?}")]
    Bind {
        address: String,
        #[source]
        source: std::io::Error,
    },
    #[error("reading the port the http driver bound on {address:?}")]
    Port {
        address: String,
        #[source]
        source: std::io::Error,
    },
    #[error("serving http on {address:?}")]
    Serve {
        address: String,
        #[source]
        source: std::io::Error,
    },
    #[error("using the http driver for {address:?}: it is not bound yet")]
    NotBound { address: String },
}

#[derive(Clone)]
pub struct HttpState {
{{- range .Controllers }}
    pub(crate) {{ .Snake }}_controller: Arc<dyn {{ .Pascal }}Controller + Send + Sync>,
{{- end }}
{{- if .Auth }}
    pub(crate) ticket_verifier: Arc<dyn TicketVerifier + Send + Sync>,
{{- end }}
}

pub struct HttpDriver {
    config: HttpDriverConfig,
    state: HttpState,
    listener: Option<tokio::net::TcpListener>,
}

impl HttpDriver {
    pub fn new(config: HttpDriverConfig{{ range .Controllers }}, {{ .Snake }}_controller: Arc<dyn {{ .Pascal }}Controller + Send + Sync>{{ end }}{{ if .Auth }}, ticket_verifier: Arc<dyn TicketVerifier + Send + Sync>{{ end }}) -> Self {
        Self {
            config,
            state: HttpState {{ "{" }}{{ range $i, $c := .Controllers }}{{ if $i }},{{ end }} {{ $c.Snake }}_controller{{ end }}{{ if .Auth }}, ticket_verifier{{ end }} {{ "}" }},
            listener: None,
        }
    }

    pub fn router(&self) -> Router {
        Router::new()
{{- range .Routes }}
            .route("{{ .Path }}", routing::{{ .MethodLower }}({{ .Ident }}))
{{- end }}
            .with_state(self.state.clone())
    }

    pub async fn bind(&mut self) -> Result<(), HttpDriverError> {
        let listener = tokio::net::TcpListener::bind(&self.config.addr)
            .await
            .map_err(|source| HttpDriverError::Bind {
                address: self.config.addr.clone(),
                source,
            })?;

        self.listener = Some(listener);

        Ok(())
    }

    pub fn local_port(&self) -> Result<u16, HttpDriverError> {
        let listener = self
            .listener
            .as_ref()
            .ok_or_else(|| HttpDriverError::NotBound {
                address: self.config.addr.clone(),
            })?;

        listener
            .local_addr()
            .map(|addr| addr.port())
            .map_err(|source| HttpDriverError::Port {
                address: self.config.addr.clone(),
                source,
            })
    }

    pub fn announce(&self) -> Result<(), HttpDriverError> {
        println!("LISTENING {}", self.local_port()?);

        Ok(())
    }

    pub async fn serve(self) -> Result<(), HttpDriverError> {
        let router = self.router();
        let address = self.config.addr.clone();

        let listener = self.listener.ok_or(HttpDriverError::NotBound {
            address: address.clone(),
        })?;

        axum::serve(listener, router)
            .await
            .map_err(|source| HttpDriverError::Serve { address, source })
    }
}
{{- if .Auth }}

fn authenticate(state: &HttpState, headers: &HeaderMap) -> Result<Subject, Rejection> {
    let token = bearer_token(headers).ok_or_else(|| {
        reject(
            StatusCode::UNAUTHORIZED,
            "authentication",
            "missing bearer token in the authorization header".to_string(),
        )
    })?;

    state.ticket_verifier.verify(token).map_err(|error| match error {
        TicketVerifierError::Refused { .. } => {
            reject(StatusCode::UNAUTHORIZED, "authentication", error.to_string())
        }
        TicketVerifierError::Verify { .. } => {
            eprintln!("{error:?}");
            reject(StatusCode::INTERNAL_SERVER_ERROR, "runtime", "internal error".to_string())
        }
    })
}

fn bearer_token(headers: &HeaderMap) -> Option<&str> {
    let value = headers.get(axum::http::header::AUTHORIZATION)?.to_str().ok()?;
    let (scheme, token) = value.trim().split_once(' ')?;

    if !scheme.eq_ignore_ascii_case("bearer") {
        return None;
    }

    let token = token.trim();

    if token.is_empty() {
        return None;
    }

    Some(token)
}
{{- end }}
{{- if .HasStream }}

const EVENT_STREAM_BUFFER: usize = 16;

const EVENT_STREAM_KEEP_ALIVE: std::time::Duration = std::time::Duration::from_secs(15);

fn event_frame<T, W>(events: &std::sync::mpsc::Receiver<T>) -> Option<Bytes>
where
    W: From<T> + serde::Serialize,
{
    match events.recv_timeout(EVENT_STREAM_KEEP_ALIVE) {
        Ok(event) => serde_json::to_string(&W::from(event))
            .ok()
            .map(|json| Bytes::from(format!("data: {json}\n\n"))),
        Err(std::sync::mpsc::RecvTimeoutError::Timeout) => Some(Bytes::from_static(b": keep-alive\n\n")),
        Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => None,
    }
}

fn event_stream<T, W>(events: std::sync::mpsc::Receiver<T>) -> Response
where
    T: Send + 'static,
    W: From<T> + serde::Serialize + 'static,
{
    let (mut sender, body) = http_body_util::channel::Channel::<Bytes>::new(EVENT_STREAM_BUFFER);
    let handle = tokio::runtime::Handle::current();

    tokio::task::spawn_blocking(move || {
        while let Some(frame) = event_frame::<T, W>(&events) {
            if handle.block_on(sender.send_data(frame)).is_err() {
                break;
            }
        }
    });

    let mut response = Response::new(Body::new(body));
    response
        .headers_mut()
        .insert(header::CONTENT_TYPE, HeaderValue::from_static("text/event-stream"));
    response
        .headers_mut()
        .insert(header::CACHE_CONTROL, HeaderValue::from_static("no-cache"));

    response
}
{{- end }}
{{ range .Controllers }}{{ $c := . }}
fn reject_{{ $c.Snake }}(error: {{ $c.Pascal }}ControllerError, invalid: StatusCode) -> Rejection {
    match error {
{{- range $c.Ports }}
        {{ $c.Pascal }}ControllerError::{{ .Port }} { .. } => {
            eprintln!("{error:?}");
            reject(StatusCode::INTERNAL_SERVER_ERROR, "runtime", "internal error".to_string())
        }
{{- end }}
{{- range $c.Taxonomy }}
        {{ $c.Pascal }}ControllerError::{{ .Variant }} { .. } => reject({{ .RestStatusExpr }}, "{{ .Wire }}", {{ .DetailExpr }}),
{{- end }}
    }
}
{{ end }}
{{- range .Routes }}
async fn {{ .Ident }}({{ .Extractors }}) -> {{ .HandlerReturn }} {
{{- if .Auth }}
    let subject = authenticate(&state, &headers)?;
{{- end }}
{{- range .QueryLines }}
    {{ . }}
{{- end }}
{{- if .Stream }}
    let events = state
        .{{ .ControllerSnake }}_controller
        .{{ .Ident }}({{ .ControllerCall }})
        .map_err(|error| reject_{{ .ControllerSnake }}(error, {{ .InvalidStatusExpr }}))?;
{{- else if .Response }}
    let out = state
        .{{ .ControllerSnake }}_controller
        .{{ .Ident }}({{ .ControllerCall }})
        .map_err(|error| reject_{{ .ControllerSnake }}(error, {{ .InvalidStatusExpr }}))?;
{{- else }}
    state
        .{{ .ControllerSnake }}_controller
        .{{ .Ident }}({{ .ControllerCall }})
        .map_err(|error| reject_{{ .ControllerSnake }}(error, {{ .InvalidStatusExpr }}))?;
{{- end }}
    Ok({{ .OkExpr }})
}
{{ end -}}
{{ end -}}

{{- define "rest_client" -}}
{{ .Header }}
{{ $c := .Client }}
{{ if $c.Auth -}}
use std::sync::Arc;

{{ end -}}
use serde::de::DeserializeOwned;

{{ if $c.Auth -}}
use crate::port::token_source::TokenSource;
{{ end -}}
use {{ .CratePath }}port::{{ $c.PortModule }}::{{ "{" }}{{ $c.Trait }}, {{ $c.Error }}{{ "}" }};
{{ range $c.TypeImports -}}
use {{ $.CratePath }}types::{{ .Snake }}::{{ .Name }};
{{ end -}}
use super::wire::RejectionWire;
{{- range $c.TypeImports }}
use super::wire::{{ .Name }}Wire;
{{- end }}

pub struct {{ $c.Config }} {
    pub base_url: String,
}

impl Default for {{ $c.Config }} {
    fn default() -> Self {
        Self {
            base_url: "{{ .DefaultBaseURL }}".to_string(),
        }
    }
}

pub struct {{ $c.Struct }} {
    base_url: String,
    client: reqwest::Client,
{{- if $c.Auth }}
    token_source: Arc<dyn TokenSource + Send + Sync>,
{{- end }}
}

impl {{ $c.Struct }} {
    pub fn new(config: {{ $c.Config }}{{ if $c.Auth }}, token_source: Arc<dyn TokenSource + Send + Sync>{{ end }}) -> Self {
        Self {
            base_url: config.base_url.trim_end_matches('/').to_string(),
            client: reqwest::Client::new(),
{{- if $c.Auth }}
            token_source,
{{- end }}
        }
    }
{{- if $c.Auth }}

    fn bearer(&self, operation: &str) -> Result<String, {{ $c.Error }}> {
        self.token_source
            .token()
            .map_err(|source| {{ $c.Error }}::Authentication {
                operation: operation.to_string(),
                message: source.to_string(),
            })
    }
{{- end }}

    fn block<T>(&self, future: impl std::future::Future<Output = T>) -> T {
        tokio::task::block_in_place(|| tokio::runtime::Handle::current().block_on(future))
    }
}

{{- if $c.HasQuery }}
fn encode_query(value: &str) -> String {
    let mut out = String::with_capacity(value.len());

    for byte in value.as_bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(char::from(*byte))
            }
            other => out.push_str(&format!("%{other:02X}")),
        }
    }

    out
}

fn with_query(url: String, pairs: Vec<(&str, String)>) -> String {
    if pairs.is_empty() {
        return url;
    }

    let query = pairs
        .iter()
        .map(|(name, value)| format!("{}={}", encode_query(name), encode_query(value)))
        .collect::<Vec<String>>()
        .join("&");

    format!("{url}?{query}")
}

{{ end -}}
async fn send(operation: &str, request: reqwest::RequestBuilder) -> Result<reqwest::Response, {{ $c.Error }}> {
    let response = request
        .send()
        .await
        .map_err(|source| transport(operation, source))?;

    if response.status().is_success() {
        return Ok(response);
    }

    Err(rejection(operation, response).await)
}

#[allow(dead_code)]
async fn answer<W: DeserializeOwned>(operation: &str, request: reqwest::RequestBuilder) -> Result<W, {{ $c.Error }}> {
    send(operation, request)
        .await?
        .json::<W>()
        .await
        .map_err(|source| transport(operation, source))
}

#[allow(dead_code)]
async fn accept(operation: &str, request: reqwest::RequestBuilder) -> Result<(), {{ $c.Error }}> {
    send(operation, request).await.map(|_response| ())
}

fn transport(operation: &str, source: reqwest::Error) -> {{ $c.Error }} {
    {{ $c.Error }}::Runtime {
        operation: operation.to_string(),
        message: "transport failure".to_string(),
        source: Some(Box::new(source)),
    }
}

async fn rejection(operation: &str, response: reqwest::Response) -> {{ $c.Error }} {
    let status = response.status();
    let text = response.text().await.unwrap_or_default();
    let operation = operation.to_string();

    let Ok(wire) = serde_json::from_str::<RejectionWire>(&text) else {
        return {{ $c.Error }}::Runtime {
            operation,
            message: format!("{status}: {text}"),
            source: None,
        };
    };

    match wire.r#type.as_str() {
{{- range $c.WireTaxonomy }}
        "{{ .Type }}" => {{ $c.Error }}::{{ .Variant }} { operation, message: wire.message },
{{- end }}
        "{{ $c.WireRuntime.Type }}" => {{ $c.Error }}::{{ $c.WireRuntime.Variant }} {
            operation,
            message: wire.message,
            source: None,
        },
        other => {{ $c.Error }}::Runtime {
            operation,
            message: format!("{status}: unknown error type {other:?}: {}", wire.message),
            source: None,
        },
    }
}
{{- if $c.HasStream }}

async fn stream_events<W, T>(operation: &str, request: reqwest::RequestBuilder) -> Result<std::sync::mpsc::Receiver<T>, {{ $c.Error }}>
where
    W: DeserializeOwned + Send + 'static,
    T: From<W> + Send + 'static,
{
    let response = send(operation, request).await?;
    let (sender, receiver) = std::sync::mpsc::channel();

    tokio::spawn(forward_events::<W, T>(response, sender));

    Ok(receiver)
}

async fn forward_events<W, T>(mut response: reqwest::Response, sender: std::sync::mpsc::Sender<T>)
where
    W: DeserializeOwned + Send + 'static,
    T: From<W> + Send + 'static,
{
    let mut buffer: Vec<u8> = Vec::new();

    loop {
        let chunk = match response.chunk().await {
            Ok(Some(chunk)) => chunk,
            Ok(None) => return,
            Err(error) => {
                eprintln!("reading the event stream: {}", error_chain(&error));
                return;
            }
        };

        buffer.extend_from_slice(&chunk);

        while let Some(end) = frame_end(&buffer) {
            let frame: Vec<u8> = buffer.drain(..end + 2).collect();

            for event in parse_frame::<W>(&frame) {
                if sender.send(T::from(event)).is_err() {
                    return;
                }
            }
        }
    }
}

fn error_chain(error: &dyn std::error::Error) -> String {
    let mut parts = vec![error.to_string()];
    let mut source = error.source();

    while let Some(current) = source {
        parts.push(current.to_string());
        source = current.source();
    }

    parts.join(": ")
}

fn frame_end(buffer: &[u8]) -> Option<usize> {
    buffer.windows(2).position(|pair| pair == b"\n\n")
}

fn parse_frame<W: DeserializeOwned>(frame: &[u8]) -> Vec<W> {
    String::from_utf8_lossy(frame)
        .lines()
        .filter_map(|line| line.strip_prefix("data:"))
        .filter_map(|data| serde_json::from_str::<W>(data.trim_start()).ok())
        .collect()
}
{{- end }}

impl {{ $c.Trait }} for {{ $c.Struct }} {
{{- range $c.Ops }}
    fn {{ .Ident }}(&self{{ if .ClientArgs }}, {{ .ClientArgs }}{{ end }}) -> Result<{{ .ClientReturn }}, {{ $c.Error }}> {
        let operation = "{{ .ID }}";
{{- range .ClientQueryLines }}
        {{ . }}
{{- end }}
        let request = self
            .client
            .request(reqwest::Method::{{ .Method }}, {{ .URLExpr }}){{ if .Body }}
            .json(&{{ .Body }}Wire::from(body)){{ end }}{{ if .Stream }}
            .header("accept", "text/event-stream"){{ end }};
{{- if .Auth }}
        let request = request.bearer_auth(self.bearer(operation)?);
{{- end }}
{{- if .Stream }}

        self.block(stream_events::<{{ .Response }}Wire, {{ .Response }}>(operation, request))
{{- else if .Response }}

        self.block(answer::<{{ .Response }}Wire>(operation, request)).map({{ .Response }}::from)
{{- else }}

        self.block(accept(operation, request))
{{- end }}
    }
{{- end }}
}
{{ end -}}
`))
