// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package restrust

import (
	"bytes"
	"fmt"
	"path"
	"sort"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/pkg/cellmanifest"
	"github.com/alexandremahdhaoui/forge-dev-codegen/pkg/rustname"
)

const header = "// Code generated by rest-rust (forge-dev-codegen). DO NOT EDIT."

const Generator = "rest-rust (forge-dev-codegen)"

const DefaultCell = "rest"

const DefaultAddress = "127.0.0.1:0"

const DefaultStorePath = ":memory:"

const DefaultBaseURL = "http://127.0.0.1:8080"

const (
	SideServer = "server"
	SideClient = "client"
	SideBoth   = "both"
)

const TicketVerifierPort = "TicketVerifier"

const TokenSourcePort = "TokenSource"

var Layers = []string{"adapter", "controller", "driver", "port", "types"}

var allowingLayers = map[string]bool{"adapter": true, "driver": true}

type Options struct {
	Service   string
	Cell      string
	Side      string
	Header    string
	Generator string
}

type File struct {
	Path    string
	Content string
}

type modEntry struct {
	Module  string
	Alias   string
	Exports []string
}

type layerMod struct {
	Header   string
	Allow    bool
	Entries  []modEntry
	UserMods []string
}

func checkSide(side string) error {
	switch side {
	case SideServer, SideClient, SideBoth:
		return nil
	default:
		return fmt.Errorf("emitting the rest cell: side %q is not one of %s, %s and %s", side, SideServer, SideClient, SideBoth)
	}
}

func Generate(doc []byte, opts Options) ([]File, error) {
	if opts.Service == "" {
		return nil, fmt.Errorf("emitting the rest cell: the service name is required")
	}

	if err := checkName("service", opts.Service); err != nil {
		return nil, fmt.Errorf("emitting the rest cell: %w", err)
	}

	if opts.Cell == "" {
		opts.Cell = DefaultCell
	}

	if !rustname.IsModuleName(opts.Cell) {
		return nil, fmt.Errorf("emitting the rest cell: cell %q is not a name Rust can spell as a module, use lowercase letters, digits and underscores and start with a letter", opts.Cell)
	}

	if opts.Side == "" {
		opts.Side = SideServer
	}

	if err := checkSide(opts.Side); err != nil {
		return nil, err
	}

	spec, err := Parse(doc)
	if err != nil {
		return nil, err
	}

	v := buildView(spec, opts)

	if opts.Header != "" {
		v.Header = opts.Header
	}

	files := []File{}

	add := func(p, name string, data any) error {
		content, err := render(name, data)
		if err != nil {
			return err
		}

		files = append(files, File{Path: p, Content: content})

		return nil
	}

	entries := map[string][]modEntry{}
	userMods := map[string][]string{}

	mount := func(layer string, entry modEntry) {
		entries[layer] = append(entries[layer], entry)
	}

	steps := []func() error{}

	for _, t := range v.Types {
		t := t

		mount("types", modEntry{Module: "zz_generated_" + t.Snake, Alias: t.Snake})

		steps = append(steps, func() error {
			return add(path.Join("types", "zz_generated_"+t.Snake+".rs"), "type", map[string]any{"Header": v.Header, "Type": t})
		})
	}

	if v.Server {
		steps = append(steps, serverSteps(v, add, mount, userMods)...)
	}

	if v.Client {
		steps = append(steps, clientSteps(v, add, mount)...)
	}

	for _, layer := range Layers {
		layer := layer

		mod := layerMod{
			Header:   v.Header,
			Allow:    allowingLayers[layer],
			Entries:  entries[layer],
			UserMods: userMods[layer],
		}
		sort.Slice(mod.Entries, func(i, j int) bool { return mod.Entries[i].Module < mod.Entries[j].Module })
		sort.Strings(mod.UserMods)

		steps = append(steps, func() error {
			return add(path.Join(layer, "mod.rs"), "layer_mod", mod)
		})
	}

	steps = append(steps, func() error {
		return add("mod.rs", "cell_mod", map[string]any{"Header": v.Header, "Layers": Layers})
	})

	for _, step := range steps {
		if err := step(); err != nil {
			return nil, err
		}
	}

	manifest := BuildManifest(v)
	if opts.Generator != "" {
		manifest.Generator = opts.Generator
	}

	body, err := cellmanifest.Marshal(manifest)
	if err != nil {
		return nil, fmt.Errorf("emitting the rest cell: %w", err)
	}

	files = append(files, File{Path: cellmanifest.FileName, Content: string(body)})

	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })

	return files, nil
}

type adder func(p, name string, data any) error

type mounter func(layer string, entry modEntry)

func serverSteps(v view, add adder, mount mounter, userMods map[string][]string) []func() error {
	mount("driver", modEntry{Module: "zz_generated_wire", Alias: "wire"})
	mount("driver", modEntry{Module: "zz_generated_http_driver", Alias: "http_driver"})

	steps := []func() error{
		func() error { return add(path.Join("driver", "zz_generated_wire.rs"), "wire", v) },
		func() error {
			return add(path.Join("driver", "zz_generated_http_driver.rs"), "http_driver", v)
		},
	}

	if v.Auth {
		mount("types", modEntry{Module: "zz_generated_subject", Alias: "subject"})
		mount("port", modEntry{Module: "zz_generated_ticket_verifier", Alias: "ticket_verifier"})

		steps = append(steps,
			func() error {
				return add(path.Join("types", "zz_generated_subject.rs"), "subject", map[string]any{"Header": v.Header})
			},
			func() error {
				return add(path.Join("port", "zz_generated_ticket_verifier.rs"), "ticket_verifier_port", map[string]any{"Header": v.Header, "CratePath": v.CratePath})
			},
		)
	}

	for _, s := range v.Stores {
		s := s

		mount("port", modEntry{Module: "zz_generated_" + s.PortSnake, Alias: s.PortSnake})
		mount("adapter", modEntry{Module: "zz_generated_" + s.Module, Alias: s.Module})

		steps = append(steps,
			func() error {
				return add(path.Join("port", "zz_generated_"+s.PortSnake+".rs"), "port", map[string]any{"Header": v.Header, "Store": s, "CratePath": v.CratePath})
			},
			func() error {
				return add(path.Join("adapter", "zz_generated_"+s.Module+".rs"), "sqlite", map[string]any{"Header": v.Header, "Store": s, "CratePath": v.CratePath})
			},
		)
	}

	for _, e := range v.Events {
		e := e

		mount("port", modEntry{Module: "zz_generated_" + e.PortSnake, Alias: e.PortSnake})

		steps = append(steps, func() error {
			return add(path.Join("port", "zz_generated_"+e.PortSnake+".rs"), "subscribe_port", map[string]any{"Header": v.Header, "Event": e, "CratePath": v.CratePath})
		})
	}

	for _, c := range v.Controllers {
		c := c

		mount("controller", modEntry{
			Module: "zz_generated_" + c.Snake + "_controller",
			Exports: []string{
				c.Pascal + "Controller",
				c.Pascal + "ControllerError",
				c.Pascal + "ControllerImpl",
			},
		})
		userMods["controller"] = append(userMods["controller"], c.Snake+"_controller")

		steps = append(steps, func() error {
			return add(path.Join("controller", "zz_generated_"+c.Snake+"_controller.rs"), "controller", map[string]any{"Header": v.Header, "Controller": c, "CratePath": v.CratePath})
		})
	}

	return steps
}

func clientSteps(v view, add adder, mount mounter) []func() error {
	mount("adapter", modEntry{Module: "zz_generated_wire", Alias: "wire"})
	mount("port", modEntry{Module: "zz_generated_token_source", Alias: "token_source"})

	steps := []func() error{
		func() error { return add(path.Join("adapter", "zz_generated_wire.rs"), "wire", v) },
		func() error {
			return add(path.Join("port", "zz_generated_token_source.rs"), "token_source_port", map[string]any{"Header": v.Header})
		},
	}

	for _, c := range v.Clients {
		c := c

		mount("port", modEntry{Module: "zz_generated_" + c.PortModule, Alias: c.PortModule})
		mount("adapter", modEntry{Module: "zz_generated_" + c.Module, Alias: c.Module})

		steps = append(steps,
			func() error {
				return add(path.Join("port", "zz_generated_"+c.PortModule+".rs"), "client_port", map[string]any{"Header": v.Header, "Client": c, "CratePath": v.CratePath})
			},
			func() error {
				return add(path.Join("adapter", "zz_generated_"+c.Module+".rs"), "rest_client", map[string]any{"Header": v.Header, "Client": c, "CratePath": v.CratePath, "DefaultBaseURL": v.DefaultBaseURL})
			},
		)
	}

	return steps
}

func BuildManifest(v view) cellmanifest.Manifest {
	m := cellmanifest.Manifest{
		Version:   cellmanifest.Version,
		Cell:      v.Cell,
		Generator: Generator,
	}

	if v.Server {
		addServerToManifest(&m, v)
	}

	if v.Client {
		addClientToManifest(&m, v)
	}

	return m
}

func addServerToManifest(m *cellmanifest.Manifest, v view) {
	requires := make([]string, 0, len(v.Controllers))

	for _, c := range v.Controllers {
		ports := make([]string, 0, len(c.Ports))
		for _, p := range c.Ports {
			ports = append(ports, p.Port)
		}

		m.Provides.Controllers = append(m.Provides.Controllers, cellmanifest.Controller{
			Trait:  c.Pascal + "Controller",
			Impl:   c.Pascal + "ControllerImpl",
			Module: v.ModulePrefix + "controller",
			Ports:  ports,
		})

		requires = append(requires, c.Pascal+"Controller")
	}

	driverPorts := []string{}
	if v.Auth {
		driverPorts = append(driverPorts, TicketVerifierPort)
	}

	if len(v.Controllers) > 0 {
		m.Provides.Drivers = append(m.Provides.Drivers, cellmanifest.Driver{
			Name:     v.DriverName,
			Type:     "HttpDriver",
			Module:   v.ModulePrefix + "driver::http_driver",
			Requires: requires,
			Ports:    driverPorts,
			Config: map[string]cellmanifest.ConfigField{
				"addr": {
					Type:        cellmanifest.FieldTypeString,
					Default:     DefaultAddress,
					Description: "The host and port the http driver binds",
				},
			},
		})
	}

	if v.Auth {
		m.Provides.Ports = append(m.Provides.Ports, cellmanifest.Port{
			Trait:  TicketVerifierPort,
			Module: v.ModulePrefix + "port::ticket_verifier",
		})
		m.Requires.Ports = append(m.Requires.Ports, TicketVerifierPort)
	}

	for _, s := range v.Stores {
		m.Provides.Ports = append(m.Provides.Ports, cellmanifest.Port{
			Trait:  s.Port,
			Module: v.ModulePrefix + "port::" + s.PortSnake,
		})

		m.Provides.Adapters = append(m.Provides.Adapters, cellmanifest.Adapter{
			Name:       s.AdapterName,
			Type:       s.Struct,
			Module:     v.ModulePrefix + "adapter::" + s.Module,
			Implements: s.Port,
			Fallible:   true,
			Config: map[string]cellmanifest.ConfigField{
				"path": {
					Type:        cellmanifest.FieldTypeString,
					Default:     DefaultStorePath,
					Description: "The sqlite file the " + s.Snake + " store opens",
				},
			},
		})
	}

	for _, e := range v.Events {
		m.Provides.Ports = append(m.Provides.Ports, cellmanifest.Port{
			Trait:  e.Port,
			Module: v.ModulePrefix + "port::" + e.PortSnake,
		})
		m.Requires.Ports = append(m.Requires.Ports, e.Port)
	}
}

func addClientToManifest(m *cellmanifest.Manifest, v view) {
	m.Provides.Ports = append(m.Provides.Ports, cellmanifest.Port{
		Trait:  TokenSourcePort,
		Module: v.ModulePrefix + "port::token_source",
	})

	for _, c := range v.Clients {
		m.Provides.Ports = append(m.Provides.Ports, cellmanifest.Port{
			Trait:  c.Trait,
			Module: v.ModulePrefix + "port::" + c.PortModule,
		})

		m.Provides.Adapters = append(m.Provides.Adapters, cellmanifest.Adapter{
			Name:       c.AdapterName,
			Type:       c.Struct,
			Module:     v.ModulePrefix + "adapter::" + c.Module,
			Implements: c.Trait,
			Ports:      []string{TokenSourcePort},
			Config: map[string]cellmanifest.ConfigField{
				"base_url": {
					Type:        cellmanifest.FieldTypeString,
					Default:     DefaultBaseURL,
					Description: "The base url the " + c.Snake + " rest client calls",
				},
			},
		})
	}
}

func render(name string, data any) (string, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", fmt.Errorf("rendering %s: %w", name, err)
	}

	return buf.String(), nil
}

var templates = template.Must(template.New("restrust").Parse(`
{{- define "cell_mod" -}}
{{ .Header }}
{{ range .Layers }}
pub mod {{ . }};
{{- end }}
{{ end -}}

{{- define "layer_mod" -}}
{{ .Header }}
{{- if .Allow }}
#![allow(clippy::disallowed_methods, clippy::disallowed_types)]
{{- end }}
{{ range .Entries }}
pub mod {{ .Module }};
{{- end }}
{{- range .UserMods }}

mod {{ . }};
{{- end }}
{{- range .Entries }}{{ if .Alias }}

pub use {{ .Module }} as {{ .Alias }};
{{- end }}{{ if .Exports }}

pub use {{ .Module }}::{{ "{" }}{{ range $i, $e := .Exports }}{{ if $i }}, {{ end }}{{ $e }}{{ end }}{{ "}" }};
{{- end }}{{ end }}
{{ end -}}

{{- define "type" -}}
{{ .Header }}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct {{ .Type.Name }} {
{{- range .Type.Fields }}
{{- if .Renamed }}
    #[serde(rename = "{{ .Name }}")]
{{- end }}
{{- if .Optional }}
    #[serde(default, skip_serializing_if = "Option::is_none")]
{{- end }}
    pub {{ .Ident }}: {{ .CoreType }},
{{- end }}
}
{{ end -}}

{{- define "subject" -}}
{{ .Header }}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Subject {
    pub id: String,
}
{{ end -}}

{{- define "port" -}}
{{ .Header }}

use {{ .CratePath }}types::{{ .Store.Snake }}::{{ .Store.Name }};

#[derive(Debug, thiserror::Error)]
pub enum {{ .Store.Port }}Error {
    #[error("putting {{ .Store.Snake }} {id:?}")]
    Put {
        id: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
    #[error("getting {{ .Store.Snake }} {id:?}")]
    Get {
        id: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ .Store.Port }}: Send + Sync {
    fn put(&self, v: {{ .Store.Name }}) -> Result<(), {{ .Store.Port }}Error>;
    fn get(&self, id: &str) -> Result<Option<{{ .Store.Name }}>, {{ .Store.Port }}Error>;
}
{{ end -}}

{{- define "subscribe_port" -}}
{{ .Header }}

use {{ .CratePath }}types::{{ .Event.Snake }}::{{ .Event.Name }};

#[derive(Debug, thiserror::Error)]
pub enum {{ .Event.Port }}Error {
    #[error("subscribing to {{ .Event.Snake }} events for {key:?}")]
    Subscribe {
        key: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ .Event.Port }}: Send + Sync {
    fn subscribe(&self, key: &str) -> Result<std::sync::mpsc::Receiver<{{ .Event.Name }}>, {{ .Event.Port }}Error>;
}
{{ end -}}

{{- define "ticket_verifier_port" -}}
{{ .Header }}

use {{ .CratePath }}types::subject::Subject;

#[derive(Debug, thiserror::Error)]
pub enum TicketVerifierError {
    #[error("verifying the ticket: refused: {reason}")]
    Refused { reason: String },
    #[error("verifying the ticket")]
    Verify {
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
}

#[cfg_attr(test, mockall::automock)]
pub trait TicketVerifier: Send + Sync {
    fn verify(&self, token: &str) -> Result<Subject, TicketVerifierError>;
}
{{ end -}}

{{- define "token_source_port" -}}
{{ .Header }}

#[derive(Debug, thiserror::Error)]
pub enum TokenSourceError {
    #[error("reading the current token: {reason}")]
    Unavailable { reason: String },
}

#[cfg_attr(test, mockall::automock)]
pub trait TokenSource: Send + Sync {
    fn token(&self) -> Result<String, TokenSourceError>;
}
{{ end -}}

{{- define "client_port" -}}
{{ .Header }}
{{ $c := .Client }}
{{ range $c.TypeImports -}}
use {{ $.CratePath }}types::{{ .Snake }}::{{ .Name }};
{{ end }}
#[derive(Debug, thiserror::Error)]
pub enum {{ $c.Error }} {
    #[error("calling {operation:?}: {message}")]
    Runtime {
        operation: String,
        message: String,
        #[source]
        source: Option<Box<dyn std::error::Error + Send + Sync>>,
    },
    #[error("calling {operation:?}: authentication refused: {message}")]
    Authentication { operation: String, message: String },
    #[error("calling {operation:?}: authorization refused: {message}")]
    Authorization { operation: String, message: String },
    #[error("calling {operation:?}: validation failed: {message}")]
    Validation { operation: String, message: String },
    #[error("calling {operation:?}: {message}")]
    Semantic { operation: String, message: String },
    #[error("calling {operation:?}: rate limited: {message}")]
    RateLimiting { operation: String, message: String },
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ $c.Trait }}: Send + Sync {
{{- range $c.Ops }}
    fn {{ .Ident }}(&self{{ if .ClientArgs }}, {{ .ClientArgs }}{{ end }}) -> Result<{{ .ClientReturn }}, {{ $c.Error }}>;
{{- end }}
}
{{ end -}}

{{- define "controller" -}}
{{ .Header }}
{{ $c := .Controller }}
use std::sync::Arc;

{{ range $c.Ports -}}
use {{ $.CratePath }}port::{{ .PortSnake }}::{{ "{" }}{{ .Port }}, {{ .Port }}Error{{ "}" }};
{{ end -}}
{{ if $c.Auth -}}
use {{ $.CratePath }}types::subject::Subject;
{{ end -}}
{{ range $c.TypeImports -}}
use {{ $.CratePath }}types::{{ .Snake }}::{{ .Name }};
{{ end }}
#[derive(Debug, thiserror::Error)]
pub enum {{ $c.Pascal }}ControllerError {
{{- range $c.Ports }}
    #[error("{{ .Reaching }} {id:?}")]
    {{ .Port }} {
        id: String,
        #[source]
        source: {{ .Port }}Error,
    },
{{- end }}
    #[error("finding {{ $c.Snake }} {id:?}: not found")]
    NotFound { id: String },
    #[error("validating {field:?}: {reason}")]
    Invalid { field: String, reason: String },
    #[error("running {operation:?}: not implemented")]
    NotImplemented { operation: String },
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ $c.Pascal }}Controller: Send + Sync {
{{- range $c.Ops }}
    fn {{ .Ident }}(&self{{ if .TraitArgs }}, {{ .TraitArgs }}{{ end }}) -> Result<{{ .ReturnType }}, {{ $c.Pascal }}ControllerError>;
{{- end }}
}

pub struct {{ $c.Pascal }}ControllerImpl {
{{- range $c.Ports }}
    pub(crate) {{ .PortSnake }}: Arc<dyn {{ .Port }} + Send + Sync>,
{{- end }}
}

impl {{ $c.Pascal }}ControllerImpl {
    pub fn new({{ range $i, $p := $c.Ports }}{{ if $i }}, {{ end }}{{ $p.PortSnake }}: Arc<dyn {{ $p.Port }} + Send + Sync>{{ end }}) -> Self {
        Self {{ "{" }}{{ range $i, $p := $c.Ports }}{{ if $i }},{{ end }} {{ $p.PortSnake }}{{ end }} {{ "}" }}
    }
}
{{ end -}}

{{- define "sqlite" -}}
{{ .Header }}
{{ $s := .Store }}
use std::sync::Mutex;

use rusqlite::OptionalExtension;

use {{ .CratePath }}port::{{ $s.PortSnake }}::{{ "{" }}{{ $s.Port }}, {{ $s.Port }}Error{{ "}" }};
use {{ .CratePath }}types::{{ $s.Snake }}::{{ $s.Name }};

const SCHEMA: &str = "CREATE TABLE IF NOT EXISTS {{ $s.Snake }} (id TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit (at TEXT NOT NULL, table_name TEXT NOT NULL, key TEXT NOT NULL, op TEXT NOT NULL, before TEXT, after TEXT);";

pub struct {{ $s.ConfigStruct }} {
    pub path: String,
}

impl Default for {{ $s.ConfigStruct }} {
    fn default() -> Self {
        Self {
            path: "{{ $s.DefaultPath }}".to_string(),
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum {{ $s.Name }}SqliteError {
    #[error("opening sqlite {path:?}")]
    Open {
        path: String,
        #[source]
        source: rusqlite::Error,
    },
    #[error("creating the schema in sqlite {path:?}")]
    Schema {
        path: String,
        #[source]
        source: rusqlite::Error,
    },
    #[error("locking the sqlite connection: poisoned")]
    Poisoned,
    #[error("running sql for {{ $s.Snake }} {id:?}")]
    Sql {
        id: String,
        #[source]
        source: rusqlite::Error,
    },
    #[error("encoding {{ $s.Snake }} {id:?}")]
    Json {
        id: String,
        #[source]
        source: serde_json::Error,
    },
}

pub struct {{ $s.Struct }} {
    connection: Mutex<rusqlite::Connection>,
}

impl {{ $s.Struct }} {
    pub fn new(config: {{ $s.ConfigStruct }}) -> Result<Self, {{ $s.Name }}SqliteError> {
        let path = config.path;
        let connection = rusqlite::Connection::open(&path).map_err(|source| {{ $s.Name }}SqliteError::Open {
            path: path.clone(),
            source,
        })?;
        connection
            .execute_batch(SCHEMA)
            .map_err(|source| {{ $s.Name }}SqliteError::Schema { path, source })?;
        Ok(Self {
            connection: Mutex::new(connection),
        })
    }

    fn put_row(&self, v: &{{ $s.Name }}) -> Result<(), {{ $s.Name }}SqliteError> {
        let id = v.id.clone();
        let sql = |source| {{ $s.Name }}SqliteError::Sql {
            id: id.clone(),
            source,
        };
        let after = serde_json::to_string(v).map_err(|source| {{ $s.Name }}SqliteError::Json {
            id: id.clone(),
            source,
        })?;
        let mut connection = self.connection.lock().map_err(|_| {{ $s.Name }}SqliteError::Poisoned)?;
        let tx = connection.transaction().map_err(sql)?;
        let before: Option<String> = tx
            .query_row("SELECT body FROM {{ $s.Snake }} WHERE id = ?1", [&id], |row| row.get(0))
            .optional()
            .map_err(sql)?;
        tx.execute(
            "INSERT INTO {{ $s.Snake }} (id, body) VALUES (?1, ?2) ON CONFLICT(id) DO UPDATE SET body = excluded.body",
            (&id, &after),
        )
        .map_err(sql)?;
        tx.execute(
            "INSERT INTO audit (at, table_name, key, op, before, after) VALUES (datetime('now'), '{{ $s.Snake }}', ?1, 'put', ?2, ?3)",
            (&id, &before, &after),
        )
        .map_err(sql)?;
        tx.commit().map_err(sql)?;
        Ok(())
    }

    fn get_row(&self, id: &str) -> Result<Option<{{ $s.Name }}>, {{ $s.Name }}SqliteError> {
        let connection = self.connection.lock().map_err(|_| {{ $s.Name }}SqliteError::Poisoned)?;
        let body: Option<String> = connection
            .query_row("SELECT body FROM {{ $s.Snake }} WHERE id = ?1", [id], |row| row.get(0))
            .optional()
            .map_err(|source| {{ $s.Name }}SqliteError::Sql {
                id: id.to_string(),
                source,
            })?;
        body.map(|text| serde_json::from_str(&text))
            .transpose()
            .map_err(|source| {{ $s.Name }}SqliteError::Json {
                id: id.to_string(),
                source,
            })
    }
}

impl {{ $s.Port }} for {{ $s.Struct }} {
    fn put(&self, v: {{ $s.Name }}) -> Result<(), {{ $s.Port }}Error> {
        let id = v.id.clone();
        self.put_row(&v).map_err(|source| {{ $s.Port }}Error::Put {
            id,
            source: Box::new(source),
        })
    }

    fn get(&self, id: &str) -> Result<Option<{{ $s.Name }}>, {{ $s.Port }}Error> {
        self.get_row(id).map_err(|source| {{ $s.Port }}Error::Get {
            id: id.to_string(),
            source: Box::new(source),
        })
    }
}
{{ end -}}

{{- define "wire" -}}
{{ .Header }}
{{ $v := . }}
{{ range .Types -}}
use {{ $v.CratePath }}types::{{ .Snake }}::{{ .Name }};
{{ end }}
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RejectionWire {
    pub r#type: String,
    pub message: String,
}
{{- range .Types }}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct {{ .Name }}Wire {
{{- range .Fields }}
{{- if .Renamed }}
    #[serde(rename = "{{ .Name }}")]
{{- end }}
{{- if .Optional }}
    #[serde(default, skip_serializing_if = "Option::is_none")]
{{- end }}
    pub {{ .Ident }}: {{ .WireType }},
{{- end }}
}

impl From<{{ .Name }}Wire> for {{ .Name }} {
    fn from(w: {{ .Name }}Wire) -> Self {
        Self {
{{- range .Fields }}
            {{ .Ident }}: {{ .ToCore }},
{{- end }}
        }
    }
}

impl From<{{ .Name }}> for {{ .Name }}Wire {
    fn from(v: {{ .Name }}) -> Self {
        Self {
{{- range .Fields }}
            {{ .Ident }}: {{ .ToWire }},
{{- end }}
        }
    }
}
{{- end }}
{{ end -}}

{{- define "http_driver" -}}
{{ .Header }}
{{ $v := . }}
use std::sync::Arc;

{{ if .HasStream -}}
use axum::body::{Body, Bytes};
{{ end -}}
use axum::extract::{Json, {{ if .UsesPath }}Path, {{ end }}State};
{{ if .Auth -}}
use axum::http::HeaderMap;
{{ end -}}
use axum::http::StatusCode;
{{ if .HasStream -}}
use axum::http::{header, HeaderValue};
use axum::response::Response;
{{ end -}}
use axum::routing;
use axum::Router;

{{ range .Controllers -}}
use {{ $v.CratePath }}controller::{{ "{" }}{{ .Pascal }}Controller, {{ .Pascal }}ControllerError{{ "}" }};
{{ end -}}
{{ if .Auth -}}
use {{ .CratePath }}port::ticket_verifier::{TicketVerifier, TicketVerifierError};
use {{ .CratePath }}types::subject::Subject;
{{ end -}}
{{ range .Events -}}
use {{ $v.CratePath }}types::{{ .Snake }}::{{ .Name }};
{{ end -}}
use super::wire::RejectionWire;
{{- range .WireImports }}
use super::wire::{{ . }}Wire;
{{- end }}

type Rejection = (StatusCode, Json<RejectionWire>);

fn reject(status: StatusCode, kind: &str, message: String) -> Rejection {
    (
        status,
        Json(RejectionWire {
            r#type: kind.to_string(),
            message,
        }),
    )
}

pub struct HttpDriverConfig {
    pub addr: String,
}

impl Default for HttpDriverConfig {
    fn default() -> Self {
        Self {
            addr: "{{ .DefaultAddress }}".to_string(),
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum HttpDriverError {
    #[error("binding the http driver to {address:?}")]
    Bind {
        address: String,
        #[source]
        source: std::io::Error,
    },
    #[error("reading the port the http driver bound on {address:?}")]
    Port {
        address: String,
        #[source]
        source: std::io::Error,
    },
    #[error("serving http on {address:?}")]
    Serve {
        address: String,
        #[source]
        source: std::io::Error,
    },
    #[error("using the http driver for {address:?}: it is not bound yet")]
    NotBound { address: String },
}

#[derive(Clone)]
pub struct HttpState {
{{- range .Controllers }}
    pub(crate) {{ .Snake }}_controller: Arc<dyn {{ .Pascal }}Controller + Send + Sync>,
{{- end }}
{{- if .Auth }}
    pub(crate) ticket_verifier: Arc<dyn TicketVerifier + Send + Sync>,
{{- end }}
}

pub struct HttpDriver {
    config: HttpDriverConfig,
    state: HttpState,
    listener: Option<tokio::net::TcpListener>,
}

impl HttpDriver {
    pub fn new(config: HttpDriverConfig{{ range .Controllers }}, {{ .Snake }}_controller: Arc<dyn {{ .Pascal }}Controller + Send + Sync>{{ end }}{{ if .Auth }}, ticket_verifier: Arc<dyn TicketVerifier + Send + Sync>{{ end }}) -> Self {
        Self {
            config,
            state: HttpState {{ "{" }}{{ range $i, $c := .Controllers }}{{ if $i }},{{ end }} {{ $c.Snake }}_controller{{ end }}{{ if .Auth }}, ticket_verifier{{ end }} {{ "}" }},
            listener: None,
        }
    }

    pub fn router(&self) -> Router {
        Router::new()
{{- range .Routes }}
            .route("{{ .Path }}", routing::{{ .MethodLower }}({{ .Ident }}))
{{- end }}
            .with_state(self.state.clone())
    }

    pub async fn bind(&mut self) -> Result<(), HttpDriverError> {
        let listener = tokio::net::TcpListener::bind(&self.config.addr)
            .await
            .map_err(|source| HttpDriverError::Bind {
                address: self.config.addr.clone(),
                source,
            })?;

        self.listener = Some(listener);

        Ok(())
    }

    pub fn local_port(&self) -> Result<u16, HttpDriverError> {
        let listener = self
            .listener
            .as_ref()
            .ok_or_else(|| HttpDriverError::NotBound {
                address: self.config.addr.clone(),
            })?;

        listener
            .local_addr()
            .map(|addr| addr.port())
            .map_err(|source| HttpDriverError::Port {
                address: self.config.addr.clone(),
                source,
            })
    }

    pub fn announce(&self) -> Result<(), HttpDriverError> {
        println!("LISTENING {}", self.local_port()?);

        Ok(())
    }

    pub async fn serve(self) -> Result<(), HttpDriverError> {
        let router = self.router();
        let address = self.config.addr.clone();

        let listener = self.listener.ok_or(HttpDriverError::NotBound {
            address: address.clone(),
        })?;

        axum::serve(listener, router)
            .await
            .map_err(|source| HttpDriverError::Serve { address, source })
    }
}
{{- if .Auth }}

fn authenticate(state: &HttpState, headers: &HeaderMap) -> Result<Subject, Rejection> {
    let token = bearer_token(headers).ok_or_else(|| {
        reject(
            StatusCode::UNAUTHORIZED,
            "authentication",
            "missing bearer token in the authorization header".to_string(),
        )
    })?;

    state.ticket_verifier.verify(token).map_err(|error| match error {
        TicketVerifierError::Refused { .. } => {
            reject(StatusCode::UNAUTHORIZED, "authentication", error.to_string())
        }
        TicketVerifierError::Verify { .. } => {
            eprintln!("{error:?}");
            reject(StatusCode::INTERNAL_SERVER_ERROR, "runtime", "internal error".to_string())
        }
    })
}

fn bearer_token(headers: &HeaderMap) -> Option<&str> {
    let value = headers.get(axum::http::header::AUTHORIZATION)?.to_str().ok()?;
    let token = value.strip_prefix("Bearer ")?.trim();

    if token.is_empty() {
        return None;
    }

    Some(token)
}
{{- end }}
{{- if .HasStream }}

const EVENT_STREAM_BUFFER: usize = 16;

fn event_stream<T, W>(events: std::sync::mpsc::Receiver<T>) -> Response
where
    T: Send + 'static,
    W: From<T> + serde::Serialize + 'static,
{
    let (mut sender, body) = http_body_util::channel::Channel::<Bytes>::new(EVENT_STREAM_BUFFER);
    let handle = tokio::runtime::Handle::current();

    tokio::task::spawn_blocking(move || {
        while let Ok(event) = events.recv() {
            let Ok(json) = serde_json::to_string(&W::from(event)) else {
                break;
            };

            let frame = Bytes::from(format!("data: {json}\n\n"));

            if handle.block_on(sender.send_data(frame)).is_err() {
                break;
            }
        }
    });

    let mut response = Response::new(Body::new(body));
    response
        .headers_mut()
        .insert(header::CONTENT_TYPE, HeaderValue::from_static("text/event-stream"));
    response
        .headers_mut()
        .insert(header::CACHE_CONTROL, HeaderValue::from_static("no-cache"));

    response
}
{{- end }}
{{ range .Controllers }}{{ $c := . }}
fn reject_{{ $c.Snake }}(error: {{ $c.Pascal }}ControllerError, invalid: StatusCode) -> Rejection {
    match error {
{{- range $c.Ports }}
        {{ $c.Pascal }}ControllerError::{{ .Port }} { .. } => {
            eprintln!("{error:?}");
            reject(StatusCode::INTERNAL_SERVER_ERROR, "runtime", "internal error".to_string())
        }
{{- end }}
        {{ $c.Pascal }}ControllerError::NotFound { .. } => reject(StatusCode::NOT_FOUND, "semantic", error.to_string()),
        {{ $c.Pascal }}ControllerError::Invalid { .. } => reject(invalid, "validation", error.to_string()),
        {{ $c.Pascal }}ControllerError::NotImplemented { .. } => reject(StatusCode::NOT_IMPLEMENTED, "runtime", error.to_string()),
    }
}
{{ end }}
{{- range .Routes }}
async fn {{ .Ident }}({{ .Extractors }}) -> {{ .HandlerReturn }} {
{{- if .Auth }}
    let subject = authenticate(&state, &headers)?;
{{- end }}
{{- if .Stream }}
    let events = state
        .{{ .ControllerSnake }}_controller
        .{{ .Ident }}({{ .ControllerCall }})
        .map_err(|error| reject_{{ .ControllerSnake }}(error, {{ .InvalidStatusExpr }}))?;
{{- else if .Response }}
    let out = state
        .{{ .ControllerSnake }}_controller
        .{{ .Ident }}({{ .ControllerCall }})
        .map_err(|error| reject_{{ .ControllerSnake }}(error, {{ .InvalidStatusExpr }}))?;
{{- else }}
    state
        .{{ .ControllerSnake }}_controller
        .{{ .Ident }}({{ .ControllerCall }})
        .map_err(|error| reject_{{ .ControllerSnake }}(error, {{ .InvalidStatusExpr }}))?;
{{- end }}
    Ok({{ .OkExpr }})
}
{{ end -}}
{{ end -}}

{{- define "rest_client" -}}
{{ .Header }}
{{ $c := .Client }}
use std::sync::Arc;

use serde::de::DeserializeOwned;

use {{ .CratePath }}port::token_source::TokenSource;
use {{ .CratePath }}port::{{ $c.PortModule }}::{{ "{" }}{{ $c.Trait }}, {{ $c.Error }}{{ "}" }};
{{ range $c.TypeImports -}}
use {{ $.CratePath }}types::{{ .Snake }}::{{ .Name }};
{{ end -}}
use super::wire::RejectionWire;
{{- range $c.TypeImports }}
use super::wire::{{ .Name }}Wire;
{{- end }}

pub struct {{ $c.Config }} {
    pub base_url: String,
}

impl Default for {{ $c.Config }} {
    fn default() -> Self {
        Self {
            base_url: "{{ .DefaultBaseURL }}".to_string(),
        }
    }
}

pub struct {{ $c.Struct }} {
    base_url: String,
    client: reqwest::Client,
    token_source: Arc<dyn TokenSource + Send + Sync>,
}

impl {{ $c.Struct }} {
    pub fn new(config: {{ $c.Config }}, token_source: Arc<dyn TokenSource + Send + Sync>) -> Self {
        Self {
            base_url: config.base_url.trim_end_matches('/').to_string(),
            client: reqwest::Client::new(),
            token_source,
        }
    }

    fn bearer(&self, operation: &str) -> Result<String, {{ $c.Error }}> {
        self.token_source
            .token()
            .map_err(|source| {{ $c.Error }}::Authentication {
                operation: operation.to_string(),
                message: source.to_string(),
            })
    }

    fn block<T>(&self, future: impl std::future::Future<Output = T>) -> T {
        tokio::task::block_in_place(|| tokio::runtime::Handle::current().block_on(future))
    }
}

async fn send(operation: &str, request: reqwest::RequestBuilder) -> Result<reqwest::Response, {{ $c.Error }}> {
    let response = request
        .send()
        .await
        .map_err(|source| transport(operation, source))?;

    if response.status().is_success() {
        return Ok(response);
    }

    Err(rejection(operation, response).await)
}

#[allow(dead_code)]
async fn answer<W: DeserializeOwned>(operation: &str, request: reqwest::RequestBuilder) -> Result<W, {{ $c.Error }}> {
    send(operation, request)
        .await?
        .json::<W>()
        .await
        .map_err(|source| transport(operation, source))
}

#[allow(dead_code)]
async fn accept(operation: &str, request: reqwest::RequestBuilder) -> Result<(), {{ $c.Error }}> {
    send(operation, request).await.map(|_response| ())
}

fn transport(operation: &str, source: reqwest::Error) -> {{ $c.Error }} {
    {{ $c.Error }}::Runtime {
        operation: operation.to_string(),
        message: "transport failure".to_string(),
        source: Some(Box::new(source)),
    }
}

async fn rejection(operation: &str, response: reqwest::Response) -> {{ $c.Error }} {
    let status = response.status();
    let text = response.text().await.unwrap_or_default();
    let operation = operation.to_string();

    let Ok(wire) = serde_json::from_str::<RejectionWire>(&text) else {
        return {{ $c.Error }}::Runtime {
            operation,
            message: format!("{status}: {text}"),
            source: None,
        };
    };

    match wire.r#type.as_str() {
        "authentication" => {{ $c.Error }}::Authentication { operation, message: wire.message },
        "authorization" => {{ $c.Error }}::Authorization { operation, message: wire.message },
        "validation" => {{ $c.Error }}::Validation { operation, message: wire.message },
        "semantic" => {{ $c.Error }}::Semantic { operation, message: wire.message },
        "rateLimiting" => {{ $c.Error }}::RateLimiting { operation, message: wire.message },
        "runtime" => {{ $c.Error }}::Runtime {
            operation,
            message: wire.message,
            source: None,
        },
        other => {{ $c.Error }}::Runtime {
            operation,
            message: format!("{status}: unknown error type {other:?}: {}", wire.message),
            source: None,
        },
    }
}
{{- if $c.HasStream }}

async fn stream_events<W, T>(operation: &str, request: reqwest::RequestBuilder) -> Result<std::sync::mpsc::Receiver<T>, {{ $c.Error }}>
where
    W: DeserializeOwned + Send + 'static,
    T: From<W> + Send + 'static,
{
    let response = send(operation, request).await?;
    let (sender, receiver) = std::sync::mpsc::channel();

    tokio::spawn(forward_events::<W, T>(response, sender));

    Ok(receiver)
}

async fn forward_events<W, T>(mut response: reqwest::Response, sender: std::sync::mpsc::Sender<T>)
where
    W: DeserializeOwned + Send + 'static,
    T: From<W> + Send + 'static,
{
    let mut buffer: Vec<u8> = Vec::new();

    while let Ok(Some(chunk)) = response.chunk().await {
        buffer.extend_from_slice(&chunk);

        while let Some(end) = frame_end(&buffer) {
            let frame: Vec<u8> = buffer.drain(..end + 2).collect();

            for event in parse_frame::<W>(&frame) {
                if sender.send(T::from(event)).is_err() {
                    return;
                }
            }
        }
    }
}

fn frame_end(buffer: &[u8]) -> Option<usize> {
    buffer.windows(2).position(|pair| pair == b"\n\n")
}

fn parse_frame<W: DeserializeOwned>(frame: &[u8]) -> Vec<W> {
    String::from_utf8_lossy(frame)
        .lines()
        .filter_map(|line| line.strip_prefix("data:"))
        .filter_map(|data| serde_json::from_str::<W>(data.trim_start()).ok())
        .collect()
}
{{- end }}

impl {{ $c.Trait }} for {{ $c.Struct }} {
{{- range $c.Ops }}
    fn {{ .Ident }}(&self{{ if .ClientArgs }}, {{ .ClientArgs }}{{ end }}) -> Result<{{ .ClientReturn }}, {{ $c.Error }}> {
        let operation = "{{ .ID }}";
        let request = self
            .client
            .request(reqwest::Method::{{ .Method }}, {{ .URLExpr }}){{ if .Body }}
            .json(&{{ .Body }}Wire::from(body)){{ end }}{{ if .Stream }}
            .header("accept", "text/event-stream"){{ end }};
{{- if .Auth }}
        let request = request.bearer_auth(self.bearer(operation)?);
{{- end }}
{{- if .Stream }}

        self.block(stream_events::<{{ .Response }}Wire, {{ .Response }}>(operation, request))
{{- else if .Response }}

        self.block(answer::<{{ .Response }}Wire>(operation, request)).map({{ .Response }}::from)
{{- else }}

        self.block(accept(operation, request))
{{- end }}
    }
{{- end }}
}
{{ end -}}
`))
