// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package udprust

import (
	"bytes"
	"fmt"
	"path"
	"regexp"
	"sort"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/grpcrust"
)

const header = "// Code generated by udp-rust (forge-dev-codegen). DO NOT EDIT."

const DefaultCell = "udp"

const maxRpcs = 256

var cellIdent = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

func checkCell(name string) error {
	if cellIdent.MatchString(name) && !grpcrust.IsRustKeyword(name) {
		return nil
	}

	return fmt.Errorf("emitting the skeleton: cell %q is not a name Rust can spell as a module, use lowercase letters, digits and underscores and start with a letter", name)
}

func sideOfLayer(layer string) string {
	if layer == "adapter" || layer == "driver" {
		return "app"
	}

	return "core"
}

type modEntry struct {
	Module string
	Alias  string
}

type layerMod struct {
	Header  string
	Entries []modEntry
}

func Generate(doc []byte, opts Options) ([]File, error) {
	if opts.Service == "" {
		return nil, fmt.Errorf("emitting the skeleton: the service name is required")
	}

	if opts.Cell == "" {
		opts.Cell = DefaultCell
	}

	if err := checkCell(opts.Cell); err != nil {
		return nil, err
	}

	if opts.Side != "" && opts.Side != "core" && opts.Side != "app" {
		return nil, fmt.Errorf("emitting the skeleton: side must be core, app or empty, got %q", opts.Side)
	}

	spec, err := grpcrust.Parse(doc)
	if err != nil {
		return nil, err
	}

	if len(spec.Services) == 0 {
		return nil, fmt.Errorf("emitting the skeleton: the proto document declares no service")
	}

	files := []File{}

	add := func(side, p, name string, data any, writeOnce bool) error {
		if opts.Side != "" && opts.Side != side {
			return nil
		}

		content, err := render(name, data)
		if err != nil {
			return err
		}

		files = append(files, File{Path: p, Content: content, WriteOnce: writeOnce})

		return nil
	}

	entries := map[string][]modEntry{}

	mount := func(layer string, entry modEntry) {
		entries[layer] = append(entries[layer], entry)
	}

	for _, svc := range spec.Services {
		v, err := buildServiceView(spec, svc, opts)
		if err != nil {
			return nil, err
		}

		steps := []func() error{
			func() error {
				return add("app", path.Join("adapter", "zz_generated_"+v.ServiceSnake+"_udp_client.rs"), "adapter", v, false)
			},
			func() error {
				return add("app", path.Join("driver", "zz_generated_"+v.ServiceSnake+"_udp_driver.rs"), "driver", v, false)
			},
			func() error {
				return add("core", path.Join("port", "zz_generated_"+v.ServiceSnake+"_client.rs"), "port", v, false)
			},
			func() error {
				return add("core", path.Join("types", "zz_generated_"+v.ServiceSnake+"_messages.rs"), "types", v, false)
			},
			func() error {
				return add("core", path.Join("controller", "zz_generated_"+v.ControllerSnake+"_controller.rs"), "controller", v, false)
			},
			func() error {
				return add("core", path.Join("controller", "zz_generated_"+v.ServiceSnake+"_codec.rs"), "codec", v, false)
			},
			func() error {
				return add("core", path.Join("hand", v.ControllerSnake+"_controller.rs"), "hand", v, true)
			},
		}

		for _, step := range steps {
			if err := step(); err != nil {
				return nil, err
			}
		}

		mount("adapter", modEntry{Module: "zz_generated_" + v.ServiceSnake + "_udp_client", Alias: v.ServiceSnake + "_udp_client"})
		mount("driver", modEntry{Module: "zz_generated_" + v.ServiceSnake + "_udp_driver", Alias: v.ServiceSnake + "_udp_driver"})
		mount("port", modEntry{Module: "zz_generated_" + v.ServiceSnake + "_client", Alias: v.ServiceSnake + "_client"})
		mount("types", modEntry{Module: "zz_generated_" + v.ServiceSnake + "_messages", Alias: v.ServiceSnake + "_messages"})
		mount("controller", modEntry{Module: "zz_generated_" + v.ControllerSnake + "_controller", Alias: v.ControllerSnake + "_controller"})
		mount("controller", modEntry{Module: "zz_generated_" + v.ServiceSnake + "_codec", Alias: v.ServiceSnake + "_codec"})
		mount("hand", modEntry{Module: v.ControllerSnake + "_controller"})
	}

	if err := add("core", path.Join("types", "zz_generated_context.rs"), "context", map[string]any{"Header": header}, false); err != nil {
		return nil, err
	}

	mount("types", modEntry{Module: "zz_generated_context", Alias: "context"})

	cellLayers := []string{}

	for _, layer := range []string{"adapter", "controller", "driver", "hand", "port", "types"} {
		if opts.Side != "" && opts.Side != sideOfLayer(layer) {
			continue
		}

		cellLayers = append(cellLayers, layer)

		mod := layerMod{Header: header, Entries: entries[layer]}
		sort.Slice(mod.Entries, func(i, j int) bool { return mod.Entries[i].Module < mod.Entries[j].Module })

		if err := add(sideOfLayer(layer), path.Join(layer, "mod.rs"), "layer_mod", mod, false); err != nil {
			return nil, err
		}
	}

	cell, err := render("cell_mod", map[string]any{"Header": header, "Layers": cellLayers})
	if err != nil {
		return nil, err
	}

	files = append(files, File{Path: "mod.rs", Content: cell})

	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })

	return files, nil
}

func render(name string, data any) (string, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", fmt.Errorf("rendering %s: %w", name, err)
	}

	return buf.String(), nil
}

var templates = template.Must(template.New("udprust").Parse(`
{{- define "cell_mod" -}}
{{ .Header }}
{{ range .Layers }}
pub mod {{ . }};
{{- end }}
{{ end -}}

{{- define "layer_mod" -}}
{{ .Header }}
{{ range .Entries }}
pub mod {{ .Module }};
{{- end }}
{{- range .Entries }}{{ if .Alias }}

pub use {{ .Module }} as {{ .Alias }};
{{- end }}{{ end }}
{{ end -}}

{{- define "context" -}}
{{ .Header }}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Context {
    pub session_id: [u8; 16],
    pub peer: std::net::SocketAddr,
}
{{ end -}}

{{- define "types" -}}
{{ .Header }}
{{ range .Messages }}
#[derive(Clone, PartialEq, prost::Message)]
pub struct {{ .Name }} {
{{- range .Fields }}
    {{ .Prost }}
    pub {{ .Ident }}: {{ .RustType }},
{{- end }}
}
{{ end }}
#[derive(Clone, PartialEq, prost::Oneof)]
pub enum {{ .EnvelopeEnum }} {
{{- range .Rpcs }}
    #[prost(message, tag = "{{ .EnvelopeTag }}")]
    {{ .Pascal }}({{ .Request }}),
{{- end }}
}

#[derive(Clone, PartialEq, prost::Message)]
pub struct {{ .EnvelopeStruct }} {
    #[prost(oneof = "{{ .EnvelopeEnum }}", tags = "{{ .EnvelopeTags }}")]
    pub kind: Option<{{ .EnvelopeEnum }}>,
}
{{ end -}}

{{- define "port" -}}
{{ .Header }}

use crate::{{ .Cell }}::types::{{ .ServiceSnake }}_messages::{{ "{" }}{{ range $i, $t := .TraitTypes }}{{ if $i }}, {{ end }}{{ $t }}{{ end }}{{ "}" }};

#[derive(Debug, thiserror::Error)]
pub enum {{ .ClientError }} {
{{- range .Rpcs }}
    #[error("calling {{ .Ident }}")]
    {{ .Pascal }} {
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
{{- end }}
}

pub trait {{ .ClientTrait }}: Send + Sync {
{{- range .Rpcs }}
    fn {{ .Ident }}(
        &self,
        request: {{ .Request }},
    ) -> impl std::future::Future<Output = Result<{{ .Reply }}, {{ $.ClientError }}>> + Send;
{{- end }}
}
{{ end -}}

{{- define "controller" -}}
{{ .Header }}

use crate::{{ .Cell }}::types::context::Context;
use crate::{{ .Cell }}::types::{{ .ServiceSnake }}_messages::{{ "{" }}{{ range $i, $t := .TraitTypes }}{{ if $i }}, {{ end }}{{ $t }}{{ end }}{{ "}" }};

#[derive(Debug, thiserror::Error)]
pub enum {{ .ControllerError }} {
    #[error("validating {field:?}: {reason}")]
    Invalid { field: String, reason: String },
    #[error("running {operation:?}: not implemented")]
    NotImplemented { operation: String },
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ .ControllerTrait }}: Send + Sync {
{{- range .Rpcs }}
    fn {{ .Ident }}(
        &self,
        request: {{ .Request }},
        context: &Context,
    ) -> Result<{{ .Reply }}, {{ $.ControllerError }}>;
{{- end }}
}

pub struct {{ .ControllerTrait }}Impl;

impl {{ .ControllerTrait }}Impl {
    pub fn new() -> Self {
        Self
    }
}

impl Default for {{ .ControllerTrait }}Impl {
    fn default() -> Self {
        Self::new()
    }
}

impl {{ .ControllerTrait }} for {{ .ControllerTrait }}Impl {
{{- range .Rpcs }}
    fn {{ .Ident }}(
        &self,
        request: {{ .Request }},
        context: &Context,
    ) -> Result<{{ .Reply }}, {{ $.ControllerError }}> {
        crate::{{ $.Cell }}::hand::{{ $.ControllerSnake }}_controller::{{ .Ident }}(request, context)
    }
{{ end -}}
}
{{ end -}}

{{- define "codec" -}}
{{ .Header }}

use prost::Message;

use crate::{{ .Cell }}::types::{{ .ServiceSnake }}_messages::{{ "{" }}{{ range $i, $t := .TraitTypes }}{{ if $i }}, {{ end }}{{ $t }}{{ end }}{{ "}" }};

pub const MAGIC: [u8; 4] = 0x5555_4944u32.to_be_bytes();
pub const MAGIC_LEN: usize = 4;
pub const SESSION_ID_LEN: usize = 16;
pub const TAG_LEN: usize = 1;
pub const HEADER_LEN: usize = MAGIC_LEN + SESSION_ID_LEN + TAG_LEN;
pub const MAX_DATAGRAM_LEN: usize = 508;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum {{ .KindEnum }} {
{{- range .Rpcs }}
    {{ .Pascal }},
{{- end }}
}

pub fn encode_tag(kind: {{ .KindEnum }}) -> [u8; TAG_LEN] {
    match kind {
{{- range .Rpcs }}
        {{ $.KindEnum }}::{{ .Pascal }} => [{{ .Tag }}],
{{- end }}
    }
}

pub fn decode_tag(tag: [u8; TAG_LEN]) -> Option<{{ .KindEnum }}> {
    match tag {
{{- range .Rpcs }}
        [{{ .Tag }}] => Some({{ $.KindEnum }}::{{ .Pascal }}),
{{- end }}
        _ => None,
    }
}

#[derive(Debug, thiserror::Error)]
pub enum {{ .CodecError }} {
    #[error("reading a datagram of {length} bytes: it does not open with the udplb magic")]
    Magic { length: usize },
    #[error("reading a datagram of {length} bytes: a datagram opens with a magic, a session id and a tag")]
    Short { length: usize },
    #[error("reading a datagram of {length} bytes: a datagram carries at most {MAX_DATAGRAM_LEN} bytes")]
    Long { length: usize },
    #[error("reading a datagram of {length} bytes: tag {tag} names no rpc of {{ .ServicePascal }}")]
    UnknownVariant { length: usize, tag: u8 },
    #[error("decoding the {operation} payload of a datagram")]
    Payload {
        operation: &'static str,
        #[source]
        source: prost::DecodeError,
    },
    #[error("encoding {operation} into a datagram of {length} bytes: a datagram carries at most {MAX_DATAGRAM_LEN} bytes")]
    Oversize { operation: &'static str, length: usize },
}

#[derive(Debug, Clone, PartialEq)]
pub enum {{ .RequestEnum }} {
{{- range .Rpcs }}
    {{ .Pascal }}({{ .Request }}),
{{- end }}
}

pub fn is_health_probe(datagram: &[u8]) -> bool {
    datagram.len() >= MAGIC_LEN + SESSION_ID_LEN
        && datagram[..MAGIC_LEN] == MAGIC
        && datagram[MAGIC_LEN..MAGIC_LEN + SESSION_ID_LEN] == [0u8; SESSION_ID_LEN]
}

pub fn frame(session_id: &[u8; SESSION_ID_LEN], tag: [u8; TAG_LEN], payload: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(HEADER_LEN + payload.len());
    out.extend_from_slice(&MAGIC);
    out.extend_from_slice(session_id);
    out.extend_from_slice(&tag);
    out.extend_from_slice(payload);
    out
}

type Unframed<'a> = ([u8; SESSION_ID_LEN], [u8; TAG_LEN], &'a [u8]);

pub fn unframe(datagram: &[u8]) -> Result<Unframed<'_>, {{ .CodecError }}> {
    if datagram.len() > MAX_DATAGRAM_LEN {
        return Err({{ .CodecError }}::Long {
            length: datagram.len(),
        });
    }

    if datagram.len() < HEADER_LEN {
        return Err({{ .CodecError }}::Short {
            length: datagram.len(),
        });
    }

    if datagram[..MAGIC_LEN] != MAGIC {
        return Err({{ .CodecError }}::Magic {
            length: datagram.len(),
        });
    }

    let mut session_id = [0u8; SESSION_ID_LEN];
    session_id.copy_from_slice(&datagram[MAGIC_LEN..MAGIC_LEN + SESSION_ID_LEN]);

    let mut tag = [0u8; TAG_LEN];
    tag.copy_from_slice(&datagram[MAGIC_LEN + SESSION_ID_LEN..HEADER_LEN]);

    Ok((session_id, tag, &datagram[HEADER_LEN..]))
}

pub fn decode_request(
    datagram: &[u8],
) -> Result<([u8; SESSION_ID_LEN], {{ .RequestEnum }}), {{ .CodecError }}> {
    let (session_id, tag, payload) = unframe(datagram)?;

    let kind = decode_tag(tag).ok_or({{ .CodecError }}::UnknownVariant {
        length: datagram.len(),
        tag: tag[0],
    })?;

    let request = match kind {
{{- range .Rpcs }}
        {{ $.KindEnum }}::{{ .Pascal }} => {{ $.RequestEnum }}::{{ .Pascal }}({{ .Request }}::decode(payload).map_err(
            |source| {{ $.CodecError }}::Payload {
                operation: "{{ .Ident }}",
                source,
            },
        )?),
{{- end }}
    };

    Ok((session_id, request))
}

fn seal<M: Message>(
    operation: &'static str,
    session_id: &[u8; SESSION_ID_LEN],
    tag: [u8; TAG_LEN],
    message: &M,
) -> Result<Vec<u8>, {{ .CodecError }}> {
    let out = frame(session_id, tag, &message.encode_to_vec());

    if out.len() > MAX_DATAGRAM_LEN {
        return Err({{ .CodecError }}::Oversize {
            operation,
            length: out.len(),
        });
    }

    Ok(out)
}
{{ range .Rpcs }}
pub fn encode_{{ .Ident }}_request(
    session_id: &[u8; SESSION_ID_LEN],
    request: &{{ .Request }},
) -> Result<Vec<u8>, {{ $.CodecError }}> {
    seal("{{ .Ident }}", session_id, encode_tag({{ $.KindEnum }}::{{ .Pascal }}), request)
}

pub fn encode_{{ .Ident }}_reply(
    session_id: &[u8; SESSION_ID_LEN],
    reply: &{{ .Reply }},
) -> Result<Vec<u8>, {{ $.CodecError }}> {
    seal("{{ .Ident }}", session_id, encode_tag({{ $.KindEnum }}::{{ .Pascal }}), reply)
}

pub fn decode_{{ .Ident }}_reply(datagram: &[u8]) -> Result<{{ .Reply }}, {{ $.CodecError }}> {
    let (_, tag, payload) = unframe(datagram)?;

    if decode_tag(tag) != Some({{ $.KindEnum }}::{{ .Pascal }}) {
        return Err({{ $.CodecError }}::UnknownVariant {
            length: datagram.len(),
            tag: tag[0],
        });
    }

    {{ .Reply }}::decode(payload).map_err(|source| {{ $.CodecError }}::Payload {
        operation: "{{ .Ident }}",
        source,
    })
}
{{ end -}}
{{ end -}}

{{- define "hand" -}}
use crate::{{ .Cell }}::controller::{{ .ControllerSnake }}_controller::{{ .ControllerError }};
use crate::{{ .Cell }}::types::context::Context;
use crate::{{ .Cell }}::types::{{ .ServiceSnake }}_messages::{{ "{" }}{{ range $i, $t := .TraitTypes }}{{ if $i }}, {{ end }}{{ $t }}{{ end }}{{ "}" }};
{{ range .Rpcs }}
pub fn {{ .Ident }}(
    request: {{ .Request }},
    context: &Context,
) -> Result<{{ .Reply }}, {{ $.ControllerError }}> {
    let _ = request;
    let _ = context;

    Err({{ $.ControllerError }}::NotImplemented {
        operation: "{{ .Ident }}".to_string(),
    })
}
{{ end -}}
{{ end -}}

{{- define "driver" -}}
{{ .Header }}

use std::sync::Arc;
use std::time::Duration;

use {{ .CoreCrate }}::{{ .Cell }}::controller::{{ .ServiceSnake }}_codec as codec;
use {{ .CoreCrate }}::{{ .Cell }}::controller::{{ .ControllerSnake }}_controller::{{ .ControllerTrait }};
use {{ .CoreCrate }}::{{ .Cell }}::types::context::Context;

const RECV_ERROR_PAUSE: Duration = Duration::from_millis(50);
const MAX_CONSECUTIVE_RECV_ERRORS: usize = 100;

#[derive(Debug, thiserror::Error)]
#[error("receiving on the udp socket {address} failed {count} times in a row")]
pub struct {{ .DriverError }} {
    address: String,
    count: usize,
    #[source]
    source: std::io::Error,
}

pub struct {{ .DriverStruct }} {
    socket: tokio::net::UdpSocket,
    controller: Arc<dyn {{ .ControllerTrait }}>,
}

impl {{ .DriverStruct }} {
    pub fn new(socket: tokio::net::UdpSocket, controller: Arc<dyn {{ .ControllerTrait }}>) -> Self {
        Self { socket, controller }
    }

    pub fn local_port(&self) -> std::io::Result<u16> {
        Ok(self.socket.local_addr()?.port())
    }

    pub fn announce(&self) -> std::io::Result<()> {
        println!("LISTENING_UDP {}", self.local_port()?);

        Ok(())
    }

    pub async fn serve(self) -> Result<(), {{ .DriverError }}> {
        let address = self
            .socket
            .local_addr()
            .map(|addr| addr.to_string())
            .unwrap_or_else(|_| "an unbound socket".to_string());

        let mut buffer = [0u8; codec::MAX_DATAGRAM_LEN + 1];
        let mut consecutive_recv_errors = 0usize;

        loop {
            let (read, peer) = match self.socket.recv_from(&mut buffer).await {
                Ok(received) => received,
                Err(source) => {
                    consecutive_recv_errors += 1;

                    if consecutive_recv_errors >= MAX_CONSECUTIVE_RECV_ERRORS {
                        return Err({{ .DriverError }} {
                            address,
                            count: consecutive_recv_errors,
                            source,
                        });
                    }

                    tokio::time::sleep(RECV_ERROR_PAUSE).await;

                    continue;
                }
            };

            consecutive_recv_errors = 0;

            let datagram = &buffer[..read];

            if codec::is_health_probe(datagram) {
                send(&self.socket, datagram, peer, &address).await;

                continue;
            }

            let Ok((session_id, request)) = codec::decode_request(datagram) else {
                continue;
            };

            let context = Context { session_id, peer };

            let answer = match request {
{{- range .Rpcs }}
                codec::{{ $.RequestEnum }}::{{ .Pascal }}(request) => {
                    match self.controller.{{ .Ident }}(request, &context) {
{{- if .Silent }}
                        Ok(_) => None,
{{- else }}
                        Ok(reply) => codec::encode_{{ .Ident }}_reply(&session_id, &reply).ok(),
{{- end }}
                        Err(_) => None,
                    }
                }
{{- end }}
            };

            let Some(answer) = answer else {
                continue;
            };

            send(&self.socket, &answer, peer, &address).await;
        }
    }
}

async fn send(
    socket: &tokio::net::UdpSocket,
    answer: &[u8],
    peer: std::net::SocketAddr,
    address: &str,
) {
    if let Err(source) = socket.send_to(answer, peer).await {
        eprintln!("sending a udp answer from {address} to {peer}: {source}");
    }
}
{{ end -}}

{{- define "adapter" -}}
{{ .Header }}

use std::time::Duration;

use {{ .CoreCrate }}::{{ .Cell }}::controller::{{ .ServiceSnake }}_codec as codec;
use {{ .CoreCrate }}::{{ .Cell }}::port::{{ .ServiceSnake }}_client::{{ "{" }}{{ .ClientError }}, {{ .ClientTrait }}{{ "}" }};
use {{ .CoreCrate }}::{{ .Cell }}::types::{{ .ServiceSnake }}_messages::{{ "{" }}{{ range $i, $t := .TraitTypes }}{{ if $i }}, {{ end }}{{ $t }}{{ end }}{{ "}" }};

const ANSWER_TIMEOUT: Duration = Duration::from_secs(2);

pub struct {{ .ClientStruct }} {
    address: String,
    session_id: [u8; codec::SESSION_ID_LEN],
    timeout: Duration,
}

impl {{ .ClientStruct }} {
    pub fn new(address: String, session_id: [u8; codec::SESSION_ID_LEN]) -> Self {
        Self {
            address,
            session_id,
            timeout: ANSWER_TIMEOUT,
        }
    }

    pub fn with_timeout(mut self, timeout: Duration) -> Self {
        self.timeout = timeout;
        self
    }

    pub fn address(&self) -> &str {
        &self.address
    }
}

impl {{ .ClientTrait }} for {{ .ClientStruct }} {
{{- range .Rpcs }}
    async fn {{ .Ident }}(&self, request: {{ .Request }}) -> Result<{{ .Reply }}, {{ $.ClientError }}> {
        let datagram = codec::encode_{{ .Ident }}_request(&self.session_id, &request)
            .map_err(failing_{{ .Ident }})?;

        let socket = tokio::net::UdpSocket::bind("0.0.0.0:0")
            .await
            .map_err(failing_{{ .Ident }})?;

        socket
            .send_to(&datagram, &self.address)
            .await
            .map_err(failing_{{ .Ident }})?;
{{ if .Silent }}
        Ok({{ .Reply }}::default())
{{- else }}
        let mut buffer = [0u8; codec::MAX_DATAGRAM_LEN + 1];

        let read = tokio::time::timeout(self.timeout, socket.recv(&mut buffer))
            .await
            .map_err(failing_{{ .Ident }})?
            .map_err(failing_{{ .Ident }})?;

        codec::decode_{{ .Ident }}_reply(&buffer[..read]).map_err(failing_{{ .Ident }})
{{- end }}
    }
{{ end -}}
}
{{ range .Rpcs }}
fn failing_{{ .Ident }}<E: std::error::Error + Send + Sync + 'static>(source: E) -> {{ $.ClientError }} {
    {{ $.ClientError }}::{{ .Pascal }} {
        source: Box::new(source),
    }
}
{{ end -}}
{{ end -}}
`))
