// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package vectorsrust

import (
	"bytes"
	"fmt"
	"path"
	"regexp"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/hexrust"
)

const header = "// Code generated by vectors-rust (forge-dev-codegen). DO NOT EDIT."

type Options struct {
	Service string
	AppDir  string
}

type File struct {
	Path    string
	Content string
}

var serviceIdent = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

func Generate(openapiDoc, vectorsDoc []byte, opts Options) ([]File, error) {
	if opts.Service == "" {
		return nil, fmt.Errorf("emitting the vectors: the service name is required")
	}

	if !serviceIdent.MatchString(hexrust.Snake(opts.Service)) {
		return nil, fmt.Errorf("emitting the vectors: service name %q is not one Rust or Cargo can spell, use letters, digits and underscores and start with a letter", opts.Service)
	}

	if opts.AppDir == "" {
		opts.AppDir = "app"
	}

	spec, err := hexrust.Parse(openapiDoc)
	if err != nil {
		return nil, err
	}

	vectors, err := parseVectors(vectorsDoc)
	if err != nil {
		return nil, err
	}

	v, err := buildView(spec, vectors, opts)
	if err != nil {
		return nil, err
	}

	content, err := render("file", v)
	if err != nil {
		return nil, err
	}

	return []File{
		{
			Path:    path.Join(opts.AppDir, "tests", "zz_generated_vectors.rs"),
			Content: content,
		},
	}, nil
}

func render(name string, data any) (string, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", fmt.Errorf("rendering %s: %w", name, err)
	}

	return buf.String(), nil
}

var templates = template.Must(template.New("vectorsrust").Parse(`
{{- define "file" -}}
{{ .Header }}

use axum::body::Body;
use axum::http::Request;
use http_body_util::BodyExt;
use tower::ServiceExt;

use {{ .AppCrate }}::driver::http_driver::HttpDriver;
{{ range .Controllers -}}
use {{ $.CoreCrate }}::controller::{{ .Snake }}_controller::{{ .Pascal }}ControllerError;
{{ end -}}
{{ range .PortErrors -}}
use {{ $.CoreCrate }}::port::{{ .Snake }}::{{ .Port }}Error;
{{ end -}}
{{ range .TypeImports -}}
use {{ $.CoreCrate }}::types::{{ .Snake }}::{{ .Name }};
{{ end }}
{{ range .Controllers }}{{ $c := . }}
mockall::mock! {
    pub {{ $c.Pascal }}Controller {}
    impl {{ $.CoreCrate }}::controller::{{ $c.Snake }}_controller::{{ $c.Pascal }}Controller for {{ $c.Pascal }}Controller {
{{- range $c.Ops }}
        fn {{ .Ident }}(&self{{ if .TraitArgs }}, {{ .TraitArgs }}{{ end }}) -> Result<{{ .ReturnType }}, {{ $c.Pascal }}ControllerError>;
{{- end }}
    }
}
{{ end }}
{{ range .Tests }}
#[tokio::test]
async fn {{ .Name }}() {
    let mut {{ .ArmVar }} = Mock{{ .ArmController }}Controller::new();
    {{ .ArmVar }}
        .{{ .ArmExpectMethod }}()
        .times(1)
        .returning(|{{ .ArmClosureParams }}| {{ .ArmReturning }});

    let driver = HttpDriver::new({{ range $i, $a := .DriverArgs }}{{ if $i }}, {{ end }}{{ $a }}{{ end }});

    let request = Request::builder()
        .method("{{ .Method }}")
        .uri("{{ .URI }}")
{{- if .HasBody }}
        .header("content-type", "application/json")
        .body(Body::from({{ .BodyLiteral }}))
{{- else }}
        .body(Body::empty())
{{- end }}
        .unwrap();

    let response = driver.router().oneshot(request).await.unwrap();

    assert_eq!(response.status().as_u16(), {{ .ExpectedStatus }});

    let body_bytes = response.into_body().collect().await.unwrap().to_bytes();
{{- if .HasExpectedBody }}
    let got: serde_json::Value = serde_json::from_slice(&body_bytes).expect("a JSON body");
    let want: serde_json::Value = serde_json::from_str({{ .ExpectedBodyLiteral }}).expect("expectedBody is valid JSON");
    assert_eq!(got, want);
{{- end }}
{{- if .HasExpectedSubstring }}
    let got: serde_json::Value = serde_json::from_slice(&body_bytes).expect("a JSON body");
    let message = got.get("message").and_then(|m| m.as_str()).unwrap_or_default();
    assert!(message.contains({{ .ExpectedSubstringLiteral }}), "message {:?} lacks {:?}", message, {{ .ExpectedSubstringLiteral }});
{{- end }}
}
{{ end -}}
{{ end -}}
`))
