// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package vectorsrust

import (
	"bytes"
	"fmt"
	"path"
	"regexp"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/restrust"
	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/udprust"
	"github.com/alexandremahdhaoui/forge-dev-codegen/pkg/rustname"
)

const header = "// Code generated by vectors-rust (forge-dev-codegen). DO NOT EDIT."

type Options struct {
	Service   string
	CrateDir  string
	Cell      string
	RestCell  string
	GrpcCell  string
	Proto     []byte
	GrpcProto []byte
	Hello     string
	Push      []string
	Rng       *RngPort
}

type RngPort struct {
	Trait   string
	Module  string
	Method  string
	Returns string
}

type rngPort = RngPort

func checkRng(rng *RngPort) error {
	if rng == nil {
		return nil
	}

	if rng.Trait == "" || rng.Module == "" || rng.Method == "" || rng.Returns == "" {
		return fmt.Errorf("reading layout.rng: it names the rng port, so it needs trait, module, method and returns, got %+v", *rng)
	}

	return nil
}

type File struct {
	Path    string
	Content string
}

var serviceIdent = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

func Generate(openapiDoc, vectorsDoc []byte, opts Options) ([]File, error) {
	if opts.Service == "" {
		return nil, fmt.Errorf("emitting the vectors: the service name is required")
	}

	if !serviceIdent.MatchString(rustname.Snake(opts.Service)) {
		return nil, fmt.Errorf("emitting the vectors: service name %q is not one Rust or Cargo can spell, use letters, digits and underscores and start with a letter", opts.Service)
	}

	if opts.Cell == "" {
		opts.Cell = udprust.DefaultCell
	}

	if opts.RestCell == "" {
		opts.RestCell = restrust.DefaultCell
	}

	if !rustname.IsModuleName(opts.RestCell) {
		return nil, fmt.Errorf("emitting the vectors: rest cell %q is not a name Rust can spell as a module, use lowercase letters, digits and underscores and start with a letter", opts.RestCell)
	}

	if err := checkRng(opts.Rng); err != nil {
		return nil, err
	}

	spec, err := restrust.Parse(openapiDoc)
	if err != nil {
		return nil, err
	}

	datagrams, err := readDatagramService(opts.Proto, opts.Cell, opts.Hello, opts.Push)
	if err != nil {
		return nil, err
	}

	calls, err := readCallService(opts.GrpcProto, opts.GrpcCell)
	if err != nil {
		return nil, err
	}

	vectors, err := parseVectors(vectorsDoc, declared{
		operation: declaredOperations(spec),
		datagram:  declaredDatagrams(datagrams),
		grpc:      declaredCalls(calls),
		rng:       opts.Rng,
	})
	if err != nil {
		return nil, err
	}

	v, err := buildView(spec, vectors, datagrams, calls, opts.Rng, opts)
	if err != nil {
		return nil, err
	}

	content, err := render("file", v)
	if err != nil {
		return nil, err
	}

	return []File{
		{
			Path:    path.Join(opts.CrateDir, "tests", "zz_generated_vectors.rs"),
			Content: content,
		},
	}, nil
}

func declaredOperations(spec *restrust.Spec) func(string) bool {
	declared := map[string]bool{}

	for _, c := range spec.Controllers {
		for _, op := range c.Operations {
			declared[op.ID] = true
		}
	}

	return func(id string) bool { return declared[id] }
}

func declaredDatagrams(svc *datagramService) func(string) bool {
	if svc == nil {
		return func(string) bool { return false }
	}

	return func(operation string) bool {
		_, ok := svc.Rpcs[operation]

		return ok
	}
}

func declaredCalls(svc *callService) func(string) bool {
	if svc == nil {
		return func(string) bool { return false }
	}

	return func(operation string) bool {
		_, ok := svc.Rpcs[operation]

		return ok
	}
}

func render(name string, data any) (string, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", fmt.Errorf("rendering %s: %w", name, err)
	}

	return buf.String(), nil
}

var templates = template.Must(template.New("vectorsrust").Parse(`
{{- define "file" -}}
{{ .Header }}

use axum::body::Body;
use axum::http::Request;
use http_body_util::BodyExt;
use tower::ServiceExt;

use {{ .Crate }}::{{ .RestCell }}::driver::http_driver::{HttpDriver, HttpDriverConfig};
{{ range .Controllers -}}
use {{ $.Crate }}::{{ $.RestCell }}::controller::{{ .Pascal }}ControllerError;
{{ end -}}
{{ if .Auth -}}
use {{ .Crate }}::port::ticket_verifier::TicketVerifierError;
use {{ .Crate }}::types::subject::Subject;
{{ end -}}
{{ range .TypeImports -}}
use {{ $.Crate }}::{{ $.RestCell }}::types::{{ .Snake }}::{{ .Name }};
{{ end }}
{{- if .HasDatagrams }}
{{- if .HasPush }}
use {{ .Crate }}::{{ .Datagram.Cell }}::adapter::{{ .Datagram.Snake }}_udp_broadcast::{{ "{" }}{{ .Datagram.BroadcastStruct }}, {{ .Datagram.BroadcastConfig }}{{ "}" }};
{{- end }}
use {{ .Crate }}::{{ .Datagram.Cell }}::adapter::{{ .Datagram.Snake }}_udp_client::{{ "{" }}{{ .Datagram.ClientStruct }}, {{ .Datagram.ClientStruct }}Config{{ "}" }};
{{- if .Datagram.Session }}
use {{ .Crate }}::{{ .Datagram.Cell }}::adapter::{{ .Datagram.Snake }}_udp_peer_table::{{ "{" }}{{ .Datagram.PeerTableStruct }}, {{ .Datagram.PeerTableConfig }}{{ "}" }};
{{- end }}
{{- if or .NeedsRegister .HasReconnect }}
use {{ .Crate }}::{{ .Datagram.Cell }}::controller::{{ .Datagram.Snake }}_codec as {{ .Datagram.Snake }}_codec;
{{- end }}
use {{ .Crate }}::{{ .Datagram.Cell }}::controller::{{ .Datagram.Pascal }}ControllerError;
{{- if .HasPush }}
use {{ .Crate }}::{{ .Datagram.Cell }}::driver::{{ .Datagram.Snake }}_tick_driver::{{ "{" }}{{ .Datagram.TickStruct }}, {{ .Datagram.TickConfig }}{{ "}" }};
{{- end }}
use {{ .Crate }}::{{ .Datagram.Cell }}::driver::{{ .Datagram.Snake }}_udp_driver::{{ "{" }}{{ .Datagram.DriverStruct }}, {{ .Datagram.DriverStruct }}Config{{ "}" }};
{{- if .HasPush }}
use {{ .Crate }}::{{ .Datagram.Cell }}::port::{{ .Datagram.Snake }}_broadcast::{{ .Datagram.Pascal }}Broadcast;
{{- end }}
use {{ .Crate }}::{{ .Datagram.Cell }}::port::{{ .Datagram.Snake }}_client::{{ .Datagram.ClientTrait }};
{{- if .HasReconnect }}
use {{ .Crate }}::{{ .Datagram.Cell }}::port::{{ .Datagram.Snake }}_peer_table::{{ .Datagram.PeerTableTrait }};
{{- end }}
{{- if .Datagram.Session }}
use {{ .Crate }}::{{ .Datagram.Cell }}::port::{{ .Datagram.Snake }}_session_gate::{{ .Datagram.GateError }};
use {{ .Crate }}::{{ .Datagram.Cell }}::types::admission::Admission;
{{- end }}
use {{ .Crate }}::{{ .Datagram.Cell }}::types::context::Context;
use {{ .Crate }}::{{ .Datagram.Cell }}::types::{{ .Datagram.Snake }}_messages::{{ "{" }}{{ range $i, $t := .Datagram.TypeImports }}{{ if $i }}, {{ end }}{{ $t }}{{ end }}{{ "}" }};
{{- if .HasPush }}
use {{ .Crate }}::{{ .Datagram.Cell }}::types::{{ .Datagram.PushModule }}::{{ .Datagram.PushEnum }};
{{- end }}
{{ end }}
{{- if .HasCalls }}
use {{ .Crate }}::{{ .Call.Cell }}::adapter::{{ .Call.ClientModule }}::{{ "{" }}{{ .Call.ClientStruct }}, {{ .Call.ClientConfig }}{{ "}" }};
use {{ .Crate }}::{{ .Call.Cell }}::controller::{{ .Call.ControllerError }};
use {{ .Crate }}::{{ .Call.Cell }}::driver::{{ .Call.DriverModule }}::{{ "{" }}{{ .Call.DriverStruct }}, {{ .Call.DriverConfig }}{{ "}" }};
use {{ .Crate }}::{{ .Call.Cell }}::port::{{ .Call.ClientPortMod }}::{{ .Call.ClientTrait }};
use {{ .Crate }}::{{ .Call.Cell }}::types::{{ .Call.TypesModule }} as {{ .Call.TypesAlias }};
{{ end }}
{{- if or .HasDatagrams .HasCalls }}
fn error_chain(error: &dyn std::error::Error) -> String {
    let mut parts = vec![error.to_string()];
    let mut source = error.source();

    while let Some(current) = source {
        parts.push(current.to_string());
        source = current.source();
    }

    parts.join(": ")
}
{{ end }}
{{- if .NeedsBodyMatcher }}
const UUID_PLACEHOLDER: &str = "<uuid>";
const ID_KEY: &str = "id";

fn body_matches(expected: &serde_json::Value, actual: &serde_json::Value) -> bool {
    let (Some(expected_fields), Some(actual_fields)) = (expected.as_object(), actual.as_object())
    else {
        return expected == actual;
    };

    expected_fields
        .iter()
        .all(|(key, value)| field_matches(key, value, actual_fields.get(key)))
}

fn field_matches(
    key: &str,
    expected: &serde_json::Value,
    actual: Option<&serde_json::Value>,
) -> bool {
    let Some(actual) = actual else {
        return false;
    };

    if key == ID_KEY && expected.as_str() == Some(UUID_PLACEHOLDER) {
        return actual.as_str().is_some_and(is_uuid_v4);
    }

    expected == actual
}

fn is_uuid_v4(value: &str) -> bool {
    let bytes = value.as_bytes();

    if bytes.len() != 36 {
        return false;
    }

    let shaped = bytes.iter().enumerate().all(|(index, byte)| {
        if matches!(index, 8 | 13 | 18 | 23) {
            *byte == b'-'
        } else {
            byte.is_ascii_hexdigit()
        }
    });

    shaped && bytes[14] == b'4' && matches!(bytes[19], b'8' | b'9' | b'a' | b'A' | b'b' | b'B')
}
{{ end }}
{{- if .HasStream }}
fn first_event(body: &[u8]) -> serde_json::Value {
    let text = String::from_utf8_lossy(body);

    let data = text
        .lines()
        .find_map(|line| line.strip_prefix("data:"))
        .expect("an event stream carries one data line");

    serde_json::from_str(data.trim_start()).expect("the event data is JSON")
}
{{ end }}
{{ range .Controllers }}{{ $c := . }}
mockall::mock! {
    pub {{ $c.Pascal }}Controller {}
    impl {{ $.Crate }}::{{ $.RestCell }}::controller::{{ $c.Pascal }}Controller for {{ $c.Pascal }}Controller {
{{- range $c.Ops }}
        fn {{ .Ident }}(&self{{ if .TraitArgs }}, {{ .TraitArgs }}{{ end }}) -> Result<{{ .ReturnType }}, {{ $c.Pascal }}ControllerError>;
{{- end }}
    }
}
{{ end }}
{{- if .Auth }}
mockall::mock! {
    pub TicketVerifier {}
    impl {{ .Crate }}::port::ticket_verifier::TicketVerifier for TicketVerifier {
        fn verify(&self, token: &str) -> Result<Subject, TicketVerifierError>;
    }
}
{{ end }}
{{- if .HasDatagrams }}
mockall::mock! {
    pub {{ .Datagram.Pascal }}Controller {}
    impl {{ .Crate }}::{{ .Datagram.Cell }}::controller::{{ .Datagram.Pascal }}Controller for {{ .Datagram.Pascal }}Controller {
{{- range .Datagram.Ops }}
        fn {{ .Ident }}(&self, request: {{ .Request }}, context: &Context) -> Result<{{ .Reply }}, {{ $.Datagram.Pascal }}ControllerError>;
{{- end }}
{{- if .Datagram.Session }}
        fn on_tick(&self) -> Result<(), {{ .Datagram.Pascal }}ControllerError>;
{{- end }}
    }
}
{{ end }}
{{- if .HasCalls }}
mockall::mock! {
    pub {{ .Call.ControllerTrait }} {}
    impl {{ .Crate }}::{{ .Call.Cell }}::controller::{{ .Call.ControllerTrait }} for {{ .Call.ControllerTrait }} {
{{- range .Call.Ops }}
        fn {{ .Ident }}(&self, request: {{ .Request }}) -> Result<{{ .Reply }}, {{ $.Call.ControllerError }}>;
{{- end }}
    }
}
{{ end }}
{{- if .HasRng }}
mockall::mock! {
    pub {{ .Rng.Trait }} {}
    impl {{ .Crate }}::{{ .Rng.Module }}::{{ .Rng.Trait }} for {{ .Rng.Trait }} {
        fn {{ .Rng.Method }}(&self) -> {{ .Rng.Returns }};
    }
}

#[allow(dead_code)]
fn {{ .Rng.Builder }}(seed: {{ .Rng.Returns }}) -> Mock{{ .Rng.Trait }} {
    let mut rng = Mock{{ .Rng.Trait }}::new();
    rng.expect_{{ .Rng.Method }}().returning(move || seed);

    rng
}
{{ end }}
{{- if and .HasDatagrams .Datagram.Session }}
mockall::mock! {
    pub {{ .Datagram.GateTrait }} {}
    impl {{ .Crate }}::{{ .Datagram.Cell }}::port::{{ .Datagram.Snake }}_session_gate::{{ .Datagram.GateTrait }} for {{ .Datagram.GateTrait }} {
        fn admit(&self, session_id: &[u8; 16], request: &{{ .Datagram.HelloRequest }}, peer: std::net::SocketAddr) -> Result<Admission, {{ .Datagram.GateError }}>;
    }
}

#[allow(dead_code)]
struct {{ .Datagram.Pascal }}Stack {
    port: u16,
    peer_table: std::sync::Arc<{{ .Datagram.PeerTableStruct }}>,
    controller: std::sync::Arc<Mock{{ .Datagram.Pascal }}Controller>,
}

fn {{ .Datagram.Snake }}_gate(admits: bool) -> Mock{{ .Datagram.GateTrait }} {
    let mut gate = Mock{{ .Datagram.GateTrait }}::new();
    gate.expect_admit().returning(move |_session_id, _request, _peer| {
        if admits {
            return Ok(Admission::Admitted);
        }

        Ok(Admission::Refused {
            reason: "refused by vectors-rust".to_string(),
        })
    });

    gate
}

fn {{ .Datagram.Snake }}_peer_table() -> std::sync::Arc<{{ .Datagram.PeerTableStruct }}> {
    std::sync::Arc::new(
        {{ .Datagram.PeerTableStruct }}::new({{ .Datagram.PeerTableConfig }} { max_sessions: 64 })
            .expect("a peer table"),
    )
}

async fn stand_up_{{ .Datagram.Snake }}(
    controller: Mock{{ .Datagram.Pascal }}Controller,
    gate: Mock{{ .Datagram.GateTrait }},
    peer_table: std::sync::Arc<{{ .Datagram.PeerTableStruct }}>,
) -> {{ .Datagram.Pascal }}Stack {
    let controller = std::sync::Arc::new(controller);

    let mut driver = {{ .Datagram.DriverStruct }}::new(
        {{ .Datagram.DriverStruct }}Config {
            addr: "127.0.0.1:0".to_string(),
        },
        controller.clone(),
        std::sync::Arc::new(gate),
        peer_table.clone(),
    );

    driver.bind().await.expect("a bound udp socket");

    let port = driver.local_port().expect("a bound udp port");

    tokio::spawn(async move {
        if let Err(error) = driver.serve().await {
            eprintln!("serving {{ .Datagram.DriverStruct }}: {}", error_chain(&error));
        }
    });

    {{ .Datagram.Pascal }}Stack {
        port,
        peer_table,
        controller,
    }
}

{{- if .NeedsRegister }}
async fn register_{{ .Datagram.Snake }}(
    port: u16,
    session_id: &str,
    hello: {{ .Datagram.HelloRequest }},
) -> (tokio::net::UdpSocket, {{ .Datagram.HelloReply }}) {
    let session = {{ .Datagram.Snake }}_codec::session_id_from(session_id);

    let socket = tokio::net::UdpSocket::bind("127.0.0.1:0")
        .await
        .expect("a bound socket");

    let datagram = {{ .Datagram.Snake }}_codec::encode_{{ .Datagram.HelloIdent }}_request(&session, &hello)
        .expect("a hello datagram");

    socket
        .send_to(&datagram, format!("127.0.0.1:{port}"))
        .await
        .expect("a sent hello");
{{- if .Datagram.HelloSilent }}

    tokio::time::sleep(std::time::Duration::from_millis(50)).await;

    (socket, {{ .Datagram.HelloReply }}::default())
{{- else }}

    let mut buffer = [0u8; {{ .Datagram.Snake }}_codec::MAX_DATAGRAM_LEN + 1];

    let read = tokio::time::timeout(
        std::time::Duration::from_millis(2000),
        socket.recv(&mut buffer),
    )
    .await
    .expect("a hello reply in time")
    .expect("a hello reply");

    let reply = {{ .Datagram.Snake }}_codec::decode_{{ .Datagram.HelloIdent }}_reply(&session, &buffer[..read])
        .expect("a decoded hello reply");

    (socket, reply)
{{- end }}
}
{{- end }}
{{- if .HasPush }}

#[allow(dead_code)]
async fn drain_{{ .Datagram.Snake }}(
    socket: &tokio::net::UdpSocket,
    session_id: &str,
    timeout_ms: u64,
    wants_answer: bool,
) -> (Option<{{ .Datagram.PushEnum }}>, Option<Vec<u8>>) {
    let session = {{ .Datagram.Snake }}_codec::session_id_from(session_id);
    let deadline = tokio::time::Instant::now() + std::time::Duration::from_millis(timeout_ms);

    let mut buffer = [0u8; {{ .Datagram.Snake }}_codec::MAX_DATAGRAM_LEN + 1];
    let mut push = None;
    let mut answer = None;

    while push.is_none() || (wants_answer && answer.is_none()) {
        let Ok(Ok(read)) = tokio::time::timeout_at(deadline, socket.recv(&mut buffer)).await else {
            break;
        };

        match {{ .Datagram.Snake }}_codec::decode_push(&session, &buffer[..read]) {
            Ok(decoded) => push = Some(decoded),
            Err(_) => answer = Some(buffer[..read].to_vec()),
        }
    }

    (push, answer)
}

async fn receive_{{ .Datagram.Snake }}_push(
    socket: &tokio::net::UdpSocket,
    session_id: &str,
    timeout_ms: u64,
) -> Option<{{ .Datagram.PushEnum }}> {
    drain_{{ .Datagram.Snake }}(socket, session_id, timeout_ms, false)
        .await
        .0
}
{{- end }}
{{ end }}
{{ range .DatagramTests }}
{{- if eq .Kind "push" }}
{{- $t := . }}
#[tokio::test]
async fn {{ .Name }}() {
    let peer_table = {{ .ServiceSnake }}_peer_table();
    let pushing = {{ .ServicePascal }}UdpBroadcast::new({{ .ServicePascal }}UdpBroadcastConfig {}, peer_table.clone());

{{- if .Seeded }}
    let rng = {{ $.Rng.Builder }}({{ .SeedLiteral }});
{{- end }}

    let mut {{ .ControllerVar }} = Mock{{ .ServicePascal }}Controller::new();
    {{ .ControllerVar }}
        .expect_{{ .HelloIdent }}()
        .returning(|_request, _context| Ok({{ .HelloReply }}::default()));
    {{ .ControllerVar }}
        .expect_on_tick()
        .returning(move || {
{{- if .Seeded }}
            let {{ $.DrawIdent }} = {{ $.Crate }}::{{ $.Rng.Module }}::{{ $.Rng.Trait }}::{{ $.Rng.Method }}(&rng);
{{ end }}
            pushing
                .send_all({{ .PushEnum }}::{{ .PushVariant }}({{ .PushLiteral }}))
                .map(|_reached| ())
                .map_err(|source| {{ .ControllerError }}::Broadcast {
                    kind: "{{ .PushVariant }}".to_string(),
                    source,
                })
        });

    let stack = stand_up_{{ .ServiceSnake }}({{ .ControllerVar }}, {{ .ServiceSnake }}_gate(true), peer_table).await;

    let peers = vec![
{{- range .SessionLiterals }}
        ({{ . }}, register_{{ $t.ServiceSnake }}(stack.port, {{ . }}, {{ $t.HelloLiteral }}).await.0),
{{- end }}
    ];

    let mut tick = {{ .ServicePascal }}TickDriver::new(
        {{ .ServicePascal }}TickDriverConfig {
            interval_ms: {{ .TickIntervalMs }},
        },
        stack.controller.clone(),
        stack.peer_table.clone(),
    );

    tick.bind().await.expect("a bound tick interval");

    tokio::spawn(async move {
        if let Err(error) = tick.serve().await {
            eprintln!("serving {{ .ServicePascal }}TickDriver: {}", error_chain(&error));
        }
    });

    for (session_id, socket) in &peers {
        let push = receive_{{ .ServiceSnake }}_push(socket, session_id, {{ .TimeoutMs }}).await;

        assert_eq!(push, Some({{ .PushEnum }}::{{ .PushVariant }}({{ .ExpectedPushLiteral }})), "session {session_id} never received the push");
    }
}
{{- else if eq .Kind "request_push" }}
{{- $t := . }}
#[tokio::test]
async fn {{ .Name }}() {
    let peer_table = {{ .ServiceSnake }}_peer_table();
    let pushing = {{ .ServicePascal }}UdpBroadcast::new({{ .ServicePascal }}UdpBroadcastConfig {}, peer_table.clone());
{{- if .Seeded }}
    let rng = {{ $.Rng.Builder }}({{ .SeedLiteral }});
{{- end }}

    let expected_request = {{ .RequestLiteral }};
    let controller_reply = {{ .ReplyLiteral }};

    let mut {{ .ControllerVar }} = Mock{{ .ServicePascal }}Controller::new();
    {{ .ControllerVar }}
        .expect_{{ .HelloIdent }}()
        .returning(|_request, _context| Ok({{ .HelloReply }}::default()));
    {{ .ControllerVar }}
        .{{ .ExpectMethod }}()
        .times(1)
        .returning(move |request, _context| {
            assert_eq!(request, expected_request);
{{ if .Seeded }}
            let {{ $.DrawIdent }} = {{ $.Crate }}::{{ $.Rng.Module }}::{{ $.Rng.Trait }}::{{ $.Rng.Method }}(&rng);
{{ end }}
            pushing
                .send_all({{ .PushEnum }}::{{ .PushVariant }}({{ .PushLiteral }}))
                .map_err(|source| {{ .ControllerError }}::Broadcast {
                    kind: "{{ .PushVariant }}".to_string(),
                    source,
                })?;

            Ok(controller_reply.clone())
        });

    let stack = stand_up_{{ .ServiceSnake }}({{ .ControllerVar }}, {{ .ServiceSnake }}_gate({{ .GateAdmits }}), peer_table).await;

    let peers = vec![
{{- range .SessionLiterals }}
        ({{ . }}, register_{{ $t.ServiceSnake }}(stack.port, {{ . }}, {{ $t.HelloLiteral }}).await.0),
{{- end }}
    ];
{{ if lt .AskingIndex 0 }}
    let asking_socket = register_{{ .ServiceSnake }}(stack.port, {{ .SessionLiteral }}, {{ .HelloLiteral }}).await.0;
    let asking = &asking_socket;
{{- else }}
    let asking = &peers[{{ .AskingIndex }}].1;
{{- end }}

    let datagram = {{ .ServiceSnake }}_codec::encode_{{ .ClientMethod }}_request(
        &{{ .ServiceSnake }}_codec::session_id_from({{ .SessionLiteral }}),
        &{{ .RequestLiteral }},
    )
    .expect("a request datagram");

    asking
        .send_to(&datagram, format!("127.0.0.1:{}", stack.port))
        .await
        .expect("a sent request");

    let (asked_push, answer) = drain_{{ .ServiceSnake }}(asking, {{ .SessionLiteral }}, {{ .TimeoutMs }}, {{ if .Silent }}false{{ else }}true{{ end }}).await;

    assert_eq!(
        asked_push,
        Some({{ .PushEnum }}::{{ .PushVariant }}({{ .ExpectedPushLiteral }})),
        "the asking session never received the push"
    );
{{- if not .Silent }}

    let reply = {{ .ServiceSnake }}_codec::decode_{{ .ClientMethod }}_reply(
        &{{ .ServiceSnake }}_codec::session_id_from({{ .SessionLiteral }}),
        &answer.expect("a reply"),
    )
    .expect("a decoded reply");

    assert_eq!(reply, {{ .ExpectedLiteral }});
{{- else }}

    assert!(answer.is_none(), "{{ .RpcPascal }} answers Nothing and the driver still sent a reply");
{{- end }}

    for (session_id, socket) in &peers {
{{- if ge .AskingIndex 0 }}
        if *session_id == {{ .SessionLiteral }} {
            continue;
        }
{{ end }}
        let push = receive_{{ .ServiceSnake }}_push(socket, session_id, {{ .TimeoutMs }}).await;

        assert_eq!(push, Some({{ .PushEnum }}::{{ .PushVariant }}({{ .ExpectedPushLiteral }})), "session {session_id} never received the push");
    }
}
{{- else if eq .Kind "dropped" }}
#[tokio::test]
async fn {{ .Name }}() {
    let mut {{ .ControllerVar }} = Mock{{ .ServicePascal }}Controller::new();
    {{ .ControllerVar }}.{{ .ExpectMethod }}().never();
{{- if and .Registered (not .IsHello) }}
    {{ .ControllerVar }}
        .expect_{{ .HelloIdent }}()
        .returning(|_request, _context| Ok({{ .HelloReply }}::default()));
{{- end }}

    let stack = stand_up_{{ .ServiceSnake }}({{ .ControllerVar }}, {{ .ServiceSnake }}_gate({{ .GateAdmits }}), {{ .ServiceSnake }}_peer_table()).await;
{{- if and .Registered (not .IsHello) }}

    let _registered = register_{{ .ServiceSnake }}(stack.port, {{ .SessionLiteral }}, {{ .HelloLiteral }}).await;
{{- end }}

    let client = {{ .ClientStruct }}::new({{ .ClientConfig }} {
        address: format!("127.0.0.1:{}", stack.port),
        session_id: {{ .SessionLiteral }}.to_string(),
        timeout_ms: {{ .TimeoutMs }},
    });

    let error = client
        .{{ .ClientMethod }}({{ .RequestLiteral }})
        .await
        .expect_err("the datagram is dropped, no reply comes back");

    assert!(error.to_string().contains("{{ .RpcPascal }}"), "{error}");
}
{{- else if eq .Kind "reconnect" }}
#[tokio::test]
async fn {{ .Name }}() {
    let expected_request = {{ .RequestLiteral }};
    let controller_reply = {{ .ReplyLiteral }};

    let mut {{ .ControllerVar }} = Mock{{ .ServicePascal }}Controller::new();
    {{ .ControllerVar }}
        .{{ .ExpectMethod }}()
        .times(2)
        .returning(move |request, _context| {
            assert_eq!(request, expected_request);

            Ok(controller_reply.clone())
        });

    let stack = stand_up_{{ .ServiceSnake }}({{ .ControllerVar }}, {{ .ServiceSnake }}_gate({{ .GateAdmits }}), {{ .ServiceSnake }}_peer_table()).await;

    let (first, _) = register_{{ .ServiceSnake }}(stack.port, {{ .SessionLiteral }}, {{ .RequestLiteral }}).await;
    let (second, reply) = register_{{ .ServiceSnake }}(stack.port, {{ .SessionLiteral }}, {{ .RequestLiteral }}).await;

    assert_eq!(reply, {{ .ExpectedLiteral }});

    let first_address = first.local_addr().expect("the first address");
    let second_address = second.local_addr().expect("the second address");

    assert_ne!(first_address, second_address);
    assert_eq!(
        stack
            .peer_table
            .peer_of(&{{ .ServiceSnake }}_codec::session_id_from({{ .SessionLiteral }}))
            .expect("a peer"),
        Some(second_address),
        "the peer table still points at the first address"
    );
}
{{- else if .Session }}
#[tokio::test]
async fn {{ .Name }}() {
    let expected_request = {{ .RequestLiteral }};
    let controller_reply = {{ .ReplyLiteral }};

    let mut {{ .ControllerVar }} = Mock{{ .ServicePascal }}Controller::new();
    {{ .ControllerVar }}
        .{{ .ExpectMethod }}()
        .times(1)
        .returning(move |request, _context| {
            assert_eq!(request, expected_request);

            Ok(controller_reply.clone())
        });
{{- if and .Registered (not .IsHello) }}
    {{ .ControllerVar }}
        .expect_{{ .HelloIdent }}()
        .returning(|_request, _context| Ok({{ .HelloReply }}::default()));
{{- end }}

    let stack = stand_up_{{ .ServiceSnake }}({{ .ControllerVar }}, {{ .ServiceSnake }}_gate({{ .GateAdmits }}), {{ .ServiceSnake }}_peer_table()).await;
{{- if and .Registered (not .IsHello) }}

    let _registered = register_{{ .ServiceSnake }}(stack.port, {{ .SessionLiteral }}, {{ .HelloLiteral }}).await;
{{- end }}

    let client = {{ .ClientStruct }}::new({{ .ClientConfig }} {
        address: format!("127.0.0.1:{}", stack.port),
        session_id: {{ .SessionLiteral }}.to_string(),
        timeout_ms: {{ .TimeoutMs }},
    });

    let reply = client
        .{{ .ClientMethod }}({{ .RequestLiteral }})
        .await
        .expect("a reply");

    assert_eq!(reply, {{ .ExpectedLiteral }});
}
{{- else }}
#[tokio::test]
async fn {{ .Name }}() {
    let expected_request = {{ .RequestLiteral }};
    let controller_reply = {{ .ReplyLiteral }};

    let mut {{ .ControllerVar }} = Mock{{ .ServicePascal }}Controller::new();
    {{ .ControllerVar }}
        .{{ .ExpectMethod }}()
        .times(1)
        .returning(move |request, _context| {
            assert_eq!(request, expected_request);

            Ok(controller_reply.clone())
        });

    let mut driver = {{ .DriverStruct }}::new(
        {{ .DriverConfig }} {
            addr: "127.0.0.1:0".to_string(),
        },
        std::sync::Arc::new({{ .ControllerVar }}),
    );

    driver.bind().await.expect("a bound udp socket");

    let port = driver.local_port().expect("a bound udp port");

    tokio::spawn(async move {
        if let Err(error) = driver.serve().await {
            eprintln!("serving {{ .DriverStruct }}: {}", error_chain(&error));
        }
    });

    let client = {{ .ClientStruct }}::new({{ .ClientConfig }} {
        address: format!("127.0.0.1:{port}"),
        session_id: {{ .SessionLiteral }}.to_string(),
        timeout_ms: {{ .TimeoutMs }},
    });

    let reply = client
        .{{ .ClientMethod }}({{ .RequestLiteral }})
        .await
        .expect("a reply");

    assert_eq!(reply, {{ .ExpectedLiteral }});
}
{{- end }}
{{ end }}
{{ range .CallTests }}
#[tokio::test(flavor = "multi_thread")]
async fn {{ .Name }}() {
    let expected_request = {{ .RequestLiteral }};
{{- if not .HasExpectedSubstring }}
    let controller_reply = {{ .ReplyLiteral }};
{{- end }}

    let mut {{ .ControllerVar }} = Mock{{ .ServicePascal }}Controller::new();
    {{ .ControllerVar }}
        .{{ .ExpectMethod }}()
        .times(1)
        .returning(move |request| {
            assert_eq!(request, expected_request);

            {{ .Returning }}
        });

    let mut driver = {{ .DriverStruct }}::new(
        {{ .DriverConfig }} {
            addr: "127.0.0.1:0".to_string(),
        },
        std::sync::Arc::new({{ .ControllerVar }}),
    );

    driver.bind().await.expect("a bound grpc socket");

    let port = driver.local_port().expect("a bound grpc port");

    tokio::spawn(async move {
        if let Err(error) = driver.serve().await {
            eprintln!("serving {{ .DriverStruct }}: {}", error_chain(&error));
        }
    });

    let client = {{ .ClientStruct }}::new({{ .ClientConfig }} {
        endpoint: format!("http://127.0.0.1:{port}"),
    })
    .expect("a grpc client");
{{ if .HasExpectedSubstring }}
    let error = client
        .{{ .ClientMethod }}({{ .RequestLiteral }})
        .expect_err("a refused call");

    let chain = error_chain(&error);

    assert!(chain.contains({{ .ExpectedSubstringLiteral }}), "status {chain:?} lacks {:?}", {{ .ExpectedSubstringLiteral }});
{{- else }}
    let reply = client
        .{{ .ClientMethod }}({{ .RequestLiteral }})
        .expect("a reply");

    assert_eq!(reply, {{ .ReplyLiteral }});
{{- end }}
}
{{ end }}
{{ range .Tests }}
#[tokio::test{{ if .Stream }}(flavor = "multi_thread"){{ end }}]
async fn {{ .Name }}() {
    let mut {{ .ArmVar }} = Mock{{ .ArmController }}Controller::new();
{{- if .ControllerNever }}
    {{ .ArmVar }}.{{ .ArmExpectMethod }}().never();
{{- else }}
    {{ .ArmVar }}
        .{{ .ArmExpectMethod }}()
{{- if .HasWith }}
        .with({{ .WithPredicates }})
{{- end }}
        .times(1)
        .returning(|{{ .ArmClosureParams }}| {{ .ArmReturning }});
{{- end }}
{{- if $.Auth }}

    let mut ticket_verifier = MockTicketVerifier::new();
{{- if .HasSubject }}
    ticket_verifier
        .expect_verify()
        .with(mockall::predicate::eq({{ .BearerLiteral }}))
        .returning(|_token| Ok(Subject { id: {{ .SubjectLiteral }}.to_string() }));
{{- else if .HasBearer }}
    ticket_verifier
        .expect_verify()
        .with(mockall::predicate::eq({{ .BearerLiteral }}))
        .returning(|_token| Err(TicketVerifierError::Refused { reason: {{ if .HasExpectedSubstring }}{{ .ExpectedSubstringLiteral }}{{ else }}"refused by vectors-rust"{{ end }}.to_string() }));
{{- else }}
    ticket_verifier.expect_verify().never();
{{- end }}
{{- end }}

    let driver = HttpDriver::new(HttpDriverConfig::default(){{ range .DriverArgs }}, {{ . }}{{ end }});

    let request = Request::builder()
        .method("{{ .Method }}")
        .uri("{{ .URI }}")
{{- if .HasBearer }}
        .header("authorization", format!("Bearer {}", {{ .BearerLiteral }}))
{{- end }}
{{- if .HasBody }}
        .header("content-type", "application/json")
        .body(Body::from({{ .BodyLiteral }}))
{{- else }}
        .body(Body::empty())
{{- end }}
        .unwrap();

    let response = driver.router().oneshot(request).await.unwrap();

    assert_eq!(response.status().as_u16(), {{ .ExpectedStatus }});
{{- if and .Stream (not .HasExpectedSubstring) }}
    assert_eq!(
        response.headers().get("content-type").and_then(|value| value.to_str().ok()),
        Some("text/event-stream")
    );
{{- end }}

    let body_bytes = response.into_body().collect().await.unwrap().to_bytes();
{{- if .HasExpectedBody }}
{{- if .Stream }}
    let got: serde_json::Value = first_event(&body_bytes);
{{- else }}
    let got: serde_json::Value = serde_json::from_slice(&body_bytes).expect("a JSON body");
{{- end }}
    let want: serde_json::Value = serde_json::from_str({{ .ExpectedBodyLiteral }}).expect("expectedBody is valid JSON");
    assert!(body_matches(&want, &got), "body {got} does not match {want}");
{{- end }}
{{- if .HasExpectedSubstring }}
    let got: serde_json::Value = serde_json::from_slice(&body_bytes).expect("a JSON body");
    let message = got.get("message").and_then(|m| m.as_str()).unwrap_or_default();
    assert!(message.contains({{ .ExpectedSubstringLiteral }}), "message {:?} lacks {:?}", message, {{ .ExpectedSubstringLiteral }});
{{- end }}
}
{{ end -}}
{{ end -}}
`))
