// Code generated by tui-rust (forge-dev-codegen). DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Grid {
    width: u16,
    height: u16,
    cells: Vec<char>,
}

impl Grid {
    pub fn new(width: u16, height: u16) -> Self {
        Self {
            width,
            height,
            cells: vec![' '; usize::from(width) * usize::from(height)],
        }
    }

    pub fn width(&self) -> u16 {
        self.width
    }

    pub fn height(&self) -> u16 {
        self.height
    }

    pub fn get(&self, x: u16, y: u16) -> Option<char> {
        self.index(x, y).map(|i| self.cells[i])
    }

    pub fn set(&mut self, x: u16, y: u16, glyph: char) -> bool {
        match self.index(x, y) {
            Some(i) => {
                self.cells[i] = glyph;
                true
            }
            None => false,
        }
    }

    pub fn find(&self, glyph: char) -> Option<(u16, u16)> {
        let i = self.cells.iter().position(|cell| *cell == glyph)?;
        let width = usize::from(self.width);
        let x = u16::try_from(i % width).ok()?;
        let y = u16::try_from(i / width).ok()?;
        Some((x, y))
    }

    pub fn row(&self, y: u16) -> String {
        if y >= self.height {
            return String::new();
        }

        let width = usize::from(self.width);
        let start = usize::from(y) * width;
        self.cells[start..start + width].iter().collect()
    }

    fn index(&self, x: u16, y: u16) -> Option<usize> {
        if x >= self.width || y >= self.height {
            return None;
        }

        Some(usize::from(y) * usize::from(self.width) + usize::from(x))
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Frame {
    pub grid: Grid,
    pub status: String,
    pub message: String,
}

impl Frame {
    pub fn blank(width: u16, height: u16) -> Self {
        Self {
            grid: Grid::new(width, height),
            status: String::new(),
            message: String::new(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Step {
    Render(Frame),
    Quit,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Prompt {
    Closed,
    Open(String),
}
