// Code generated by tui-rust (forge-dev-codegen). DO NOT EDIT.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Input {
    Char(char),
    Enter,
    Backspace,
    Escape,
    Up,
    Down,
    Left,
    Right,
    Interrupt,
    Other,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Key {
    Left,
    Down,
    Up,
    Right,
    Act,
    EndTurn,
    Quit,
}
