package chartgen_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"sigs.k8s.io/yaml"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/chartgen"
	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/hexrust"
	"github.com/alexandremahdhaoui/forge-dev-codegen/pkg/cellmanifest"
)

const rootForgeDev = `name: songe-hello
kind: hexagonal
version: 0.1.0
description: The hello service.
language: rust
generator: forge://github.com/alexandremahdhaoui/forge-dev-codegen/cmd/hexagonal-rust
wiring:
  specPath: ./wiring.yaml
layout:
  cells: [rest, grpc, udp]
`

const wiring = `binary: songe-hello-node
drivers:
  rest: { enabled: true }
  grpc: { enabled: true }
  udp: { enabled: true }
  tick: { enabled: true }
`

const configSpec = `# Code generated by hexagonal-rust (forge-dev-codegen). DO NOT EDIT.
components:
  schemas:
    Spec:
      properties:
        driver_rest:
          default: true
          description: Whether the rest driver starts
          type: boolean
          x-env: SONGE_HELLO_NODE_DRIVER_REST
          x-flag: driver-rest
        greeting_store_memory_capacity:
          default: 100
          description: How many greeting rows the memory store holds
          type: integer
          x-env: SONGE_HELLO_NODE_GREETING_STORE_MEMORY_CAPACITY
          x-flag: greeting-store-memory-capacity
        greeting_store_sqlite_path:
          default: ':memory:'
          description: The sqlite file the greeting store opens
          type: string
          x-env: SONGE_HELLO_NODE_GREETING_STORE_SQLITE_PATH
          x-flag: greeting-store-sqlite-path
        grpc_addr:
          default: 127.0.0.1:0
          description: The host and port the hello grpc driver binds
          type: string
          x-env: SONGE_HELLO_NODE_GRPC_ADDR
          x-flag: grpc-addr
        rest_addr:
          default: 127.0.0.1:0
          description: The host and port the http driver binds
          type: string
          x-env: SONGE_HELLO_NODE_REST_ADDR
          x-flag: rest-addr
        tick_interval_ms:
          default: 1000
          description: How many milliseconds the tick driver waits between two ticks
          type: integer
          x-env: SONGE_HELLO_NODE_TICK_INTERVAL_MS
          x-flag: tick-interval-ms
        ticket_verifier_secret_secret:
          description: The one string the ticket_verifier secret adapter accepts
          type: string
          x-env: SONGE_HELLO_NODE_TICKET_VERIFIER_SECRET_SECRET
          x-flag: ticket-verifier-secret-secret
        udp_addr:
          default: 127.0.0.1:0
          description: The host and port the hello_datagram udp driver binds
          type: string
          x-env: SONGE_HELLO_NODE_UDP_ADDR
          x-flag: udp-addr
      type: object
info:
  title: songe-hello-node config
  version: 0.1.0
openapi: 3.0.3
`

func addr(description string) map[string]cellmanifest.ConfigField {
	return map[string]cellmanifest.ConfigField{
		"addr": {Type: cellmanifest.FieldTypeString, Default: "127.0.0.1:0", Description: description},
	}
}

func manifests() map[string]cellmanifest.Manifest {
	return map[string]cellmanifest.Manifest{
		"rest": {
			Version: cellmanifest.Version, Cell: "rest", Generator: "rest-rust (forge-dev-codegen)",
			Provides: cellmanifest.Provides{Drivers: []cellmanifest.Driver{{
				Name: "rest", Type: "HttpDriver", Module: "rest::driver::http_driver",
				Protocol: cellmanifest.ProtocolTCP, Requires: []string{"GreetingController"},
				Config: addr("The host and port the http driver binds"),
			}}},
		},
		"grpc": {
			Version: cellmanifest.Version, Cell: "grpc", Generator: "grpc-rust-tonic (forge-dev-codegen)",
			BuildScript: "zz_generated_build.rs",
			Provides: cellmanifest.Provides{Drivers: []cellmanifest.Driver{{
				Name: "grpc", Type: "HelloGrpcDriver", Module: "grpc::driver::hello_grpc_driver",
				Protocol: cellmanifest.ProtocolTCP, Requires: []string{"HelloController"},
				Config: addr("The host and port the hello grpc driver binds"),
			}}},
		},
		"udp": {
			Version: cellmanifest.Version, Cell: "udp", Generator: "udp-rust (forge-dev-codegen)",
			Provides: cellmanifest.Provides{Drivers: []cellmanifest.Driver{
				{
					Name: "udp", Type: "HelloDatagramUdpDriver", Module: "udp::driver::hello_datagram_udp_driver",
					Protocol: cellmanifest.ProtocolUDP, Requires: []string{"HelloDatagramController"},
					Config: addr("The host and port the hello_datagram udp driver binds"),
				},
				{
					Name: "tick", Type: "HelloDatagramTickDriver", Module: "udp::driver::hello_datagram_tick_driver",
					Requires: []string{"HelloDatagramController"},
					Config: map[string]cellmanifest.ConfigField{
						"interval_ms": {Type: cellmanifest.FieldTypeInteger, Default: 1000},
					},
				},
			}},
		},
	}
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("creating %s: %v", filepath.Dir(path), err)
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
}

func crate(t *testing.T, cells map[string]cellmanifest.Manifest) string {
	t.Helper()

	root := t.TempDir()
	writeFile(t, filepath.Join(root, hexrust.CellConfigFile), rootForgeDev)
	writeFile(t, filepath.Join(root, "wiring.yaml"), wiring)
	writeFile(t, filepath.Join(root, "chart", "forge-dev.yaml"), "name: songe-hello\nkind: chart\n")

	for cell, m := range cells {
		writeFile(t, filepath.Join(root, "src", cell, hexrust.CellConfigFile), "name: songe-hello\nkind: "+cell+"\n")

		if err := cellmanifest.Write(filepath.Join(root, "src", cell, cellmanifest.FileName), m); err != nil {
			t.Fatalf("writing the %s manifest: %v", cell, err)
		}
	}

	return root
}

func generate(t *testing.T, root string) map[string]string {
	t.Helper()

	files, err := chartgen.Generate(chartgen.Options{
		OpenapiSpec: []byte(configSpec),
		SrcDir:      filepath.Join(root, "chart"),
	})
	if err != nil {
		t.Fatalf("emitting the chart: %v", err)
	}

	out := map[string]string{}
	for _, f := range files {
		out[f.Path] = f.Content
	}

	return out
}

func generateHello(t *testing.T) map[string]string {
	t.Helper()

	return generate(t, crate(t, manifests()))
}

func TestTheChartCarriesTheRootNameAndItsVersionAsBothChartAndAppVersion(t *testing.T) {
	files := generateHello(t)

	var chart struct {
		APIVersion  string `json:"apiVersion"`
		Name        string `json:"name"`
		Description string `json:"description"`
		Type        string `json:"type"`
		Version     string `json:"version"`
		AppVersion  string `json:"appVersion"`
	}

	if err := yaml.Unmarshal([]byte(files[chartgen.ChartFile]), &chart); err != nil {
		t.Fatalf("reading Chart.yaml: %v\n%s", err, files[chartgen.ChartFile])
	}

	if chart.APIVersion != "v2" || chart.Type != "" {
		t.Errorf("Chart.yaml = %+v", chart)
	}

	if chart.Name != "songe-hello" || chart.Description != "The hello service." {
		t.Errorf("Chart.yaml = %+v", chart)
	}

	if chart.Version != "0.1.0" || chart.AppVersion != "0.1.0" {
		t.Errorf("Chart.yaml = %+v, want version and appVersion both 0.1.0", chart)
	}
}

func TestValuesHoldOneKeyPerSpecPropertyPlusTheImageRepositoryAndNothingElse(t *testing.T) {
	files := generateHello(t)

	var values map[string]any
	if err := yaml.Unmarshal([]byte(files[chartgen.ValuesFile]), &values); err != nil {
		t.Fatalf("reading values.yaml: %v\n%s", err, files[chartgen.ValuesFile])
	}

	want := map[string]any{
		"image":                          map[string]any{"repository": "songe-hello-node"},
		"driver_rest":                    true,
		"greeting_store_memory_capacity": float64(100),
		"greeting_store_sqlite_path":     ":memory:",
		"grpc_addr":                      "127.0.0.1:0",
		"rest_addr":                      "127.0.0.1:0",
		"tick_interval_ms":               float64(1000),
		"ticket_verifier_secret_secret":  "",
		"udp_addr":                       "127.0.0.1:0",
	}

	if len(values) != len(want) {
		t.Fatalf("values.yaml has keys %v, want %v", keys(values), keys(want))
	}

	for key, value := range want {
		if image, ok := value.(map[string]any); ok {
			got, _ := values[key].(map[string]any)
			if got["repository"] != image["repository"] || len(got) != 1 {
				t.Errorf("image = %v, want %v", values[key], image)
			}

			continue
		}

		if values[key] != value {
			t.Errorf("values.%s = %v (%T), want %v (%T)", key, values[key], values[key], value, value)
		}
	}

	if !strings.HasPrefix(strings.SplitN(files[chartgen.ValuesFile], "\n", 2)[1], "image:\n  repository: songe-hello-node\n") {
		t.Errorf("values.yaml does not start with the image block\n%s", files[chartgen.ValuesFile])
	}
}

func keys(m map[string]any) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}

	return out
}

func TestAPropertyWithNoDefaultIsAnEmptyString(t *testing.T) {
	files := generateHello(t)

	if !strings.Contains(files[chartgen.ValuesFile], "\nticket_verifier_secret_secret: \"\"\n") {
		t.Errorf("values.yaml does not spell the empty default\n%s", files[chartgen.ValuesFile])
	}
}

func TestTheDeploymentEnvNamesEveryPropertyByItsEnvInSortedOrder(t *testing.T) {
	files := generateHello(t)
	deployment := files[chartgen.DeploymentFile]

	wantInOrder := []string{
		"- name: SONGE_HELLO_NODE_DRIVER_REST\n              value: {{ .Values.driver_rest | quote }}",
		"- name: SONGE_HELLO_NODE_GREETING_STORE_MEMORY_CAPACITY\n              value: {{ .Values.greeting_store_memory_capacity | quote }}",
		"- name: SONGE_HELLO_NODE_GREETING_STORE_SQLITE_PATH\n              value: {{ .Values.greeting_store_sqlite_path | quote }}",
		"- name: SONGE_HELLO_NODE_GRPC_ADDR\n              value: {{ .Values.grpc_addr | quote }}",
		"- name: SONGE_HELLO_NODE_REST_ADDR\n              value: {{ .Values.rest_addr | quote }}",
		"- name: SONGE_HELLO_NODE_TICK_INTERVAL_MS\n              value: {{ .Values.tick_interval_ms | quote }}",
		"- name: SONGE_HELLO_NODE_TICKET_VERIFIER_SECRET_SECRET\n              value: {{ .Values.ticket_verifier_secret_secret | quote }}",
		"- name: SONGE_HELLO_NODE_UDP_ADDR\n              value: {{ .Values.udp_addr | quote }}",
	}

	last := -1
	for _, want := range wantInOrder {
		at := strings.Index(deployment, want)
		if at < 0 {
			t.Fatalf("the deployment lacks %q\n%s", want, deployment)
		}

		if at < last {
			t.Fatalf("the env entry %q is out of sorted order\n%s", want, deployment)
		}

		last = at
	}

	if strings.Count(deployment, "- name: SONGE_HELLO_NODE_") != len(wantInOrder) {
		t.Errorf("the deployment carries an env entry no property declares\n%s", deployment)
	}

	if !strings.Contains(deployment, "- name: songe-hello-node\n          image: \"{{ .Values.image.repository }}:{{ .Chart.AppVersion }}\"") {
		t.Errorf("the container is not named after the binary with the chart app version as its tag\n%s", deployment)
	}
}

func TestRestAndGrpcGetTcpPortsUdpGetsAUdpPortAndTickGetsNone(t *testing.T) {
	files := generateHello(t)
	deployment, service := files[chartgen.DeploymentFile], files[chartgen.ServiceFile]

	for _, want := range []string{
		"- name: rest\n              containerPort: {{ .Values.rest_addr | splitList \":\" | last | int }}\n              protocol: TCP",
		"- name: grpc\n              containerPort: {{ .Values.grpc_addr | splitList \":\" | last | int }}\n              protocol: TCP",
		"- name: udp\n              containerPort: {{ .Values.udp_addr | splitList \":\" | last | int }}\n              protocol: UDP",
	} {
		if !strings.Contains(deployment, want) {
			t.Errorf("the deployment lacks %q\n%s", want, deployment)
		}
	}

	for _, want := range []string{
		"- name: rest\n      protocol: TCP\n      port: {{ .Values.rest_addr | splitList \":\" | last | int }}\n      targetPort: {{ .Values.rest_addr | splitList \":\" | last | int }}",
		"- name: grpc\n      protocol: TCP\n      port: {{ .Values.grpc_addr | splitList \":\" | last | int }}",
		"- name: udp\n      protocol: UDP\n      port: {{ .Values.udp_addr | splitList \":\" | last | int }}",
	} {
		if !strings.Contains(service, want) {
			t.Errorf("the service lacks %q\n%s", want, service)
		}
	}

	if strings.Contains(deployment, "name: tick\n") || strings.Contains(service, "name: tick\n") {
		t.Errorf("the tick driver got a port and it listens on nothing\n%s\n%s", deployment, service)
	}

	if strings.Count(deployment, "containerPort:") != 3 || strings.Count(service, "targetPort:") != 3 {
		t.Errorf("want exactly three ports\n%s\n%s", deployment, service)
	}
}

func TestEveryObjectCarriesTheAppNameLabelAndTheServiceSelectsOnIt(t *testing.T) {
	files := generateHello(t)

	label := "app.kubernetes.io/name: {{ .Chart.Name }}"

	if strings.Count(files[chartgen.DeploymentFile], label) != 3 {
		t.Errorf("the deployment carries the label on metadata, selector and pod template\n%s", files[chartgen.DeploymentFile])
	}

	if strings.Count(files[chartgen.ServiceFile], label) != 2 {
		t.Errorf("the service carries the label on metadata and selector\n%s", files[chartgen.ServiceFile])
	}

	if strings.Contains(files[chartgen.DeploymentFile], "app.kubernetes.io/instance") {
		t.Errorf("the deployment carries a label the contract does not name")
	}
}

func TestWhenNoDriverCarriesAProtocolThereIsNoServiceFileAndNoPorts(t *testing.T) {
	cells := manifests()
	udp := cells["udp"]
	udp.Provides.Drivers = udp.Provides.Drivers[1:]
	delete(cells, "rest")
	delete(cells, "grpc")

	root := t.TempDir()
	writeFile(t, filepath.Join(root, hexrust.CellConfigFile), strings.Replace(rootForgeDev, "[rest, grpc, udp]", "[udp]", 1))
	writeFile(t, filepath.Join(root, "wiring.yaml"), wiring)
	writeFile(t, filepath.Join(root, "src", "udp", hexrust.CellConfigFile), "name: songe-hello\nkind: udp\n")

	if err := cellmanifest.Write(filepath.Join(root, "src", "udp", cellmanifest.FileName), udp); err != nil {
		t.Fatalf("writing the udp manifest: %v", err)
	}

	files := generate(t, root)

	if _, ok := files[chartgen.ServiceFile]; ok {
		t.Errorf("a service was emitted with no driver listening\n%s", files[chartgen.ServiceFile])
	}

	if strings.Contains(files[chartgen.DeploymentFile], "ports:") {
		t.Errorf("the deployment carries ports with no driver listening\n%s", files[chartgen.DeploymentFile])
	}
}

func TestADriverWhoseAddrKeyIsMissingFromTheSpecIsRefusedByName(t *testing.T) {
	cells := manifests()
	rest := cells["rest"]
	rest.Provides.Drivers[0].Name = "http"
	cells["rest"] = rest

	_, err := chartgen.Generate(chartgen.Options{
		OpenapiSpec: []byte(configSpec),
		SrcDir:      filepath.Join(crate(t, cells), "chart"),
	})
	if err == nil {
		t.Fatal("a driver with no addr key in the spec was accepted")
	}

	want := `driver "http" in cell "rest" listens on TCP and the config spec has no "http_addr" key to read its port from`
	if !strings.Contains(err.Error(), want) {
		t.Errorf("got %q, want it to contain %q", err.Error(), want)
	}
}

func TestAMissingRootForgeDevIsRefusedByName(t *testing.T) {
	root := t.TempDir()

	_, err := chartgen.Generate(chartgen.Options{
		OpenapiSpec: []byte(configSpec),
		SrcDir:      filepath.Join(root, "chart"),
	})
	if err == nil {
		t.Fatal("a crate with no root forge-dev.yaml was accepted")
	}

	if !strings.Contains(err.Error(), "reading the root cell "+`"`+filepath.Join(root, "forge-dev.yaml")+`"`) {
		t.Errorf("got %q, want the root forge-dev.yaml named", err.Error())
	}
}

func TestAListedCellWithNoManifestIsRefusedByName(t *testing.T) {
	cells := manifests()
	delete(cells, "grpc")
	root := crate(t, cells)
	writeFile(t, filepath.Join(root, "src", "grpc", hexrust.CellConfigFile), "name: songe-hello\nkind: grpc\n")

	_, err := chartgen.Generate(chartgen.Options{
		OpenapiSpec: []byte(configSpec),
		SrcDir:      filepath.Join(root, "chart"),
	})
	if err == nil {
		t.Fatal("a listed cell with no manifest was accepted")
	}

	if !strings.Contains(err.Error(), `mounting cell "grpc": src/grpc/zz_generated_cell.yaml is missing`) {
		t.Errorf("got %q, want the missing manifest named", err.Error())
	}
}

func TestEveryEmittedFileStartsWithTheGeneratedHeader(t *testing.T) {
	files := generateHello(t)

	want := []string{chartgen.ChartFile, chartgen.ValuesFile, chartgen.DeploymentFile, chartgen.ServiceFile}
	if len(files) != len(want) {
		t.Fatalf("emitted %v, want %v", keysOf(files), want)
	}

	for _, path := range want {
		if !strings.HasPrefix(files[path], "# Code generated by chart-gen (forge-dev-codegen). DO NOT EDIT.\n") {
			t.Errorf("%s does not start with the header\n%s", path, files[path])
		}
	}
}

func keysOf(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}

	return out
}

func TestHelmTemplateRendersOneDeploymentAndOneServiceFromTheEmittedChart(t *testing.T) {
	helm, err := exec.LookPath("helm")
	if err != nil {
		t.Skip("helm is not on PATH")
	}

	files := generateHello(t)
	dir := t.TempDir()

	for path, content := range files {
		writeFile(t, filepath.Join(dir, path), content)
	}

	cmd := exec.Command(helm, "template", "hello", dir)

	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("helm template: %v\n%s", err, out)
	}

	rendered := string(out)

	if strings.Count(rendered, "\nkind: Deployment\n") != 1 || strings.Count(rendered, "\nkind: Service\n") != 1 {
		t.Errorf("helm template rendered other than one Deployment and one Service\n%s", rendered)
	}

	if !strings.Contains(rendered, "image: \"songe-hello-node:0.1.0\"") {
		t.Errorf("the image tag is not the app version\n%s", rendered)
	}

	if !strings.Contains(rendered, "value: \"1000\"") || !strings.Contains(rendered, "value: \"true\"") {
		t.Errorf("an integer or a boolean value did not render quoted\n%s", rendered)
	}
}
