package chartgen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"sigs.k8s.io/yaml"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/hexrust"
	"github.com/alexandremahdhaoui/forge-dev-codegen/pkg/cellmanifest"
)

const Generator = "chart-gen (forge-dev-codegen)"

const header = "# Code generated by " + Generator + ". DO NOT EDIT.\n"

const (
	ChartFile      = "Chart.yaml"
	ValuesFile     = "values.yaml"
	DeploymentFile = "templates/zz_generated_deployment.yaml"
	ServiceFile    = "templates/zz_generated_service.yaml"
)

const addrSuffix = "_addr"

type Options struct {
	OpenapiSpec []byte
	SrcDir      string
}

type File struct {
	Path    string
	Content string
}

type rootConfig struct {
	Name        string `json:"name"`
	Version     string `json:"version"`
	Description string `json:"description"`
	Layout      struct {
		Cells []string `json:"cells"`
	} `json:"layout"`
	Wiring struct {
		SpecPath string `json:"specPath"`
	} `json:"wiring"`
}

type specProperty struct {
	Default *any   `json:"default,omitempty"`
	Env     string `json:"x-env,omitempty"`
}

type specDocument struct {
	Components struct {
		Schemas map[string]struct {
			Properties map[string]specProperty `json:"properties"`
		} `json:"schemas"`
	} `json:"components"`
}

type chartMetadata struct {
	APIVersion  string `json:"apiVersion"`
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Version     string `json:"version"`
	AppVersion  string `json:"appVersion"`
}

type envEntry struct {
	Name string
	Key  string
}

type portEntry struct {
	Name     string
	Protocol string
	AddrKey  string
}

type templateData struct {
	Container string
	Env       []envEntry
	Ports     []portEntry
}

func Generate(opts Options) ([]File, error) {
	if opts.SrcDir == "" {
		return nil, fmt.Errorf("emitting the chart: the cell directory is required")
	}

	crateRoot := filepath.Dir(opts.SrcDir)

	root, err := readRoot(crateRoot)
	if err != nil {
		return nil, fmt.Errorf("emitting the chart: %w", err)
	}

	wiringDoc, err := os.ReadFile(filepath.Join(crateRoot, root.Wiring.SpecPath))
	if err != nil {
		return nil, fmt.Errorf("emitting the chart: reading the wiring %q: %w", root.Wiring.SpecPath, err)
	}

	wiring, err := hexrust.ParseWiring(wiringDoc)
	if err != nil {
		return nil, fmt.Errorf("emitting the chart: %w", err)
	}

	manifests, err := hexrust.ReadManifests(crateRoot, root.Layout.Cells)
	if err != nil {
		return nil, fmt.Errorf("emitting the chart: %w", err)
	}

	properties, err := readProperties(opts.OpenapiSpec)
	if err != nil {
		return nil, fmt.Errorf("emitting the chart: %w", err)
	}

	keys := sortedKeys(properties)

	env, err := envEntries(keys, properties)
	if err != nil {
		return nil, fmt.Errorf("emitting the chart: %w", err)
	}

	ports, err := portEntries(manifests, properties)
	if err != nil {
		return nil, fmt.Errorf("emitting the chart: %w", err)
	}

	chart, err := chartYAML(root)
	if err != nil {
		return nil, fmt.Errorf("emitting the chart: %w", err)
	}

	values, err := valuesYAML(wiring.Binary, keys, properties)
	if err != nil {
		return nil, fmt.Errorf("emitting the chart: %w", err)
	}

	data := templateData{Container: wiring.Binary, Env: env, Ports: ports}

	deployment, err := render("deployment", data)
	if err != nil {
		return nil, fmt.Errorf("emitting the chart: %w", err)
	}

	files := []File{
		{Path: ChartFile, Content: chart},
		{Path: ValuesFile, Content: values},
		{Path: DeploymentFile, Content: deployment},
	}

	if len(ports) == 0 {
		return files, nil
	}

	service, err := render("service", data)
	if err != nil {
		return nil, fmt.Errorf("emitting the chart: %w", err)
	}

	return append(files, File{Path: ServiceFile, Content: service}), nil
}

func readRoot(crateRoot string) (rootConfig, error) {
	path := filepath.Join(crateRoot, hexrust.CellConfigFile)

	doc, err := os.ReadFile(path)
	if err != nil {
		return rootConfig{}, fmt.Errorf("reading the root cell %q: %w", path, err)
	}

	var root rootConfig
	if err := yaml.Unmarshal(doc, &root); err != nil {
		return rootConfig{}, fmt.Errorf("reading the root cell %q: %w", path, err)
	}

	if root.Name == "" {
		return rootConfig{}, fmt.Errorf("reading the root cell %q: name is empty, it names the chart", path)
	}

	if root.Version == "" {
		return rootConfig{}, fmt.Errorf("reading the root cell %q: version is empty, it is the chart version and the app version", path)
	}

	if root.Wiring.SpecPath == "" {
		return rootConfig{}, fmt.Errorf("reading the root cell %q: wiring.specPath is empty, it names the binary", path)
	}

	if len(root.Layout.Cells) == 0 {
		return rootConfig{}, fmt.Errorf("reading the root cell %q: layout.cells is empty, the cells declare the drivers", path)
	}

	return root, nil
}

func readProperties(doc []byte) (map[string]specProperty, error) {
	var spec specDocument
	if err := yaml.Unmarshal(doc, &spec); err != nil {
		return nil, fmt.Errorf("reading the config spec: %w", err)
	}

	schema, ok := spec.Components.Schemas["Spec"]
	if !ok {
		return nil, fmt.Errorf("reading the config spec: it declares no Spec schema")
	}

	return schema.Properties, nil
}

func sortedKeys(properties map[string]specProperty) []string {
	keys := make([]string, 0, len(properties))
	for key := range properties {
		keys = append(keys, key)
	}

	sort.Strings(keys)

	return keys
}

func envEntries(keys []string, properties map[string]specProperty) ([]envEntry, error) {
	env := make([]envEntry, 0, len(keys))

	for _, key := range keys {
		if properties[key].Env == "" {
			return nil, fmt.Errorf("config key %q carries no x-env, the loader reads it by that name", key)
		}

		env = append(env, envEntry{Name: properties[key].Env, Key: key})
	}

	return env, nil
}

func portEntries(manifests []cellmanifest.Manifest, properties map[string]specProperty) ([]portEntry, error) {
	ports := []portEntry{}

	for _, m := range manifests {
		for _, driver := range m.Provides.Drivers {
			if driver.Protocol == "" {
				continue
			}

			addrKey := driver.Name + addrSuffix
			if _, ok := properties[addrKey]; !ok {
				return nil, fmt.Errorf(
					"driver %q in cell %q listens on %s and the config spec has no %q key to read its port from",
					driver.Name, m.Cell, driver.Protocol, addrKey,
				)
			}

			ports = append(ports, portEntry{Name: driver.Name, Protocol: driver.Protocol, AddrKey: addrKey})
		}
	}

	return ports, nil
}

func chartYAML(root rootConfig) (string, error) {
	body, err := yaml.Marshal(chartMetadata{
		APIVersion:  "v2",
		Name:        root.Name,
		Description: root.Description,
		Version:     root.Version,
		AppVersion:  root.Version,
	})
	if err != nil {
		return "", fmt.Errorf("marshalling %s: %w", ChartFile, err)
	}

	return header + string(body), nil
}

func valuesYAML(binary string, keys []string, properties map[string]specProperty) (string, error) {
	image, err := yaml.Marshal(map[string]any{"image": map[string]any{"repository": binary}})
	if err != nil {
		return "", fmt.Errorf("marshalling %s: %w", ValuesFile, err)
	}

	values := make(map[string]any, len(keys))
	for _, key := range keys {
		values[key] = defaultValue(properties[key])
	}

	body, err := yaml.Marshal(values)
	if err != nil {
		return "", fmt.Errorf("marshalling %s: %w", ValuesFile, err)
	}

	return header + string(image) + string(body), nil
}

func defaultValue(property specProperty) any {
	if property.Default == nil {
		return ""
	}

	return *property.Default
}

func render(name string, data templateData) (string, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", fmt.Errorf("rendering %s: %w", name, err)
	}

	return header + strings.TrimLeft(buf.String(), "\n"), nil
}

var templates = template.Must(template.New("chart").Delims("[[", "]]").Parse(`
[[- define "deployment" -]]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
        - name: [[ .Container ]]
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          env:
[[- range .Env ]]
            - name: [[ .Name ]]
              value: {{ .Values.[[ .Key ]] | quote }}
[[- end ]]
[[- if .Ports ]]
          ports:
[[- range .Ports ]]
            - name: [[ .Name ]]
              containerPort: {{ .Values.[[ .AddrKey ]] | splitList ":" | last | int }}
              protocol: [[ .Protocol ]]
[[- end ]]
[[- end ]]
[[ end ]]
[[- define "service" -]]
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
[[- range .Ports ]]
    - name: [[ .Name ]]
      protocol: [[ .Protocol ]]
      port: {{ .Values.[[ .AddrKey ]] | splitList ":" | last | int }}
      targetPort: {{ .Values.[[ .AddrKey ]] | splitList ":" | last | int }}
[[- end ]]
[[ end ]]
`))
