// Code generated by rest-rust (forge-dev-codegen). DO NOT EDIT.
#![allow(clippy::disallowed_methods, clippy::disallowed_types)]

pub mod zz_generated_rest_driver;

pub use zz_generated_rest_driver as rest_driver;
