// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:29e1c7a0c537d3cf637ef5a97f95c5192de51b537615cf8c884b7f65f63cf840

package main

import (
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// ValidateService validates a Service and returns validation results.
// It checks required fields and validates enum values.
func ValidateService(s *Service) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: addrEnv
	if s.AddrEnv == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.addrEnv",
			Message: "required field is missing",
		})
	}
	// Validate required field: binary
	if s.Binary == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.binary",
			Message: "required field is missing",
		})
	}
	// Validate required field: name
	if s.Name == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.name",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateSpec validates a Spec and returns validation results.
// It checks required fields and validates enum values.
func ValidateSpec(s *Spec) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required array of references: services
	if len(s.Services) == 0 {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.services",
			Message: "required field is missing or empty",
		})
	}
	// Validate array of references: services
	for i, item := range s.Services {
		nestedResult := ValidateService(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.services[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// Validate validates a Spec and returns validation results.
// This is the main entry point for validation.
func Validate(s *Spec) *mcptypes.ConfigValidateOutput {
	return ValidateSpec(s)
}

// ValidateMap validates a map[string]interface{} by first parsing it to a Spec.
// This is a convenience function for validating spec data from forge.yaml.
func ValidateMap(m map[string]interface{}) *mcptypes.ConfigValidateOutput {
	s, err := FromMap(m)
	if err != nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: false,
			Errors: []mcptypes.ValidationError{
				{
					Field:   "spec",
					Message: err.Error(),
				},
			},
		}
	}

	return Validate(s)
}
