// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:3b89ef01f54d5b08753fef5a92fc6fd55eef8024f0f325d7ce7d7337e420c91f

package main

import (
	"fmt"
)

// After represents the After configuration.
// One command run after readiness. Its stdout carries a value the stack exports.
type After struct {
	// Arguments passed to the command. Every value carries the same placeholders as the service.
	Args []string `json:"args,omitempty"`
	// The program to run. A value with a path separator resolves against the project root. A bare name is looked up on PATH.
	Command string `json:"command"`
	// The environment variable the captured value is exported as.
	Export string `json:"export"`
	// A dotted path into the JSON answer, such as store.id. A numeric segment indexes an array. Exactly one of regex and jsonPath is required.
	JsonPath string `json:"jsonPath,omitempty"`
	// A regular expression with one capturing group over stdout. Exactly one of regex and jsonPath is required.
	Regex string `json:"regex,omitempty"`
}

// Ready represents the Ready configuration.
// How the engine decides the service is ready. An absent block means the stdout keyword, which is the contract every service written before ports existed relies on.
type Ready struct {
	// One of stdout, tcp and http. An absent kind reads as stdout. stdout waits for a LISTENING line. tcp connects to a declared port. http gets a path on a declared port and compares the status.
	Kind string `json:"kind,omitempty"`
	// The path to get. Required for http, refused for the other kinds.
	Path string `json:"path,omitempty"`
	// The declared port to probe. Required for tcp and http, refused for stdout.
	Port string `json:"port,omitempty"`
	// The status the get must answer. Required for http, refused for the other kinds.
	Status int `json:"status,omitempty"`
}

// Service represents the Service configuration.
// One service binary to start.
type Service struct {
	// The name every exported address is built from. A service with no ports declared is started with addrEnv set to 127.0.0.1:0 and announces its ports on stdout. A service with ports declared exports one address per port as <addrEnv>_<PORT>.
	AddrEnv string `json:"addrEnv"`
	// Commands run once the service is ready, in order. Each one captures a value out of its stdout into the environment.
	After []After `json:"after,omitempty"`
	// Arguments passed to the binary. Every value carries placeholders.
	Args []string `json:"args,omitempty"`
	// Path to the binary to start. Relative paths resolve against the project root.
	Binary string `json:"binary"`
	// Extra environment variables for this service. They win over the accumulated testenv env. Every value carries placeholders.
	Env map[string]string `json:"env,omitempty"`
	// Service name. The log file is <TmpDir>/<name>.log.
	Name string `json:"name"`
	// Names of the ports the engine binds free before start. Each one is substituted as @port.<name>@ into args and env and exported as <addrEnv>_<NAME>. The delimiter is @ because forge expands its own double brace templates over this spec before the engine reads it.
	Ports []string `json:"ports,omitempty"`
	Ready Ready    `json:"ready,omitempty"`
	// Seconds to wait for readiness before create fails. Default 30.
	ReadyTimeoutSeconds int `json:"readyTimeoutSeconds,omitempty"`
}

// Spec represents the Spec configuration.
// The services to start. Each runs as a detached child process.
type Spec struct {
	// Services started in order.
	Services []Service `json:"services"`
}

// AfterFromMap creates a After from a map[string]interface{}.
func AfterFromMap(m map[string]interface{}) (*After, error) {
	if m == nil {
		return &After{}, nil
	}

	s := &After{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "args":
		case "command":
		case "export":
		case "jsonPath":
		case "regex":
		default:
			return nil, fmt.Errorf("field %s: not a key of After; the keys are args, command, export, jsonPath, regex", key)
		}
	}
	// Parse args
	if v, ok := m["args"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Args = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Args = append(s.Args, str)
				} else {
					return nil, fmt.Errorf("field args[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Args = arr
		} else {
			return nil, fmt.Errorf("field args: expected []string, got %T", v)
		}
	}
	// Parse command
	if v, ok := m["command"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Command = val
		} else {
			return nil, fmt.Errorf("field command: expected string, got %T", v)
		}
	}
	// Parse export
	if v, ok := m["export"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Export = val
		} else {
			return nil, fmt.Errorf("field export: expected string, got %T", v)
		}
	}
	// Parse jsonPath
	if v, ok := m["jsonPath"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.JsonPath = val
		} else {
			return nil, fmt.Errorf("field jsonPath: expected string, got %T", v)
		}
	}
	// Parse regex
	if v, ok := m["regex"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Regex = val
		} else {
			return nil, fmt.Errorf("field regex: expected string, got %T", v)
		}
	}
	return s, nil
}

// ReadyFromMap creates a Ready from a map[string]interface{}.
func ReadyFromMap(m map[string]interface{}) (*Ready, error) {
	if m == nil {
		return &Ready{}, nil
	}

	s := &Ready{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "kind":
		case "path":
		case "port":
		case "status":
		default:
			return nil, fmt.Errorf("field %s: not a key of Ready; the keys are kind, path, port, status", key)
		}
	}
	// Parse kind
	if v, ok := m["kind"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Kind = val
		} else {
			return nil, fmt.Errorf("field kind: expected string, got %T", v)
		}
	}
	// Parse path
	if v, ok := m["path"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Path = val
		} else {
			return nil, fmt.Errorf("field path: expected string, got %T", v)
		}
	}
	// Parse port
	if v, ok := m["port"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Port = val
		} else {
			return nil, fmt.Errorf("field port: expected string, got %T", v)
		}
	}
	// Parse status
	if v, ok := m["status"]; ok && v != nil {
		switch val := v.(type) {
		case int:
			s.Status = val
		case int64:
			s.Status = int(val)
		case float64:
			s.Status = int(val)
		default:
			return nil, fmt.Errorf("field status: expected int, got %T", v)
		}
	}
	return s, nil
}

// ServiceFromMap creates a Service from a map[string]interface{}.
func ServiceFromMap(m map[string]interface{}) (*Service, error) {
	if m == nil {
		return &Service{}, nil
	}

	s := &Service{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "addrEnv":
		case "after":
		case "args":
		case "binary":
		case "env":
		case "name":
		case "ports":
		case "ready":
		case "readyTimeoutSeconds":
		default:
			return nil, fmt.Errorf("field %s: not a key of Service; the keys are addrEnv, after, args, binary, env, name, ports, ready, readyTimeoutSeconds", key)
		}
	}
	// Parse addrEnv
	if v, ok := m["addrEnv"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.AddrEnv = val
		} else {
			return nil, fmt.Errorf("field addrEnv: expected string, got %T", v)
		}
	}
	// Parse after
	if v, ok := m["after"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.After = make([]After, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := AfterFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field after[%d]: %w", i, err)
					}
					if ref != nil {
						s.After = append(s.After, *ref)
					}
				} else {
					return nil, fmt.Errorf("field after[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field after: expected []object, got %T", v)
		}
	}
	// Parse args
	if v, ok := m["args"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Args = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Args = append(s.Args, str)
				} else {
					return nil, fmt.Errorf("field args[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Args = arr
		} else {
			return nil, fmt.Errorf("field args: expected []string, got %T", v)
		}
	}
	// Parse binary
	if v, ok := m["binary"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Binary = val
		} else {
			return nil, fmt.Errorf("field binary: expected string, got %T", v)
		}
	}
	// Parse env
	if v, ok := m["env"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Env = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Env[key] = str
				} else {
					return nil, fmt.Errorf("field env[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Env = mapVal
		} else {
			return nil, fmt.Errorf("field env: expected map[string]string, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse ports
	if v, ok := m["ports"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Ports = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Ports = append(s.Ports, str)
				} else {
					return nil, fmt.Errorf("field ports[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Ports = arr
		} else {
			return nil, fmt.Errorf("field ports: expected []string, got %T", v)
		}
	}
	// Parse ready
	if v, ok := m["ready"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := ReadyFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field ready: %w", err)
			}
			if ref != nil {
				s.Ready = *ref
			}
		} else {
			return nil, fmt.Errorf("field ready: expected object, got %T", v)
		}
	}
	// Parse readyTimeoutSeconds
	if v, ok := m["readyTimeoutSeconds"]; ok && v != nil {
		switch val := v.(type) {
		case int:
			s.ReadyTimeoutSeconds = val
		case int64:
			s.ReadyTimeoutSeconds = int(val)
		case float64:
			s.ReadyTimeoutSeconds = int(val)
		default:
			return nil, fmt.Errorf("field readyTimeoutSeconds: expected int, got %T", v)
		}
	}
	return s, nil
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "services":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are services", key)
		}
	}
	// Parse services
	if v, ok := m["services"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Services = make([]Service, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := ServiceFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field services[%d]: %w", i, err)
					}
					if ref != nil {
						s.Services = append(s.Services, *ref)
					}
				} else {
					return nil, fmt.Errorf("field services[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field services: expected []object, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a After to a map[string]interface{}.
func (s *After) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Args) > 0 {
		m["args"] = s.Args
	}
	if s.Command != "" {
		m["command"] = s.Command
	}
	if s.Export != "" {
		m["export"] = s.Export
	}
	if s.JsonPath != "" {
		m["jsonPath"] = s.JsonPath
	}
	if s.Regex != "" {
		m["regex"] = s.Regex
	}
	return m
}

// ToMap converts a Ready to a map[string]interface{}.
func (s *Ready) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Kind != "" {
		m["kind"] = s.Kind
	}
	if s.Path != "" {
		m["path"] = s.Path
	}
	if s.Port != "" {
		m["port"] = s.Port
	}
	if s.Status != 0 {
		m["status"] = s.Status
	}
	return m
}

// ToMap converts a Service to a map[string]interface{}.
func (s *Service) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.AddrEnv != "" {
		m["addrEnv"] = s.AddrEnv
	}
	if len(s.After) > 0 {
		arr := make([]interface{}, 0, len(s.After))
		for _, item := range s.After {
			arr = append(arr, item.ToMap())
		}
		m["after"] = arr
	}
	if len(s.Args) > 0 {
		m["args"] = s.Args
	}
	if s.Binary != "" {
		m["binary"] = s.Binary
	}
	if len(s.Env) > 0 {
		m["env"] = s.Env
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	if len(s.Ports) > 0 {
		m["ports"] = s.Ports
	}
	// Reference type Ready
	if refMap := s.Ready.ToMap(); len(refMap) > 0 {
		m["ready"] = refMap
	}
	if s.ReadyTimeoutSeconds != 0 {
		m["readyTimeoutSeconds"] = s.ReadyTimeoutSeconds
	}
	return m
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Services) > 0 {
		arr := make([]interface{}, 0, len(s.Services))
		for _, item := range s.Services {
			arr = append(arr, item.ToMap())
		}
		m["services"] = arr
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
