// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:7f53bb63aff81d1baf11dfc758b434606a398b8432b1e986fd30be6ed20dcb73

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for forge-lint. All fields are optional.
type Spec struct {
	// Root directory holding the forge.yaml to check (default is current directory)
	RootDir string `json:"rootDir,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}
	// Parse rootDir
	if v, ok := m["rootDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.RootDir = val
		} else {
			return nil, fmt.Errorf("field rootDir: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.RootDir != "" {
		m["rootDir"] = s.RootDir
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
