// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:65c5fbe07d1cfb79640c794a6299af9afc98355781bca99cef1665c65432ce69

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for windows-allow. A dev machine tool that clears a locally built Windows exe past Smart App Control by relinking the hash until the machine allows a build. Never a release step.
type Spec struct {
	// How many builds to try before giving up. Defaults to 8.
	Attempts int `json:"attempts,omitempty"`
	// The directory the allowed build lands in. Env vars are expanded, so $WIN_OUTPUT_PATH works.
	Destination string `json:"destination"`
	// How many builds of this binary to keep in the destination after an allowed one. Older builds of the same name are removed. Builds of other projects are never touched. Defaults to 3.
	Keep int `json:"keep,omitempty"`
	// The base name of the game binary. The deployed file is name-commit-hash.exe.
	Name string `json:"name"`
	// The arguments the probe runs the exe with.
	ProbeArgs []string `json:"probeArgs,omitempty"`
	// The string an allowed build prints. Its absence with Invalid argument present means the build is blocked.
	ProbeExpect string `json:"probeExpect"`
	// How long the probe waits for the exe to print before it stops it. Defaults to 8.
	ProbeTimeoutSeconds int `json:"probeTimeoutSeconds,omitempty"`
	// The repo directory whose commit names the deployed file. Defaults to the current directory.
	RootDir string `json:"rootDir,omitempty"`
	// The built Windows exe to clear, a path relative to rootDir.
	Source string `json:"source"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}
	// Parse attempts
	if v, ok := m["attempts"]; ok && v != nil {
		switch val := v.(type) {
		case int:
			s.Attempts = val
		case int64:
			s.Attempts = int(val)
		case float64:
			s.Attempts = int(val)
		default:
			return nil, fmt.Errorf("field attempts: expected int, got %T", v)
		}
	}
	// Parse destination
	if v, ok := m["destination"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Destination = val
		} else {
			return nil, fmt.Errorf("field destination: expected string, got %T", v)
		}
	}
	// Parse keep
	if v, ok := m["keep"]; ok && v != nil {
		switch val := v.(type) {
		case int:
			s.Keep = val
		case int64:
			s.Keep = int(val)
		case float64:
			s.Keep = int(val)
		default:
			return nil, fmt.Errorf("field keep: expected int, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse probeArgs
	if v, ok := m["probeArgs"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.ProbeArgs = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.ProbeArgs = append(s.ProbeArgs, str)
				} else {
					return nil, fmt.Errorf("field probeArgs[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.ProbeArgs = arr
		} else {
			return nil, fmt.Errorf("field probeArgs: expected []string, got %T", v)
		}
	}
	// Parse probeExpect
	if v, ok := m["probeExpect"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.ProbeExpect = val
		} else {
			return nil, fmt.Errorf("field probeExpect: expected string, got %T", v)
		}
	}
	// Parse probeTimeoutSeconds
	if v, ok := m["probeTimeoutSeconds"]; ok && v != nil {
		switch val := v.(type) {
		case int:
			s.ProbeTimeoutSeconds = val
		case int64:
			s.ProbeTimeoutSeconds = int(val)
		case float64:
			s.ProbeTimeoutSeconds = int(val)
		default:
			return nil, fmt.Errorf("field probeTimeoutSeconds: expected int, got %T", v)
		}
	}
	// Parse rootDir
	if v, ok := m["rootDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.RootDir = val
		} else {
			return nil, fmt.Errorf("field rootDir: expected string, got %T", v)
		}
	}
	// Parse source
	if v, ok := m["source"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Source = val
		} else {
			return nil, fmt.Errorf("field source: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Attempts != 0 {
		m["attempts"] = s.Attempts
	}
	if s.Destination != "" {
		m["destination"] = s.Destination
	}
	if s.Keep != 0 {
		m["keep"] = s.Keep
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	if len(s.ProbeArgs) > 0 {
		m["probeArgs"] = s.ProbeArgs
	}
	if s.ProbeExpect != "" {
		m["probeExpect"] = s.ProbeExpect
	}
	if s.ProbeTimeoutSeconds != 0 {
		m["probeTimeoutSeconds"] = s.ProbeTimeoutSeconds
	}
	if s.RootDir != "" {
		m["rootDir"] = s.RootDir
	}
	if s.Source != "" {
		m["source"] = s.Source
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
