// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/restspec"
)

// NewHandlers wires the generate tool: the model's OpenAPI paths decide
// the routes, axum serves them. Same contract as forge-dev's builtin go
// cell - the paths are the surface, one typed handler per operation, a
// LISTENING line on bind.
func NewHandlers() Handlers {
	return Handlers{
		Generate: func(_ context.Context, input GenerateInput) (*GenerateOutput, error) {
			if input.Kind != "rest-api" {
				return nil, fmt.Errorf("emitting %q: rest-rust-axum fills the rest-api cell only", input.Kind)
			}

			if input.Language != "rust" {
				return nil, fmt.Errorf("emitting for %q: rest-rust-axum generates rust only", input.Language)
			}

			operations, err := restspec.Operations([]byte(input.OpenapiSpec))
			if err != nil {
				return nil, fmt.Errorf("reading the paths for %q: %w", input.Name, err)
			}

			var buf bytes.Buffer
			if err := axumTmpl.Execute(&buf, map[string]any{
				"Name":       input.Name,
				"Version":    input.Version,
				"EnvPrefix":  envPrefix(input.Name),
				"Checksum":   input.Checksum,
				"Operations": operations,
			}); err != nil {
				return nil, fmt.Errorf("rendering the axum server for %q: %w", input.Name, err)
			}

			return &GenerateOutput{
				Files: []GeneratedFile{{Path: "zz_generated_rest.rs", Content: buf.String()}},
			}, nil
		},
	}
}

// envPrefix turns rest-demo into REST_DEMO.
func envPrefix(name string) string {
	return strings.ToUpper(strings.NewReplacer("-", "_", ".", "_").Replace(name))
}

var axumTmpl = template.Must(template.New("axum").Parse(`// Code generated by rest-rust-axum (forge-dev-codegen). DO NOT EDIT.
// Source: forge-dev.yaml
// SourceChecksum: {{ .Checksum }}

//! {{ .Name }} v{{ .Version }}: a rest-api kind program served by axum.
//! The author writes new_rest_handlers() beside this module; the routes
//! derive from the OpenAPI paths verbatim, so the server cannot drift
//! from the spec.

#![allow(dead_code)]

use std::collections::HashMap;

/// One handler per operation of the OpenAPI paths: path parameters in,
/// status and body out. The type makes every field required.
pub struct RESTHandlers {
{{- range .Operations }}
    /// Serves {{ .Method }} {{ .Path }}. {{ .Description }}
    pub {{ .SnakeName }}: fn(&HashMap<String, String>) -> (u16, String),
{{- end }}
}

fn answer(pair: (u16, String)) -> (axum::http::StatusCode, String) {
    let status = axum::http::StatusCode::from_u16(pair.0)
        .unwrap_or(axum::http::StatusCode::INTERNAL_SERVER_ERROR);

    (status, pair.1)
}

/// serve binds {{ .EnvPrefix }}_ADDR (default 127.0.0.1:0), prints
/// LISTENING <port> once bound, and serves the declared routes.
pub async fn serve(handlers: RESTHandlers) {
    let router = axum::Router::new(){{ range .Operations }}
        .route("{{ .Path }}", {
            let handler = handlers.{{ .SnakeName }};
            axum::routing::{{ .MethodLower }}(
                move |axum::extract::Path(params): axum::extract::Path<HashMap<String, String>>| async move {
                    answer(handler(&params))
                },
            )
        }){{ end }};

    let addr = std::env::var("{{ .EnvPrefix }}_ADDR").unwrap_or_else(|_| "127.0.0.1:0".to_string());
    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .unwrap_or_else(|e| panic!("{{ .Name }}: binding {addr}: {e}"));
    let port = listener
        .local_addr()
        .expect("{{ .Name }}: reading the bound port")
        .port();

    println!("LISTENING {port}");

    axum::serve(listener, router)
        .await
        .expect("{{ .Name }}: serving");
}
`))
