// Code generated by tui-rust (forge-dev-codegen). DO NOT EDIT.
#![allow(clippy::disallowed_methods, clippy::disallowed_types)]

pub mod zz_generated_crossterm_keyboard;
pub mod zz_generated_crossterm_screen;

pub use zz_generated_crossterm_keyboard as crossterm_keyboard;

pub use zz_generated_crossterm_screen as crossterm_screen;
