// Code generated by tui-rust (forge-dev-codegen). DO NOT EDIT.

use std::time::Duration;

use crossterm::event::{self, Event, KeyCode, KeyEvent, KeyEventKind, KeyModifiers};

use crate::tui::port::keyboard::{Keyboard, KeyboardError};
use crate::tui::types::key::Input;

#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct CrosstermKeyboardConfig {}

pub struct CrosstermKeyboard;

impl CrosstermKeyboard {
    pub fn new(config: CrosstermKeyboardConfig) -> Self {
        let _ = config;

        Self
    }
}

fn reading(timeout: Duration) -> impl Fn(std::io::Error) -> KeyboardError {
    move |source| KeyboardError::Read {
        timeout_ms: u64::try_from(timeout.as_millis()).unwrap_or(u64::MAX),
        source: Box::new(source),
    }
}

pub fn input_of(key: KeyEvent) -> Input {
    if key.modifiers.contains(KeyModifiers::CONTROL) && key.code == KeyCode::Char('c') {
        return Input::Interrupt;
    }

    match key.code {
        KeyCode::Char(c) => Input::Char(c),
        KeyCode::Enter => Input::Enter,
        KeyCode::Backspace => Input::Backspace,
        KeyCode::Esc => Input::Escape,
        KeyCode::Up => Input::Up,
        KeyCode::Down => Input::Down,
        KeyCode::Left => Input::Left,
        KeyCode::Right => Input::Right,
        _ => Input::Other,
    }
}

impl Keyboard for CrosstermKeyboard {
    fn read(&self, timeout: Duration) -> Result<Option<Input>, KeyboardError> {
        let failing = reading(timeout);

        if !event::poll(timeout).map_err(&failing)? {
            return Ok(None);
        }

        match event::read().map_err(&failing)? {
            Event::Key(key) if key.kind != KeyEventKind::Release => Ok(Some(input_of(key))),
            _ => Ok(None),
        }
    }
}
