// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package authzgen_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/authzgen"
)

func writeModuleCell(t *testing.T, root, dir, doc string) {
	t.Helper()

	cell := filepath.Join(root, dir)

	if err := os.MkdirAll(cell, 0o755); err != nil {
		t.Fatalf("making the cell %s: %v", dir, err)
	}

	files, err := authzgen.Generate([]byte(doc))
	if err != nil {
		t.Fatalf("generating the module of %s: %v", dir, err)
	}

	for _, f := range files {
		if err := os.WriteFile(filepath.Join(cell, f.Path), []byte(f.Content), 0o600); err != nil {
			t.Fatalf("writing %s of %s: %v", f.Path, dir, err)
		}
	}
}

const chatSpec = `module: chat
references:
  - module: session
    types:
      - name: character
      - name: session
        relations: [member]
types:
  - name: channel
    relations:
      - name: session
        subjects: [session]
      - name: member
        expression: member from session
      - name: post
        expression: member
vectors:
  - name: a member may post
    tuples:
      - user: session:s1
        relation: session
        object: channel:c1
      - user: character:alice
        relation: member
        object: session:s1
    checks:
      - user: character:alice
        relation: post
        object: channel:c1
        expected: true
`

func twoCells(t *testing.T) string {
	t.Helper()

	root := t.TempDir()

	writeModuleCell(t, root, "session", sessionSpec+`vectors:
  - name: a member may join
    tuples:
      - user: character:alice
        relation: member
        object: session:s1
    checks:
      - user: character:alice
        relation: join
        object: session:s1
        expected: true
`)
	writeModuleCell(t, root, "chat", chatSpec)

	if err := os.MkdirAll(filepath.Join(root, "combined"), 0o755); err != nil {
		t.Fatalf("making the combine cell: %v", err)
	}

	return root
}

func combine(t *testing.T, root string, modules ...string) map[string]string {
	t.Helper()

	files, err := authzgen.Combine(authzgen.CombineOptions{
		Name:    "songe-authz",
		SrcDir:  filepath.Join(root, "combined"),
		Modules: modules,
	})
	if err != nil {
		t.Fatalf("combining: %v", err)
	}

	byPath := map[string]string{}
	for _, f := range files {
		byPath[f.Path] = f.Content
	}

	return byPath
}

func refusedCombination(t *testing.T, root string, modules []string, wants ...string) {
	t.Helper()

	_, err := authzgen.Combine(authzgen.CombineOptions{
		Name:    "songe-authz",
		SrcDir:  filepath.Join(root, "combined"),
		Modules: modules,
	})
	if err == nil {
		t.Fatal("the combination was accepted")
	}

	for _, want := range wants {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("the refusal %q never named %q", err, want)
		}
	}
}

func TestTheCombinationWritesTheModFileTheMergedTestsAndACopyOfEveryModule(t *testing.T) {
	root := twoCells(t)
	files := combine(t, root, "../session/zz_generated_authz.json", "../chat/zz_generated_authz.json")

	for _, path := range []string{
		"zz_generated_fga.mod",
		"zz_generated_fga.yaml",
		"zz_generated_session.fga",
		"zz_generated_chat.fga",
	} {
		if _, written := files[path]; !written {
			t.Errorf("the combination never wrote %s", path)
		}
	}

	if len(files) != 4 {
		t.Fatalf("the combination wrote %d files", len(files))
	}
}

func TestTheModFileCarriesTheSchemaAndNamesEveryModuleFileInTheListedOrder(t *testing.T) {
	root := twoCells(t)
	got := combine(t, root, "../session/zz_generated_authz.json", "../chat/zz_generated_authz.json")["zz_generated_fga.mod"]

	want := `# Code generated by authz-gen (forge-dev-codegen). DO NOT EDIT.
schema: "1.2"
contents:
  - zz_generated_session.fga
  - zz_generated_chat.fga
`

	if got != want {
		t.Fatalf("the mod file\n got:\n%s\nwant:\n%s", got, want)
	}
}

func TestTheMergedTestFileNamesTheModFileAndPrefixesEveryCaseWithItsModule(t *testing.T) {
	root := twoCells(t)
	got := combine(t, root, "../session/zz_generated_authz.json", "../chat/zz_generated_authz.json")["zz_generated_fga.yaml"]

	for _, want := range []string{
		"name: \"songe-authz\"\n",
		"model_file: \"zz_generated_fga.mod\"\n",
		"  - name: \"session: a member may join\"\n",
		"  - name: \"chat: a member may post\"\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("the merged tests never held\n%s\ngot:\n%s", want, got)
		}
	}
}

func TestTheCopiedModuleFileIsTheByteOfTheModuleCell(t *testing.T) {
	root := twoCells(t)
	got := combine(t, root, "../session/zz_generated_authz.json", "../chat/zz_generated_authz.json")["zz_generated_chat.fga"]

	want, err := os.ReadFile(filepath.Join(root, "chat", "zz_generated_chat.fga"))
	if err != nil {
		t.Fatalf("reading the chat module: %v", err)
	}

	if got != string(want) {
		t.Fatalf("the copy\n got:\n%s\nwant:\n%s", got, want)
	}
}

func TestACombinationWithoutAModuleIsRefusedNamingTheFix(t *testing.T) {
	refusedCombination(t, twoCells(t), nil,
		"the cell lists no module",
		"name every zz_generated_authz.json under modules in combine.yaml",
	)
}

func TestAManifestThatIsNotOnDiskIsRefusedNamingThePath(t *testing.T) {
	refusedCombination(t, twoCells(t), []string{"../play/zz_generated_authz.json"},
		"reading the manifest ../play/zz_generated_authz.json",
	)
}

func TestAModuleListedTwiceIsRefusedNamingBothPaths(t *testing.T) {
	refusedCombination(t, twoCells(t), []string{
		"../session/zz_generated_authz.json",
		"../session/zz_generated_authz.json",
	}, `module "session" is listed by`, "list each module once")
}

func TestAModuleWhoseReferenceIsNotListedIsRefusedNamingBothModules(t *testing.T) {
	refusedCombination(t, twoCells(t), []string{"../chat/zz_generated_authz.json"},
		`module "chat" names module "session", which the combination does not list`,
		"add its zz_generated_authz.json under modules",
	)
}

func writeManifestCell(t *testing.T, root, dir, manifest string) {
	t.Helper()

	cell := filepath.Join(root, dir)

	if err := os.MkdirAll(cell, 0o755); err != nil {
		t.Fatalf("making the cell %s: %v", dir, err)
	}

	if err := os.WriteFile(filepath.Join(cell, "zz_generated_authz.json"), []byte(manifest), 0o600); err != nil {
		t.Fatalf("writing the manifest of %s: %v", dir, err)
	}
}

func TestTwoModulesOnDifferentSchemasAreRefusedNamingBothSchemas(t *testing.T) {
	root := twoCells(t)

	writeManifestCell(t, root, "old", `{
  "module": "old",
  "schema": "1.1",
  "model": "zz_generated_old.fga",
  "tests": "zz_generated_old.fga.yaml",
  "types": [],
  "references": [],
  "extends": [],
  "cases": []
}
`)

	if err := os.WriteFile(filepath.Join(root, "old", "zz_generated_old.fga"), []byte("module old\n"), 0o600); err != nil {
		t.Fatalf("writing the old module: %v", err)
	}

	if err := os.WriteFile(filepath.Join(root, "old", "zz_generated_old.fga.yaml"), []byte("name: \"old\"\ntests:\n"), 0o600); err != nil {
		t.Fatalf("writing the old tests: %v", err)
	}

	refusedCombination(t, root, []string{
		"../session/zz_generated_authz.json",
		"../old/zz_generated_authz.json",
	}, `module "session" writes schema "1.2" and module "old" writes schema "1.1"`, "one model holds one schema")
}

func TestAManifestWithoutAModuleNameIsRefusedNamingThePathAndTheFix(t *testing.T) {
	root := twoCells(t)

	writeManifestCell(t, root, "blank", "{}\n")

	refusedCombination(t, root, []string{"../blank/zz_generated_authz.json"},
		`module "" is not a lower case identifier`,
		"build the module cell before the combination",
	)
}

func TestAManifestThatIsNotJsonIsRefusedNamingThePath(t *testing.T) {
	root := twoCells(t)

	writeManifestCell(t, root, "broken", "not json\n")

	refusedCombination(t, root, []string{"../broken/zz_generated_authz.json"},
		"reading the manifest ../broken/zz_generated_authz.json",
	)
}

func TestAModuleFileMissingBesideItsManifestIsRefusedNamingTheModule(t *testing.T) {
	root := twoCells(t)

	writeManifestCell(t, root, "gone", `{
  "module": "gone",
  "schema": "1.2",
  "model": "zz_generated_gone.fga",
  "tests": "zz_generated_gone.fga.yaml"
}
`)

	refusedCombination(t, root, []string{"../gone/zz_generated_authz.json"},
		`reading the module file of "gone"`,
	)
}

func TestATestFileThatIsNotYamlIsRefusedNamingTheModule(t *testing.T) {
	root := twoCells(t)

	writeManifestCell(t, root, "bent", `{
  "module": "bent",
  "schema": "1.2",
  "model": "zz_generated_bent.fga",
  "tests": "zz_generated_bent.fga.yaml"
}
`)

	if err := os.WriteFile(filepath.Join(root, "bent", "zz_generated_bent.fga"), []byte("module bent\n"), 0o600); err != nil {
		t.Fatalf("writing the bent module: %v", err)
	}

	if err := os.WriteFile(filepath.Join(root, "bent", "zz_generated_bent.fga.yaml"), []byte("tests: [\n"), 0o600); err != nil {
		t.Fatalf("writing the bent tests: %v", err)
	}

	refusedCombination(t, root, []string{"../bent/zz_generated_authz.json"},
		`reading the test file of "bent"`,
	)
}

func TestACombineDocumentThatIsNotYamlIsRefusedNamingTheFile(t *testing.T) {
	_, err := authzgen.ModulesFromSpec([]byte("modules: [\n"))
	if err == nil || !strings.Contains(err.Error(), "reading combine.yaml:") {
		t.Fatalf("the refusal was %v", err)
	}
}

func TestACombinationWithoutACellNameIsRefused(t *testing.T) {
	_, err := authzgen.Combine(authzgen.CombineOptions{Modules: []string{"a.json"}})
	if err == nil || !strings.Contains(err.Error(), "the cell name is required") {
		t.Fatalf("the refusal was %v", err)
	}
}

func TestTheModuleListIsReadFromTheCombineDocument(t *testing.T) {
	modules, err := authzgen.ModulesFromSpec([]byte("modules:\n  - ../session/zz_generated_authz.json\n"))
	if err != nil {
		t.Fatalf("reading combine.yaml: %v", err)
	}

	if strings.Join(modules, ",") != "../session/zz_generated_authz.json" {
		t.Fatalf("got modules %q", modules)
	}
}

func TestACombineDocumentWhoseModulesAreAMappingIsRefusedNamingTheKeyAndTheShape(t *testing.T) {
	_, err := authzgen.ModulesFromSpec([]byte("modules:\n  session: ../session\n"))
	if err == nil {
		t.Fatal("a mapping of modules was accepted")
	}

	want := "combine.yaml modules: expected a list of paths to a zz_generated_authz.json, got a mapping"
	if !strings.Contains(err.Error(), want) {
		t.Fatalf("the refusal %q never named %q", err, want)
	}
}

func TestACombineDocumentWithAnUnknownKeyIsRefused(t *testing.T) {
	_, err := authzgen.ModulesFromSpec([]byte("module: session\n"))
	if err == nil || !strings.Contains(err.Error(), "combine.yaml module: unknown key, write one of modules") {
		t.Fatalf("the refusal was %v", err)
	}
}

func TestAnEmptyPathInTheCombineDocumentIsRefusedNamingItsIndex(t *testing.T) {
	_, err := authzgen.ModulesFromSpec([]byte("modules:\n  - \"\"\n"))
	if err == nil || !strings.Contains(err.Error(), "combine.yaml modules[0]: it is empty") {
		t.Fatalf("the refusal was %v", err)
	}
}

func TestTheCombinedDemoRegeneratesExactlyTheCommittedGoldenFiles(t *testing.T) {
	cell := filepath.Join(demoDir, "combined")

	spec, err := os.ReadFile(filepath.Join(cell, "combine.yaml"))
	if err != nil {
		t.Fatalf("reading the demo combine.yaml: %v", err)
	}

	modules, err := authzgen.ModulesFromSpec(spec)
	if err != nil {
		t.Fatalf("reading the demo combine.yaml: %v", err)
	}

	files, err := authzgen.Combine(authzgen.CombineOptions{
		Name:    "demo-authz-combined",
		SrcDir:  cell,
		Modules: modules,
	})
	if err != nil {
		t.Fatalf("combining the demo: %v", err)
	}

	for _, f := range files {
		want, err := os.ReadFile(filepath.Join(cell, f.Path))
		if err != nil {
			t.Fatalf("reading the demo file %s: %v", f.Path, err)
		}

		if f.Content != string(want) {
			t.Errorf("combined/%s drifted from the committed golden file\n got:\n%s\nwant:\n%s", f.Path, f.Content, want)
		}
	}
}

func TestThePerModuleTestFileNamesTheModFileTheCombineKindWrites(t *testing.T) {
	root := twoCells(t)

	module, err := os.ReadFile(filepath.Join(root, "chat", "zz_generated_chat.fga.yaml"))
	if err != nil {
		t.Fatalf("reading the chat tests: %v", err)
	}

	named := ""

	for _, line := range strings.Split(string(module), "\n") {
		if rest, cut := strings.CutPrefix(line, "model_file: "); cut {
			named = strings.Trim(rest, `"`)
		}
	}

	if named == "" {
		t.Fatalf("the chat tests name no model_file\n%s", module)
	}

	files := combine(t, root, "../session/zz_generated_authz.json", "../chat/zz_generated_authz.json")

	if _, written := files[named]; !written {
		t.Fatalf("the module tests name %q, which the combination never writes", named)
	}
}

func TestEveryCombinedPathIsZzGenerated(t *testing.T) {
	root := twoCells(t)

	for path := range combine(t, root, "../session/zz_generated_authz.json", "../chat/zz_generated_authz.json") {
		if !strings.HasPrefix(path, "zz_generated") {
			t.Errorf("%s is not named zz_generated", path)
		}
	}
}
