// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package authzgen

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
)

const (
	header        = "# Code generated by authz-gen (forge-dev-codegen). DO NOT EDIT."
	schemaVersion = "1.2"
	modelFile     = "zz_generated_fga.mod"
	manifestPath  = "zz_generated_authz.json"
)

func Generate(doc []byte) ([]File, error) {
	m, err := ParseSpec(doc)
	if err != nil {
		return nil, err
	}

	model, err := emitModel(m)
	if err != nil {
		return nil, fmt.Errorf("emitting the openfga module %q: %w", m.Name, err)
	}

	manifest, err := emitManifest(m)
	if err != nil {
		return nil, fmt.Errorf("emitting the manifest of module %q: %w", m.Name, err)
	}

	tests, err := emitTests(m)
	if err != nil {
		return nil, fmt.Errorf("emitting the tests of module %q: %w", m.Name, err)
	}

	wire, err := emitWire(m, model)
	if err != nil {
		return nil, fmt.Errorf("emitting the wire form of module %q: %w", m.Name, err)
	}

	return []File{
		{Path: modelPath(m), Content: model},
		{Path: testsPath(m), Content: tests},
		{Path: wirePath(m), Content: wire},
		{Path: manifestPath, Content: manifest},
	}, nil
}

func modelPath(m Module) string {
	return "zz_generated_" + m.Name + ".fga"
}

func testsPath(m Module) string {
	return "zz_generated_" + m.Name + ".fga.yaml"
}

func emitModel(m Module) (string, error) {
	var b strings.Builder

	b.WriteString(header + "\n")
	b.WriteString("module " + m.Name + "\n")

	for _, t := range m.Types {
		b.WriteString("\n")

		if err := writeType(&b, "type", t); err != nil {
			return "", err
		}
	}

	for _, e := range m.Extends {
		for _, t := range e.Types {
			b.WriteString("\n")

			if err := writeType(&b, "extend type", t); err != nil {
				return "", fmt.Errorf("extending module %q: %w", e.Module, err)
			}
		}
	}

	for _, c := range m.Conditions {
		b.WriteString("\n")
		writeCondition(&b, c)
	}

	return b.String(), nil
}

func writeType(b *strings.Builder, keyword string, t Type) error {
	fmt.Fprintf(b, "%s %s\n", keyword, t.Name)

	if len(t.Relations) == 0 {
		return nil
	}

	b.WriteString("  relations\n")

	for _, r := range t.Relations {
		definition, err := renderRelation(r)
		if err != nil {
			return fmt.Errorf("rendering type %q relation %q: %w", t.Name, r.Name, err)
		}

		fmt.Fprintf(b, "    define %s: %s\n", r.Name, definition)
	}

	return nil
}

func renderRelation(r Relation) (string, error) {
	direct := renderSubjects(r)

	if r.Expression == "" {
		return direct, nil
	}

	e, err := parseExpression(r.Expression)
	if err != nil {
		return "", fmt.Errorf("parsing expression %q: %w", r.Expression, err)
	}

	if direct == "" {
		return e.String(), nil
	}

	if e.operator == "" || e.operator == operatorOr {
		return direct + " or " + e.String(), nil
	}

	return direct + " or (" + e.String() + ")", nil
}

func renderSubjects(r Relation) string {
	if len(r.Subjects) == 0 {
		return ""
	}

	parts := make([]string, 0, len(r.Subjects))

	for _, s := range r.Subjects {
		if r.Condition != "" {
			s += " with " + r.Condition
		}

		parts = append(parts, s)
	}

	return "[" + strings.Join(parts, ", ") + "]"
}

func writeCondition(b *strings.Builder, c Condition) {
	params := make([]string, 0, len(c.Parameters))

	for _, p := range c.Parameters {
		params = append(params, p.Name+": "+p.Type)
	}

	fmt.Fprintf(b, "condition %s(%s) {\n  %s\n}\n", c.Name, strings.Join(params, ", "), strings.TrimSpace(c.Expression))
}

type testDocument struct {
	Name      string     `json:"name"`
	ModelFile string     `json:"model_file"`
	Tests     []testCase `json:"tests"`
}

type testCase struct {
	Name   string      `json:"name"`
	Tuples []testTuple `json:"tuples,omitempty"`
	Check  []testCheck `json:"check"`
}

type testTuple struct {
	User      string          `json:"user"`
	Relation  string          `json:"relation"`
	Object    string          `json:"object"`
	Condition *TupleCondition `json:"condition,omitempty"`
}

type testCheck struct {
	User       string          `json:"user"`
	Object     string          `json:"object"`
	Context    map[string]any  `json:"context,omitempty"`
	Assertions map[string]bool `json:"assertions"`
}

func emitTests(m Module) (string, error) {
	return writeTestDocument(testDocumentOf(m))
}

func testDocumentOf(m Module) testDocument {
	document := testDocument{Name: m.Name, ModelFile: modelFile}

	for _, c := range m.Vectors {
		one := testCase{Name: c.Name}

		for _, t := range c.Tuples {
			one.Tuples = append(one.Tuples, testTuple(t))
		}

		for _, ch := range c.Checks {
			one.Check = append(one.Check, testCheck{
				User:       ch.User,
				Object:     ch.Object,
				Context:    ch.Context,
				Assertions: map[string]bool{ch.Relation: *ch.Expected},
			})
		}

		document.Tests = append(document.Tests, one)
	}

	return document
}

func writeTestDocument(document testDocument) (string, error) {
	var b strings.Builder

	b.WriteString(header + "\n")
	fmt.Fprintf(&b, "name: %s\n", quote(document.Name))
	fmt.Fprintf(&b, "model_file: %s\n", quote(document.ModelFile))
	b.WriteString("tests:\n")

	for _, c := range document.Tests {
		if err := writeCase(&b, c); err != nil {
			return "", fmt.Errorf("writing case %q: %w", c.Name, err)
		}
	}

	return b.String(), nil
}

func writeCase(b *strings.Builder, c testCase) error {
	fmt.Fprintf(b, "  - name: %s\n", quote(c.Name))

	if len(c.Tuples) > 0 {
		b.WriteString("    tuples:\n")
	}

	for _, t := range c.Tuples {
		if err := writeTuple(b, t); err != nil {
			return err
		}
	}

	b.WriteString("    check:\n")

	for _, ch := range c.Check {
		if err := writeCheck(b, ch); err != nil {
			return err
		}
	}

	return nil
}

func writeTuple(b *strings.Builder, t testTuple) error {
	fmt.Fprintf(b, "      - user: %s\n", quote(t.User))
	fmt.Fprintf(b, "        relation: %s\n", quote(t.Relation))
	fmt.Fprintf(b, "        object: %s\n", quote(t.Object))

	if t.Condition == nil {
		return nil
	}

	b.WriteString("        condition:\n")
	fmt.Fprintf(b, "          name: %s\n", quote(t.Condition.Name))

	if len(t.Condition.Context) == 0 {
		return nil
	}

	context, err := flow(t.Condition.Context)
	if err != nil {
		return fmt.Errorf("encoding the context of tuple %s %s %s: %w", t.User, t.Relation, t.Object, err)
	}

	fmt.Fprintf(b, "          context: %s\n", context)

	return nil
}

func writeCheck(b *strings.Builder, ch testCheck) error {
	fmt.Fprintf(b, "      - user: %s\n", quote(ch.User))
	fmt.Fprintf(b, "        object: %s\n", quote(ch.Object))

	if len(ch.Context) > 0 {
		context, err := flow(ch.Context)
		if err != nil {
			return fmt.Errorf("encoding the context of check %s %s: %w", ch.User, ch.Object, err)
		}

		fmt.Fprintf(b, "        context: %s\n", context)
	}

	b.WriteString("        assertions:\n")

	for _, relation := range assertedRelations(ch.Assertions) {
		fmt.Fprintf(b, "          %s: %t\n", quote(relation), ch.Assertions[relation])
	}

	return nil
}

func assertedRelations(assertions map[string]bool) []string {
	names := make([]string, 0, len(assertions))
	for name := range assertions {
		names = append(names, name)
	}

	sort.Strings(names)

	return names
}

func quote(s string) string {
	return strconv.Quote(s)
}

func flow(value map[string]any) (string, error) {
	encoded, err := json.Marshal(value)
	if err != nil {
		return "", err
	}

	return string(encoded), nil
}

type manifest struct {
	Module     string             `json:"module"`
	Schema     string             `json:"schema"`
	Model      string             `json:"model"`
	Tests      string             `json:"tests"`
	Wire       string             `json:"wire"`
	Types      []string           `json:"types"`
	References []manifestExternal `json:"references"`
	Extends    []manifestExternal `json:"extends"`
	Cases      []string           `json:"cases"`
}

type manifestExternal struct {
	Module string   `json:"module"`
	Types  []string `json:"types"`
}

func emitManifest(m Module) (string, error) {
	out := manifest{
		Module:     m.Name,
		Schema:     schemaVersion,
		Model:      modelPath(m),
		Tests:      testsPath(m),
		Wire:       wirePath(m),
		Types:      []string{},
		References: []manifestExternal{},
		Extends:    []manifestExternal{},
		Cases:      []string{},
	}

	for _, t := range m.Types {
		out.Types = append(out.Types, t.Name)
	}

	for _, r := range m.References {
		names := []string{}
		for _, t := range r.Types {
			names = append(names, t.Name)
		}

		out.References = append(out.References, manifestExternal{Module: r.Module, Types: names})
	}

	for _, e := range m.Extends {
		names := []string{}
		for _, t := range e.Types {
			names = append(names, t.Name)
		}

		out.Extends = append(out.Extends, manifestExternal{Module: e.Module, Types: names})
	}

	for _, c := range m.Vectors {
		out.Cases = append(out.Cases, c.Name)
	}

	encoded, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return "", fmt.Errorf("encoding the manifest: %w", err)
	}

	return string(encoded) + "\n", nil
}
