// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package authzgen_test

import (
	"strings"
	"testing"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/authzgen"
)

const playSpec = `module: play
references:
  - module: session
    types:
      - name: character
      - name: session
        relations: [member]
extends:
  - module: session
    types:
      - name: session
        relations:
          - name: turn_owner
            subjects: [character]
types:
  - name: monster
    relations:
      - name: session
        subjects: [session]
      - name: alive
        subjects: ["character:*"]
        condition: monster_alive
      - name: attack
        expression: alive and turn_owner from session
conditions:
  - name: monster_alive
    parameters:
      - name: hp
        type: int
    expression: hp > 0
vectors:
  - name: only the turn owner may attack
    tuples:
      - user: "character:*"
        relation: alive
        object: monster:boar
        condition:
          name: monster_alive
    checks:
      - user: character:alice
        relation: attack
        object: monster:boar
        context:
          hp: 3
        expected: true
      - user: character:bob
        relation: attack
        object: monster:boar
        expected: false
`

const wantPlayModel = `# Code generated by authz-gen (forge-dev-codegen). DO NOT EDIT.
module play

type monster
  relations
    define session: [session]
    define alive: [character:* with monster_alive]
    define attack: alive and turn_owner from session

extend type session
  relations
    define turn_owner: [character]

condition monster_alive(hp: int) {
  hp > 0
}
`

const wantPlayTests = `# Code generated by authz-gen (forge-dev-codegen). DO NOT EDIT.
name: "play"
model_file: "fga.mod"
tests:
  - name: "only the turn owner may attack"
    tuples:
      - user: "character:*"
        relation: "alive"
        object: "monster:boar"
        condition:
          name: "monster_alive"
    check:
      - user: "character:alice"
        object: "monster:boar"
        context: {"hp":3}
        assertions:
          "attack": true
      - user: "character:bob"
        object: "monster:boar"
        assertions:
          "attack": false
`

const wantPlayManifest = `{
  "module": "play",
  "schema": "1.2",
  "model": "zz_generated_play.fga",
  "tests": "zz_generated_play.fga.yaml",
  "types": [
    "monster"
  ],
  "references": [
    {
      "module": "session",
      "types": [
        "character",
        "session"
      ]
    }
  ],
  "extends": [
    {
      "module": "session",
      "types": [
        "session"
      ]
    }
  ],
  "cases": [
    "only the turn owner may attack"
  ]
}
`

func generate(t *testing.T, doc string) map[string]string {
	t.Helper()

	files, err := authzgen.Generate([]byte(doc))
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	byPath := map[string]string{}
	for _, f := range files {
		byPath[f.Path] = f.Content
	}

	return byPath
}

func TestGeneratingAModuleEmitsTheModelTheTestsAndTheManifest(t *testing.T) {
	files, err := authzgen.Generate([]byte(playSpec))
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	got := []string{}
	for _, f := range files {
		got = append(got, f.Path)
	}

	want := "zz_generated_play.fga,zz_generated_play.fga.yaml,zz_generated_authz.json"
	if strings.Join(got, ",") != want {
		t.Fatalf("emitted paths\n got %q\nwant %q", got, want)
	}
}

func TestTheModuleFileCarriesTheModuleLineTheTypesTheExtensionsAndTheConditions(t *testing.T) {
	got := generate(t, playSpec)["zz_generated_play.fga"]
	if got != wantPlayModel {
		t.Fatalf("model\n got:\n%s\nwant:\n%s", got, wantPlayModel)
	}
}

func TestTheTestFileNamesTheCombinedModelAndHoldsOneCheckPerAssertion(t *testing.T) {
	got := generate(t, playSpec)["zz_generated_play.fga.yaml"]
	if got != wantPlayTests {
		t.Fatalf("tests\n got:\n%s\nwant:\n%s", got, wantPlayTests)
	}
}

func TestTheManifestNamesTheModuleItsTypesItsReferencesItsExtensionsAndItsCases(t *testing.T) {
	got := generate(t, playSpec)["zz_generated_authz.json"]
	if got != wantPlayManifest {
		t.Fatalf("manifest\n got:\n%s\nwant:\n%s", got, wantPlayManifest)
	}
}

func TestATypeWithNoRelationsEmitsOneLine(t *testing.T) {
	got := generate(t, "module: session\ntypes:\n  - name: account\n")["zz_generated_session.fga"]

	want := "module session\n\ntype account\n"
	if !strings.HasSuffix(got, want) {
		t.Fatalf("model\n got:\n%s\nwant suffix:\n%s", got, want)
	}
}

func TestSubjectsAndAnOrExpressionRenderOnOneLine(t *testing.T) {
	got := generate(t, `module: docs
types:
  - name: user
  - name: document
    relations:
      - name: owner
        subjects: [user]
      - name: viewer
        subjects: [user, "user:*"]
        expression: owner
`)["zz_generated_docs.fga"]

	if !strings.Contains(got, "define viewer: [user, user:*] or owner\n") {
		t.Fatalf("model\n%s", got)
	}
}

func TestSubjectsAndAnAndExpressionRenderTheExpressionInParentheses(t *testing.T) {
	got := generate(t, `module: docs
types:
  - name: user
  - name: document
    relations:
      - name: owner
        subjects: [user]
      - name: editor
        subjects: [user]
      - name: viewer
        subjects: [user]
        expression: owner and editor
`)["zz_generated_docs.fga"]

	if !strings.Contains(got, "define viewer: [user] or (owner and editor)\n") {
		t.Fatalf("model\n%s", got)
	}
}

func TestATupleContextRendersAsAFlowMappingUnderTheCondition(t *testing.T) {
	got := generate(t, `module: docs
conditions:
  - name: fresh
    parameters:
      - name: grant_time
        type: timestamp
      - name: now
        type: timestamp
    expression: now < grant_time + duration("10m")
types:
  - name: user
  - name: document
    relations:
      - name: viewer
        subjects: [user]
        condition: fresh
vectors:
  - name: a fresh grant views
    tuples:
      - user: user:anne
        relation: viewer
        object: document:d1
        condition:
          name: fresh
          context:
            grant_time: "2026-01-01T00:00:00Z"
    checks:
      - user: user:anne
        relation: viewer
        object: document:d1
        context:
          now: "2026-01-01T00:05:00Z"
        expected: true
`)["zz_generated_docs.fga.yaml"]

	for _, want := range []string{
		"        condition:\n          name: \"fresh\"\n          context: {\"grant_time\":\"2026-01-01T00:00:00Z\"}\n",
		"        context: {\"now\":\"2026-01-01T00:05:00Z\"}\n",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("tests\n%s\nnever held\n%s", got, want)
		}
	}
}

func TestACaseNameWithAQuoteIsQuotedForYaml(t *testing.T) {
	got := generate(t, sessionSpec+`vectors:
  - name: 'the "host" may join'
    checks:
      - user: character:alice
        relation: join
        object: session:s1
        expected: false
`)["zz_generated_session.fga.yaml"]

	if !strings.Contains(got, `  - name: "the \"host\" may join"`) {
		t.Fatalf("tests\n%s", got)
	}
}

func TestAModuleWithoutVectorsEmitsAnEmptyTestList(t *testing.T) {
	got := generate(t, "module: session\ntypes:\n  - name: account\n")["zz_generated_session.fga.yaml"]

	if !strings.HasSuffix(got, "tests:\n") {
		t.Fatalf("tests\n%s", got)
	}
}

func TestEveryEmittedPathIsZzGenerated(t *testing.T) {
	for path := range generate(t, playSpec) {
		if !strings.HasPrefix(path, "zz_generated") {
			t.Errorf("%s is not named zz_generated", path)
		}
	}
}
