// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/surface"
)

// NewHandlers wires the generate tool: the model's surface.commands decide
// the subcommands, cobra does the dispatch, and the answer is files only -
// forge-dev core writes them. The emitted program keeps the builtin cli
// cell's author and behavior contract, so swapping the generator never
// changes the handlers file or what the program does.
func NewHandlers() Handlers {
	return Handlers{
		Generate: func(_ context.Context, input GenerateInput) (*GenerateOutput, error) {
			if input.Kind != "cli" {
				return nil, fmt.Errorf("emitting %q: cli-go-cobra fills the cli cell only", input.Kind)
			}

			if input.Language != "" && input.Language != "go" {
				return nil, fmt.Errorf("emitting for %q: cli-go-cobra generates go only", input.Language)
			}

			commands, err := surface.Commands(input.Surface)
			if err != nil {
				return nil, fmt.Errorf("reading surface.commands for %q: %w", input.Name, err)
			}

			pkg := input.PackageName
			if pkg == "" {
				pkg = "main"
			}

			var buf bytes.Buffer
			if err := cobraTmpl.Execute(&buf, map[string]any{
				"Name":        input.Name,
				"Version":     input.Version,
				"Description": input.Description,
				"Package":     pkg,
				"Checksum":    input.Checksum,
				"Commands":    commands,
			}); err != nil {
				return nil, fmt.Errorf("rendering the cobra dispatcher for %q: %w", input.Name, err)
			}

			formatted, err := format.Source(buf.Bytes())
			if err != nil {
				return nil, fmt.Errorf("formatting the cobra dispatcher for %q: %w", input.Name, err)
			}

			return &GenerateOutput{
				Files: []GeneratedFile{{Path: "zz_generated.cli.go", Content: string(formatted)}},
			}, nil
		},
	}
}

var cobraTmpl = template.Must(template.New("cobra").Parse(`// Code generated by cli-go-cobra (forge-dev-codegen). DO NOT EDIT.
// Source: forge-dev.yaml
// SourceChecksum: {{ .Checksum }}

package {{ .Package }}

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// {{ .Name }} v{{ .Version }}: a cli kind program dispatched by cobra. The
// author contract is the builtin cell's, so the generator is swappable:
//
//	func NewCLIHandlers() CLIHandlers {
//		return CLIHandlers{
{{- range .Commands }}
//			{{ .GoName }}: func(args []string) int { ... },
{{- end }}
//		}
//	}

// CLIHandlers holds one handler per declared command. Every field is
// required: a nil handler fails at dispatch, loud, naming the command.
type CLIHandlers struct {
{{- range .Commands }}
	// {{ .GoName }} runs the {{ .Name }} command. {{ .Description }}
	{{ .GoName }} func(args []string) int
{{- end }}
}

// Dispatch routes args through cobra and answers the process exit code.
// Flag parsing is disabled on every subcommand: the handler owns its args,
// exactly as the builtin cell hands them over.
func Dispatch(handlers CLIHandlers, args []string) int {
	code := 0

	root := &cobra.Command{
		Use:           "{{ .Name }}",
		Short:         "{{ .Description }}",
		Version:       "{{ .Version }}",
		SilenceUsage:  true,
		SilenceErrors: true,
	}
{{ range .Commands }}
	root.AddCommand(&cobra.Command{
		Use:                "{{ .Name }}",
		Short:              "{{ .Description }}",
		DisableFlagParsing: true,
		RunE: func(_ *cobra.Command, commandArgs []string) error {
			if handlers.{{ .GoName }} == nil {
				return fmt.Errorf("command {{ .Name }} has no handler")
			}

			code = handlers.{{ .GoName }}(commandArgs)

			return nil
		},
	})
{{ end }}
	root.SetArgs(args)

	if err := root.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "{{ .Name }}: %v\n", err)

		return 2
	}

	return code
}

func main() {
	os.Exit(Dispatch(NewCLIHandlers(), os.Args[1:]))
}
`))
