// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"context"
	"fmt"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/surface"
)

// NewHandlers wires the generate tool: the model's layout.commands decide
// the subcommands, typer does the dispatch. The emitted module keeps the
// cli cell's behavior contract - raw args to the handler, exit codes pass
// through, an unknown command exits 2 naming itself.
func NewHandlers() Handlers {
	return Handlers{
		Generate: func(_ context.Context, input GenerateInput) (*GenerateOutput, error) {
			if input.Kind != "cli" {
				return nil, fmt.Errorf("emitting %q: cli-python-typer fills the cli cell only", input.Kind)
			}

			if input.Language != "python" {
				return nil, fmt.Errorf("emitting for %q: cli-python-typer generates python only", input.Language)
			}

			commands, err := surface.Commands(input.Layout)
			if err != nil {
				return nil, fmt.Errorf("reading layout.commands for %q: %w", input.Name, err)
			}

			var buf bytes.Buffer
			if err := typerTmpl.Execute(&buf, map[string]any{
				"Name":        input.Name,
				"Version":     input.Version,
				"Description": input.Description,
				"Checksum":    input.Checksum,
				"Commands":    commands,
			}); err != nil {
				return nil, fmt.Errorf("rendering the typer dispatcher for %q: %w", input.Name, err)
			}

			return &GenerateOutput{
				Files: []GeneratedFile{{Path: "zz_generated_cli.py", Content: buf.String()}},
			}, nil
		},
	}
}

var typerTmpl = template.Must(template.New("typer").Parse(`# Code generated by cli-python-typer (forge-dev-codegen). DO NOT EDIT.
# Source: forge-dev.yaml
# SourceChecksum: {{ .Checksum }}

"""{{ .Name }} v{{ .Version }}: a cli kind program dispatched by typer.

The author writes new_cli_handlers() in handlers.py beside this module; the
behavior contract is every cli cell's - raw args to the handler, exit codes
pass through, an unknown command exits 2 naming itself.
"""

import sys

import typer
from typer.core import TyperGroup

try:  # typer vendors click from 0.20 on; older typer uses the real one.
    from typer._click import exceptions as click_exceptions
except ImportError:  # pragma: no cover - depends on the installed typer
    from click import exceptions as click_exceptions

from handlers import new_cli_handlers


class LoudGroup(TyperGroup):
    """Names an unknown command the way every cli cell does."""

    def resolve_command(self, ctx, args):
        try:
            return super().resolve_command(ctx, args)
        except click_exceptions.UsageError as e:
            raise click_exceptions.UsageError(f'unknown command "{args[0]}"') from e


app = typer.Typer(
    cls=LoudGroup,
    add_completion=False,
    rich_markup_mode=None,
    help="{{ .Description }}",
)

_handlers = new_cli_handlers()

_RAW = {"allow_extra_args": True, "ignore_unknown_options": True}

{{ range .Commands }}
@app.command(name="{{ .Name }}", context_settings=_RAW)
def {{ .SnakeName }}(ctx: typer.Context) -> None:
    """{{ .Description }}"""
    handler = _handlers.get("{{ .Name }}")
    if handler is None:
        print('{{ $.Name }}: command "{{ .Name }}" has no handler', file=sys.stderr)
        raise typer.Exit(2)
    raise typer.Exit(handler(list(ctx.args)))

{{ end }}
if __name__ == "__main__":
    app()
`))
