// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml
// SourceChecksum: sha256:97760d0efe7517065e5ca6f6df84a609c101f5e3781db4554a5603852f5763d4

package main

import (
	"github.com/alexandremahdhaoui/forge/pkg/enginedocs"
	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
)

// docsConfig is the configuration for documentation tools.
var docsConfig = &enginedocs.Config{
	EngineName:   "grpc-rust-tonic",
	LocalDir:     "cmd/grpc-rust-tonic/docs",
	BaseURL:      "https://raw.githubusercontent.com/alexandremahdhaoui/forge-dev-codegen/refs/heads/main",
	RequiredDocs: []string{"usage", "schema"},
}

// RegisterDocsMCPTools registers the docs-list and docs-get MCP tools.
func RegisterDocsMCPTools(server *mcpserver.Server) error {
	return enginedocs.RegisterDocsTools(server, *docsConfig)
}
