// Code generated by hexagonal-rust (forge-dev-codegen). DO NOT EDIT.

use std::net::SocketAddr;
use std::sync::Arc;

use axum::Router;
use tokio::net::TcpListener;

use crate::controller::GreetingController;

pub struct HttpDriver {
    pub controller: Arc<dyn GreetingController + Send + Sync>,
    pub address: SocketAddr,
}

impl HttpDriver {
    pub async fn serve(self) {
        let router = Router::new();
        let listener = TcpListener::bind(self.address).await.unwrap();
        axum::serve(listener, router).await.unwrap();
    }
}
