// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package hexrust

import (
	"bytes"
	"fmt"
	"path"
	"sort"
	"strings"
	"text/template"
)

const header = "// Code generated by hexagonal-rust (forge-dev-codegen). DO NOT EDIT."

type Options struct {
	Service      string
	CoreDir      string
	AppDir       string
	Side         string
	ExtraModules []ExtraModule
}

type ExtraModule struct {
	Layer  string
	Module string
}

var extraModuleLayers = map[string]string{
	"types":      "core",
	"port":       "core",
	"controller": "core",
	"hand":       "core",
	"adapter":    "app",
	"driver":     "app",
}

func checkExtraModules(modules []ExtraModule) error {
	for _, m := range modules {
		if _, ok := extraModuleLayers[m.Layer]; !ok {
			return fmt.Errorf("mounting extra module %q: layer %q is unknown, use %s", m.Module, m.Layer, extraModuleLayerList())
		}

		if !rustAndSQLIdent.MatchString(m.Module) {
			return fmt.Errorf("mounting extra module %q on layer %q: %q is not a name Rust can spell as a module", m.Module, m.Layer, m.Module)
		}
	}

	return nil
}

func extraModuleLayerList() string {
	names := make([]string, 0, len(extraModuleLayers))
	for name := range extraModuleLayers {
		names = append(names, name)
	}

	sort.Strings(names)

	return strings.Join(names, ", ")
}

func ExtraModulesFromSurface(surface map[string]interface{}) ([]ExtraModule, error) {
	raw, ok := surface["extraModules"]
	if !ok {
		return nil, nil
	}

	entries, ok := raw.([]interface{})
	if !ok {
		return nil, fmt.Errorf("reading extraModules: it is a list of layer and module pairs")
	}

	modules := make([]ExtraModule, 0, len(entries))

	for i, entry := range entries {
		m, ok := entry.(map[string]interface{})
		if !ok {
			return nil, fmt.Errorf("reading extraModules entry %d: it is not an object", i)
		}

		layer, _ := m["layer"].(string)
		module, _ := m["module"].(string)

		if layer == "" || module == "" {
			return nil, fmt.Errorf("reading extraModules entry %d: layer and module are both required", i)
		}

		modules = append(modules, ExtraModule{Layer: layer, Module: module})
	}

	return modules, nil
}

type File struct {
	Path      string
	Content   string
	WriteOnce bool
}

func Generate(doc []byte, opts Options) ([]File, error) {
	if opts.Service == "" {
		return nil, fmt.Errorf("emitting the skeleton: the service name is required")
	}

	if err := checkName("service", opts.Service); err != nil {
		return nil, fmt.Errorf("emitting the skeleton: %w", err)
	}

	if opts.CoreDir == "" {
		opts.CoreDir = "core"
	}

	if opts.AppDir == "" {
		opts.AppDir = "app"
	}

	if opts.Side != "" && opts.Side != "core" && opts.Side != "app" {
		return nil, fmt.Errorf("emitting the skeleton: side must be core, app or empty, got %q", opts.Side)
	}

	if err := checkExtraModules(opts.ExtraModules); err != nil {
		return nil, fmt.Errorf("emitting the skeleton: %w", err)
	}

	spec, err := Parse(doc)
	if err != nil {
		return nil, err
	}

	v := buildView(spec, opts)
	core := path.Join(opts.CoreDir, "src")
	app := path.Join(opts.AppDir, "src")

	files := []File{}

	add := func(side, p, name string, data any, writeOnce bool) error {
		if opts.Side != "" && opts.Side != side {
			return nil
		}

		content, err := render(name, data)
		if err != nil {
			return err
		}

		files = append(files, File{Path: p, Content: content, WriteOnce: writeOnce})

		return nil
	}

	steps := []func() error{
		func() error { return add("core", path.Join(core, "lib.rs"), "core_lib", v, false) },
		func() error { return add("core", path.Join(core, "zz_generated_hand.rs"), "core_hand", v, false) },
		func() error {
			return add("core", path.Join(core, "types", "zz_generated_mod.rs"), "types_mod", v, false)
		},
		func() error { return add("core", path.Join(core, "port", "zz_generated_mod.rs"), "port_mod", v, false) },
		func() error {
			return add("core", path.Join(core, "controller", "zz_generated_mod.rs"), "controller_mod", v, false)
		},
		func() error { return add("app", path.Join(app, "lib.rs"), "app_lib", v, false) },
		func() error {
			return add("app", path.Join(app, "adapter", "zz_generated_mod.rs"), "adapter_mod", v, false)
		},
		func() error {
			return add("app", path.Join(app, "driver", "zz_generated_mod.rs"), "driver_mod", v, false)
		},
		func() error { return add("app", path.Join(app, "driver", "zz_generated_wire.rs"), "wire", v, false) },
		func() error {
			return add("app", path.Join(app, "driver", "zz_generated_http_driver.rs"), "http_driver", v, false)
		},
		func() error {
			return add("app", path.Join(app, "bin", v.Service+"-server.rs"), "server_main", v, false)
		},
	}

	for _, t := range v.Types {
		t := t
		steps = append(steps, func() error {
			return add("core", path.Join(core, "types", "zz_generated_"+t.Snake+".rs"), "type", map[string]any{"Header": header, "Type": t}, false)
		})
	}

	for _, s := range v.Stores {
		s := s
		steps = append(steps,
			func() error {
				return add("core", path.Join(core, "port", "zz_generated_"+s.PortSnake+".rs"), "port", map[string]any{"Header": header, "Store": s}, false)
			},
			func() error {
				return add("app", path.Join(app, "adapter", "zz_generated_"+s.Snake+"_sqlite.rs"), "sqlite", map[string]any{"Header": header, "Store": s, "CoreCrate": v.CoreCrate}, false)
			},
		)
	}

	for _, c := range v.Controllers {
		c := c
		steps = append(steps,
			func() error {
				return add("core", path.Join(core, "controller", "zz_generated_"+c.Snake+"_controller.rs"), "controller", map[string]any{"Header": header, "Controller": c}, false)
			},
			func() error {
				return add("core", path.Join(core, "hand", c.Snake+"_controller.rs"), "hand", map[string]any{"Controller": c}, true)
			},
		)
	}

	for _, step := range steps {
		if err := step(); err != nil {
			return nil, err
		}
	}

	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })

	return files, nil
}

func render(name string, data any) (string, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", fmt.Errorf("rendering %s: %w", name, err)
	}

	return buf.String(), nil
}

var templates = template.Must(template.New("hexrust").Parse(`
{{- define "core_lib" -}}
{{ .Header }}

#[path = "types/zz_generated_mod.rs"]
pub mod types;
#[path = "port/zz_generated_mod.rs"]
pub mod port;
#[path = "controller/zz_generated_mod.rs"]
pub mod controller;
#[path = "zz_generated_hand.rs"]
pub mod hand;
{{ end -}}

{{- define "core_hand" -}}
{{ .Header }}
{{ range .Controllers }}
#[path = "hand/{{ .Snake }}_controller.rs"]
pub mod {{ .Snake }}_controller;
{{ end -}}
{{ range .ExtraHand }}
#[path = "hand/{{ . }}.rs"]
pub mod {{ . }};
{{ end -}}
{{ end -}}

{{- define "types_mod" -}}
{{ .Header }}
{{ range .Types }}
#[path = "zz_generated_{{ .Snake }}.rs"]
pub mod {{ .Snake }};
{{ end -}}
{{ range .ExtraTypes }}
pub mod {{ . }};
{{ end -}}
{{ end -}}

{{- define "port_mod" -}}
{{ .Header }}
{{ range .Stores }}
#[path = "zz_generated_{{ .PortSnake }}.rs"]
pub mod {{ .PortSnake }};
{{ end -}}
{{ range .ExtraPort }}
pub mod {{ . }};
{{ end -}}
{{ end -}}

{{- define "controller_mod" -}}
{{ .Header }}
{{ range .Controllers }}
#[path = "zz_generated_{{ .Snake }}_controller.rs"]
pub mod {{ .Snake }}_controller;
{{ end -}}
{{ range .ExtraController }}
#[path = "zz_generated_{{ . }}.rs"]
pub mod {{ . }};
{{ end -}}
{{ end -}}

{{- define "type" -}}
{{ .Header }}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct {{ .Type.Name }} {
{{- range .Type.Fields }}
{{- if .Renamed }}
    #[serde(rename = "{{ .Name }}")]
{{- end }}
{{- if .Optional }}
    #[serde(default, skip_serializing_if = "Option::is_none")]
{{- end }}
    pub {{ .Ident }}: {{ .CoreType }},
{{- end }}
}
{{ end -}}

{{- define "port" -}}
{{ .Header }}

use crate::types::{{ .Store.Snake }}::{{ .Store.Name }};

#[derive(Debug, thiserror::Error)]
pub enum {{ .Store.Port }}Error {
    #[error("putting {{ .Store.Snake }} {id:?}")]
    Put {
        id: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
    #[error("getting {{ .Store.Snake }} {id:?}")]
    Get {
        id: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync>,
    },
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ .Store.Port }}: Send + Sync {
    fn put(&self, v: {{ .Store.Name }}) -> Result<(), {{ .Store.Port }}Error>;
    fn get(&self, id: &str) -> Result<Option<{{ .Store.Name }}>, {{ .Store.Port }}Error>;
}

impl<T: {{ .Store.Port }} + ?Sized> {{ .Store.Port }} for std::sync::Arc<T> {
    fn put(&self, v: {{ .Store.Name }}) -> Result<(), {{ .Store.Port }}Error> {
        (**self).put(v)
    }

    fn get(&self, id: &str) -> Result<Option<{{ .Store.Name }}>, {{ .Store.Port }}Error> {
        (**self).get(id)
    }
}
{{ end -}}

{{- define "controller" -}}
{{ .Header }}
{{ $c := .Controller }}
{{ range $c.Ports -}}
use crate::port::{{ .PortSnake }}::{{ "{" }}{{ .Port }}, {{ .Port }}Error{{ "}" }};
{{ end -}}
{{ range $c.TypeImports -}}
use crate::types::{{ .Snake }}::{{ .Name }};
{{ end }}
#[derive(Debug, thiserror::Error)]
pub enum {{ $c.Pascal }}ControllerError {
{{- range $c.Ports }}
    #[error("reaching {{ .Snake }} store for {id:?}")]
    {{ .Port }} {
        id: String,
        #[source]
        source: {{ .Port }}Error,
    },
{{- end }}
    #[error("finding {{ $c.Snake }} {id:?}: not found")]
    NotFound { id: String },
    #[error("validating {field:?}: {reason}")]
    Invalid { field: String, reason: String },
    #[error("running {operation:?}: not implemented")]
    NotImplemented { operation: String },
}

#[cfg_attr(test, mockall::automock)]
pub trait {{ $c.Pascal }}Controller: Send + Sync {
{{- range $c.Ops }}
    fn {{ .Ident }}(&self{{ if .TraitArgs }}, {{ .TraitArgs }}{{ end }}) -> Result<{{ .ReturnType }}, {{ $c.Pascal }}ControllerError>;
{{- end }}
}

pub struct {{ $c.Pascal }}ControllerImpl{{ $c.Generics }} {
{{- range $c.Ports }}
    {{ .PortSnake }}: {{ .Generic }},
{{- end }}
}

impl{{ $c.Generics }} {{ $c.Pascal }}ControllerImpl{{ $c.GenericArgs }} {
    pub fn new({{ range $i, $p := $c.Ports }}{{ if $i }}, {{ end }}{{ $p.PortSnake }}: {{ $p.Generic }}{{ end }}) -> Self {
        Self {{ "{" }}{{ range $i, $p := $c.Ports }}{{ if $i }},{{ end }} {{ $p.PortSnake }}{{ end }} {{ "}" }}
    }
}

impl{{ $c.Generics }} {{ $c.Pascal }}Controller for {{ $c.Pascal }}ControllerImpl{{ $c.GenericArgs }} {
{{- range $c.Ops }}
    fn {{ .Ident }}(&self{{ if .TraitArgs }}, {{ .TraitArgs }}{{ end }}) -> Result<{{ .ReturnType }}, {{ $c.Pascal }}ControllerError> {
        crate::hand::{{ $c.Snake }}_controller::{{ .Ident }}({{ .HandCall }})
    }
{{ end -}}
}
{{ end -}}

{{- define "hand" -}}
{{ $c := .Controller -}}
use crate::controller::{{ $c.Snake }}_controller::{{ $c.Pascal }}ControllerError;
{{ range $c.Ports -}}
use crate::port::{{ .PortSnake }}::{{ .Port }};
{{ end -}}
{{ range $c.TypeImports -}}
use crate::types::{{ .Snake }}::{{ .Name }};
{{ end }}
{{- range $c.Ops }}
pub fn {{ .Ident }}{{ .HandGenerics }}({{ .HandParams }}) -> Result<{{ .ReturnType }}, {{ $c.Pascal }}ControllerError> {
{{- if .Unused }}
    let _ = {{ .Unused }};
{{- end }}
    Err({{ $c.Pascal }}ControllerError::NotImplemented {
        operation: "{{ .Ident }}".to_string(),
    })
}
{{ end -}}
{{ end -}}

{{- define "app_lib" -}}
{{ .Header }}

#[path = "adapter/zz_generated_mod.rs"]
pub mod adapter;
#[path = "driver/zz_generated_mod.rs"]
pub mod driver;
{{ end -}}

{{- define "adapter_mod" -}}
{{ .Header }}
{{ range .Stores }}
#[path = "zz_generated_{{ .Snake }}_sqlite.rs"]
pub mod {{ .Snake }}_sqlite;
{{ end -}}
{{ range .ExtraAdapter }}
pub mod {{ . }};
{{ end -}}
{{ end -}}

{{- define "driver_mod" -}}
{{ .Header }}

#[path = "zz_generated_wire.rs"]
pub mod wire;
#[path = "zz_generated_http_driver.rs"]
pub mod http_driver;
{{ range .ExtraDriver }}
pub mod {{ . }};
{{ end -}}
{{ end -}}

{{- define "sqlite" -}}
{{ .Header }}
{{ $s := .Store }}
use std::sync::Mutex;

use rusqlite::OptionalExtension;
use {{ .CoreCrate }}::port::{{ $s.PortSnake }}::{{ "{" }}{{ $s.Port }}, {{ $s.Port }}Error{{ "}" }};
use {{ .CoreCrate }}::types::{{ $s.Snake }}::{{ $s.Name }};

const SCHEMA: &str = "CREATE TABLE IF NOT EXISTS {{ $s.Snake }} (id TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit (at TEXT NOT NULL, table_name TEXT NOT NULL, key TEXT NOT NULL, op TEXT NOT NULL, before TEXT, after TEXT);";

#[derive(Debug, thiserror::Error)]
pub enum {{ $s.Name }}SqliteError {
    #[error("opening sqlite {path:?}")]
    Open {
        path: String,
        #[source]
        source: rusqlite::Error,
    },
    #[error("creating the schema in sqlite {path:?}")]
    Schema {
        path: String,
        #[source]
        source: rusqlite::Error,
    },
    #[error("locking the sqlite connection: poisoned")]
    Poisoned,
    #[error("running sql for {{ $s.Snake }} {id:?}")]
    Sql {
        id: String,
        #[source]
        source: rusqlite::Error,
    },
    #[error("encoding {{ $s.Snake }} {id:?}")]
    Json {
        id: String,
        #[source]
        source: serde_json::Error,
    },
}

pub struct {{ $s.Name }}SqliteStore {
    connection: Mutex<rusqlite::Connection>,
}

impl {{ $s.Name }}SqliteStore {
    pub fn open(path: &str) -> Result<Self, {{ $s.Name }}SqliteError> {
        let connection = rusqlite::Connection::open(path).map_err(|source| {{ $s.Name }}SqliteError::Open {
            path: path.to_string(),
            source,
        })?;
        connection
            .execute_batch(SCHEMA)
            .map_err(|source| {{ $s.Name }}SqliteError::Schema {
                path: path.to_string(),
                source,
            })?;
        Ok(Self {
            connection: Mutex::new(connection),
        })
    }

    fn put_row(&self, v: &{{ $s.Name }}) -> Result<(), {{ $s.Name }}SqliteError> {
        let id = v.id.clone();
        let sql = |source| {{ $s.Name }}SqliteError::Sql {
            id: id.clone(),
            source,
        };
        let after = serde_json::to_string(v).map_err(|source| {{ $s.Name }}SqliteError::Json {
            id: id.clone(),
            source,
        })?;
        let mut connection = self.connection.lock().map_err(|_| {{ $s.Name }}SqliteError::Poisoned)?;
        let tx = connection.transaction().map_err(sql)?;
        let before: Option<String> = tx
            .query_row("SELECT body FROM {{ $s.Snake }} WHERE id = ?1", [&id], |row| row.get(0))
            .optional()
            .map_err(sql)?;
        tx.execute(
            "INSERT INTO {{ $s.Snake }} (id, body) VALUES (?1, ?2) ON CONFLICT(id) DO UPDATE SET body = excluded.body",
            (&id, &after),
        )
        .map_err(sql)?;
        tx.execute(
            "INSERT INTO audit (at, table_name, key, op, before, after) VALUES (datetime('now'), '{{ $s.Snake }}', ?1, 'put', ?2, ?3)",
            (&id, &before, &after),
        )
        .map_err(sql)?;
        tx.commit().map_err(sql)?;
        Ok(())
    }

    fn get_row(&self, id: &str) -> Result<Option<{{ $s.Name }}>, {{ $s.Name }}SqliteError> {
        let connection = self.connection.lock().map_err(|_| {{ $s.Name }}SqliteError::Poisoned)?;
        let body: Option<String> = connection
            .query_row("SELECT body FROM {{ $s.Snake }} WHERE id = ?1", [id], |row| row.get(0))
            .optional()
            .map_err(|source| {{ $s.Name }}SqliteError::Sql {
                id: id.to_string(),
                source,
            })?;
        body.map(|text| serde_json::from_str(&text))
            .transpose()
            .map_err(|source| {{ $s.Name }}SqliteError::Json {
                id: id.to_string(),
                source,
            })
    }
}

impl {{ $s.Port }} for {{ $s.Name }}SqliteStore {
    fn put(&self, v: {{ $s.Name }}) -> Result<(), {{ $s.Port }}Error> {
        let id = v.id.clone();
        self.put_row(&v).map_err(|source| {{ $s.Port }}Error::Put {
            id,
            source: Box::new(source),
        })
    }

    fn get(&self, id: &str) -> Result<Option<{{ $s.Name }}>, {{ $s.Port }}Error> {
        self.get_row(id).map_err(|source| {{ $s.Port }}Error::Get {
            id: id.to_string(),
            source: Box::new(source),
        })
    }
}
{{ end -}}

{{- define "wire" -}}
{{ .Header }}
{{ $core := .CoreCrate }}
{{ range .Types -}}
use {{ $core }}::types::{{ .Snake }}::{{ .Name }};
{{ end }}
{{- range .Types }}
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct {{ .Name }}Wire {
{{- range .Fields }}
{{- if .Renamed }}
    #[serde(rename = "{{ .Name }}")]
{{- end }}
{{- if .Optional }}
    #[serde(default, skip_serializing_if = "Option::is_none")]
{{- end }}
    pub {{ .Ident }}: {{ .WireType }},
{{- end }}
}

impl From<{{ .Name }}Wire> for {{ .Name }} {
    fn from(w: {{ .Name }}Wire) -> Self {
        Self {
{{- range .Fields }}
            {{ .Ident }}: {{ .ToCore }},
{{- end }}
        }
    }
}

impl From<{{ .Name }}> for {{ .Name }}Wire {
    fn from(v: {{ .Name }}) -> Self {
        Self {
{{- range .Fields }}
            {{ .Ident }}: {{ .ToWire }},
{{- end }}
        }
    }
}
{{ end -}}
{{ end -}}

{{- define "http_driver" -}}
{{ .Header }}
{{ $v := . }}
use std::sync::Arc;

use axum::extract::{Json, {{ if .UsesPath }}Path, {{ end }}State};
use axum::http::StatusCode;
use axum::routing;
use axum::Router;
{{ range .Controllers -}}
use {{ $v.CoreCrate }}::controller::{{ .Snake }}_controller::{{ "{" }}{{ .Pascal }}Controller, {{ .Pascal }}ControllerError{{ "}" }};
{{ end }}
{{- range .WireImports }}
use super::wire::{{ . }}Wire;
{{- end }}

#[derive(Debug, serde::Serialize)]
pub struct RejectionWire {
    pub r#type: String,
    pub message: String,
}

type Rejection = (StatusCode, Json<RejectionWire>);

fn reject(status: StatusCode, kind: &str, message: String) -> Rejection {
    (
        status,
        Json(RejectionWire {
            r#type: kind.to_string(),
            message,
        }),
    )
}

#[derive(Clone)]
pub struct HttpDriver {
{{- range .Controllers }}
    {{ .Snake }}_controller: Arc<dyn {{ .Pascal }}Controller>,
{{- end }}
}

impl HttpDriver {
    pub fn new({{ range $i, $c := .Controllers }}{{ if $i }}, {{ end }}{{ $c.Snake }}_controller: Arc<dyn {{ $c.Pascal }}Controller>{{ end }}) -> Self {
        Self {{ "{" }}{{ range $i, $c := .Controllers }}{{ if $i }},{{ end }} {{ $c.Snake }}_controller{{ end }} {{ "}" }}
    }

    pub fn router(self) -> Router {
        Router::new()
{{- range .Routes }}
            .route("{{ .Path }}", routing::{{ .MethodLower }}({{ .Ident }}))
{{- end }}
            .with_state(self)
    }
}
{{ range .Controllers }}{{ $c := . }}
fn reject_{{ $c.Snake }}(error: {{ $c.Pascal }}ControllerError, invalid: StatusCode) -> Rejection {
    match error {
{{- range $c.Ports }}
        {{ $c.Pascal }}ControllerError::{{ .Port }} { .. } => {
            eprintln!("{error:?}");
            reject(StatusCode::INTERNAL_SERVER_ERROR, "runtime", "internal error".to_string())
        }
{{- end }}
        {{ $c.Pascal }}ControllerError::NotFound { .. } => reject(StatusCode::NOT_FOUND, "semantic", error.to_string()),
        {{ $c.Pascal }}ControllerError::Invalid { .. } => reject(invalid, "validation", error.to_string()),
        {{ $c.Pascal }}ControllerError::NotImplemented { .. } => reject(StatusCode::NOT_IMPLEMENTED, "runtime", error.to_string()),
    }
}
{{ end }}
{{- range .Routes }}
async fn {{ .Ident }}({{ .Extractors }}) -> {{ .HandlerReturn }} {
{{- if .Response }}
    let out = driver
        .{{ .ControllerSnake }}_controller
        .{{ .Ident }}({{ .ControllerCall }})
        .map_err(|error| reject_{{ .ControllerSnake }}(error, {{ .InvalidStatusExpr }}))?;
{{- else }}
    driver
        .{{ .ControllerSnake }}_controller
        .{{ .Ident }}({{ .ControllerCall }})
        .map_err(|error| reject_{{ .ControllerSnake }}(error, {{ .InvalidStatusExpr }}))?;
{{- end }}
    Ok({{ .OkExpr }})
}
{{ end -}}
{{ end -}}

{{- define "server_main" -}}
{{ .Header }}

use std::sync::Arc;

use anyhow::Context;
{{ range .UsedStores -}}
use {{ $.AppCrate }}::adapter::{{ .Snake }}_sqlite::{{ .Name }}SqliteStore;
{{ end -}}
use {{ .AppCrate }}::driver::http_driver::HttpDriver;
{{ range .Controllers -}}
use {{ $.CoreCrate }}::controller::{{ .Snake }}_controller::{{ .Pascal }}ControllerImpl;
{{ end }}
#[tokio::main]
async fn main() {
    if let Err(error) = run().await {
        eprintln!("{{ .Service }}-server: {error:#}");
        std::process::exit(1);
    }
}

async fn run() -> anyhow::Result<()> {
{{- range .UsedStores }}
    let {{ .Snake }}_path = std::env::var("SONGE_STORE_{{ .Upper }}_PATH").unwrap_or_else(|_| ":memory:".to_string());
    let {{ .PortSnake }} = Arc::new(
        {{ .Name }}SqliteStore::open(&{{ .Snake }}_path)
            .with_context(|| format!("opening {{ .Snake }} store {{ "{" }}{{ .Snake }}_path:?{{ "}" }}"))?,
    );
{{- end }}
{{- range .Controllers }}
    let {{ .Snake }}_controller = Arc::new({{ .Pascal }}ControllerImpl::new({{ range $i, $p := .Ports }}{{ if $i }}, {{ end }}{{ $p.PortSnake }}.clone(){{ end }}));
{{- end }}
    let driver = HttpDriver::new({{ range $i, $c := .Controllers }}{{ if $i }}, {{ end }}{{ $c.Snake }}_controller{{ end }});
    let addr = std::env::var("{{ .ServiceUpper }}_ADDR").unwrap_or_else(|_| "127.0.0.1:0".to_string());
    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .with_context(|| format!("binding {addr}"))?;
    let port = listener
        .local_addr()
        .context("reading the bound port")?
        .port();
    println!("LISTENING {port}");
    axum::serve(listener, driver.router())
        .await
        .context("serving")?;
    Ok(())
}
{{ end -}}
`))
