// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package hexrust

import (
	"bytes"
	"fmt"
	"path"
	"sort"
	"text/template"

	"github.com/alexandremahdhaoui/forge-dev-codegen/internal/restrust"
)

const header = "// Code generated by hexagonal-rust (forge-dev-codegen). DO NOT EDIT."

const Generator = "hexagonal-rust (forge-dev-codegen)"

var reservedCellNames = map[string]bool{
	"adapter": true, "bin": true, "config": true, "controller": true,
	"driver": true, "port": true, "types": true,
}

type Options struct {
	Service string
	Cell    string
	Cells   []string
}

type File struct {
	Path    string
	Content string
}

func checkCells(cells []string) error {
	seen := map[string]bool{}

	for _, cell := range cells {
		if !restrust.IsModuleName(cell) {
			return fmt.Errorf("mounting cell %q: it is not a name Rust can spell as a module, use lowercase letters, digits and underscores and start with a letter", cell)
		}

		if reservedCellNames[cell] {
			return fmt.Errorf("mounting cell %q: the crate root already owns that module, name the cell something else", cell)
		}

		if seen[cell] {
			return fmt.Errorf("mounting cell %q: it is listed twice", cell)
		}

		seen[cell] = true
	}

	return nil
}

func CellsFromLayout(layout map[string]interface{}) ([]string, error) {
	raw, ok := layout["cells"]
	if !ok {
		return nil, nil
	}

	entries, ok := raw.([]interface{})
	if !ok {
		return nil, fmt.Errorf("reading cells: it is a list of module directory names under src")
	}

	names := make([]string, 0, len(entries))

	for i, entry := range entries {
		name, ok := entry.(string)
		if !ok || name == "" {
			return nil, fmt.Errorf("reading cells entry %d: it is a name, not %v", i, entry)
		}

		names = append(names, name)
	}

	return names, nil
}

func Generate(doc []byte, opts Options) ([]File, error) {
	if opts.Service == "" {
		return nil, fmt.Errorf("emitting the skeleton: the service name is required")
	}

	if err := checkCells(opts.Cells); err != nil {
		return nil, fmt.Errorf("emitting the skeleton: %w", err)
	}

	restFiles, err := restrust.Generate(doc, restrust.Options{
		Service:   opts.Service,
		Cell:      opts.Cell,
		Root:      true,
		Header:    header,
		Generator: Generator,
	})
	if err != nil {
		return nil, err
	}

	cells := append([]string{}, opts.Cells...)
	sort.Strings(cells)

	lib, err := render("lib", map[string]any{"Header": header, "Cells": cells})
	if err != nil {
		return nil, err
	}

	files := []File{{Path: path.Join("src", "lib.rs"), Content: lib}}

	for _, f := range restFiles {
		files = append(files, File{Path: f.Path, Content: f.Content})
	}

	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })

	return files, nil
}

func render(name string, data any) (string, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", fmt.Errorf("rendering %s: %w", name, err)
	}

	return buf.String(), nil
}

var templates = template.Must(template.New("hexrust").Parse(`
{{- define "lib" -}}
{{ .Header }}

pub mod adapter;
pub mod controller;
pub mod driver;
pub mod port;
pub mod types;
{{ range .Cells }}
pub mod {{ . }};
{{- end }}
{{ end -}}
`))
