// Code generated by hexagonal-rust (forge-dev-codegen). DO NOT EDIT.

use std::sync::Arc;

use crate::port::greeting_store::GreetingStore;
use crate::types::greeting::Greeting;

pub trait GreetingController {
    fn greet(&self, name: &str) -> Greeting;
}

pub struct GreetingControllerImpl {
    pub greeting_store: Arc<dyn GreetingStore + Send + Sync>,
}

impl GreetingControllerImpl {
    pub fn new(greeting_store: Arc<dyn GreetingStore + Send + Sync>) -> Self {
        Self { greeting_store }
    }
}
