// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:1782078ca5a274e97c5560c1b4054f6ccf850de798f290ea012d8e2d769b5868

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for no-comment-lint. All fields are optional.
type Spec struct {
	// Glob patterns excluded from the scan (default is zz_generated*, **/zz_generated*, **/docs/**)
	Exclude []string `json:"exclude,omitempty"`
	// Source languages to scan (default is go, rust, python, typescript)
	Languages []string `json:"languages,omitempty"`
	// Root directory to scan for source files (default is current directory)
	RootDir string `json:"rootDir,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}
	// Parse exclude
	if v, ok := m["exclude"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Exclude = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Exclude = append(s.Exclude, str)
				} else {
					return nil, fmt.Errorf("field exclude[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Exclude = arr
		} else {
			return nil, fmt.Errorf("field exclude: expected []string, got %T", v)
		}
	}
	// Parse languages
	if v, ok := m["languages"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Languages = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Languages = append(s.Languages, str)
				} else {
					return nil, fmt.Errorf("field languages[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Languages = arr
		} else {
			return nil, fmt.Errorf("field languages: expected []string, got %T", v)
		}
	}
	// Parse rootDir
	if v, ok := m["rootDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.RootDir = val
		} else {
			return nil, fmt.Errorf("field rootDir: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Exclude) > 0 {
		m["exclude"] = s.Exclude
	}
	if len(s.Languages) > 0 {
		m["languages"] = s.Languages
	}
	if s.RootDir != "" {
		m["rootDir"] = s.RootDir
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
