// Code generated by tui-rust (forge-dev-codegen). DO NOT EDIT.

use std::sync::Arc;
use std::time::Duration;

use crate::tui::controller::{BoardController, BoardControllerError};
use crate::tui::port::keyboard::{Keyboard, KeyboardError};
use crate::tui::port::screen::{Screen, ScreenError};
use crate::tui::types::frame::{Frame, Prompt, Step};
use crate::tui::types::key::{Input, Key};

pub const WIDTH: u16 = 12;
pub const HEIGHT: u16 = 6;
pub const DEFAULT_TICK_MS: i64 = 100;

pub struct TuiDriverConfig {
    pub tick_ms: i64,
}

impl Default for TuiDriverConfig {
    fn default() -> Self {
        Self {
            tick_ms: DEFAULT_TICK_MS,
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum TuiDriverError {
    #[error("entering the terminal for the tui driver")]
    Enter {
        #[source]
        source: ScreenError,
    },
    #[error("drawing a {WIDTH}x{HEIGHT} frame for the tui driver")]
    Draw {
        #[source]
        source: ScreenError,
    },
    #[error("leaving the terminal of the tui driver")]
    Leave {
        #[source]
        source: ScreenError,
    },
    #[error("reading a key for the tui driver within {tick_ms} ms")]
    Read {
        tick_ms: u64,
        #[source]
        source: KeyboardError,
    },
    #[error("running the board controller on {input}")]
    Controller {
        input: String,
        #[source]
        source: BoardControllerError,
    },
    #[error("reading {key} for the tui driver: {value} is below 1 ms")]
    Tick { key: String, value: i64 },
    #[error("joining the tui loop task")]
    Join {
        #[source]
        source: tokio::task::JoinError,
    },
    #[error("using the tui driver: it is not bound yet")]
    NotBound,
}

enum Next {
    Skip,
    Redraw,
    Show(Frame),
    Quit,
}

pub struct TuiDriver {
    config: TuiDriverConfig,
    controller: Arc<dyn BoardController + Send + Sync>,
    screen: Arc<dyn Screen + Send + Sync>,
    keyboard: Arc<dyn Keyboard + Send + Sync>,
    screen_open: bool,
}

impl TuiDriver {
    pub fn new(
        config: TuiDriverConfig,
        controller: Arc<dyn BoardController + Send + Sync>,
        screen: Arc<dyn Screen + Send + Sync>,
        keyboard: Arc<dyn Keyboard + Send + Sync>,
    ) -> Self {
        Self {
            config,
            controller,
            screen,
            keyboard,
            screen_open: false,
        }
    }

    pub async fn bind(&mut self) -> Result<(), TuiDriverError> {
        if self.config.tick_ms < 1 {
            return Err(TuiDriverError::Tick {
                key: "tick_ms".to_string(),
                value: self.config.tick_ms,
            });
        }

        println!("TUI {WIDTH}x{HEIGHT}");

        self.screen
            .enter()
            .map_err(|source| TuiDriverError::Enter { source })?;

        self.screen_open = true;

        Ok(())
    }

    pub fn announce(&self) -> Result<(), TuiDriverError> {
        if !self.screen_open {
            return Err(TuiDriverError::NotBound);
        }

        Ok(())
    }

    pub async fn serve(self) -> Result<(), TuiDriverError> {
        if !self.screen_open {
            return Err(TuiDriverError::NotBound);
        }

        let (mut driver, outcome) = tokio::task::spawn_blocking(move || {
            let outcome = self.run();
            (self, outcome)
        })
        .await
        .map_err(|source| TuiDriverError::Join { source })?;

        driver.screen_open = false;

        let left = driver
            .screen
            .leave()
            .map_err(|source| TuiDriverError::Leave { source });

        outcome.and(left)
    }

    fn run(&self) -> Result<(), TuiDriverError> {
        let screen: &(dyn Screen + Send + Sync) = &*self.screen;
        let keyboard: &(dyn Keyboard + Send + Sync) = &*self.keyboard;

        let tick_ms = self.config.tick_ms.unsigned_abs();
        let tick = Duration::from_millis(tick_ms);

        let mut frame = self.tick(&Frame::blank(WIDTH, HEIGHT))?;
        let mut prompt = Prompt::Closed;

        draw(screen, &frame, &prompt)?;

        loop {
            let input = keyboard
                .read(tick)
                .map_err(|source| TuiDriverError::Read { tick_ms, source })?;

            let next = match input {
                None => Next::Show(self.tick(&frame)?),
                Some(Input::Interrupt) => Next::Quit,
                Some(input) => match std::mem::replace(&mut prompt, Prompt::Closed) {
                    Prompt::Open(text) => {
                        let (after, next) = self.edit(&frame, text, input)?;
                        prompt = after;
                        next
                    }
                    Prompt::Closed => self.command(&frame, &mut prompt, input)?,
                },
            };

            match next {
                Next::Skip => {}
                Next::Redraw => draw(screen, &frame, &prompt)?,
                Next::Show(shown) => {
                    frame = shown;
                    draw(screen, &frame, &prompt)?;
                }
                Next::Quit => return Ok(()),
            }
        }
    }

    fn tick(&self, frame: &Frame) -> Result<Frame, TuiDriverError> {
        self.controller
            .on_tick(frame)
            .map_err(running("tick".to_string()))
    }

    fn command(
        &self,
        frame: &Frame,
        prompt: &mut Prompt,
        input: Input,
    ) -> Result<Next, TuiDriverError> {
        if opens_line(&input) {
            *prompt = Prompt::Open(String::new());

            return Ok(Next::Redraw);
        }

        let Some(key) = bind_key(&input) else {
            return Ok(Next::Skip);
        };

        let step = self
            .controller
            .on_key(frame, key)
            .map_err(running(format!("key {key:?}")))?;

        Ok(next_of(step))
    }

    fn edit(
        &self,
        frame: &Frame,
        mut text: String,
        input: Input,
    ) -> Result<(Prompt, Next), TuiDriverError> {
        match input {
            Input::Enter => {
                let step = self
                    .controller
                    .on_line(frame, &text)
                    .map_err(running(format!("line {text:?}")))?;

                Ok((Prompt::Closed, next_of(step)))
            }
            Input::Escape => Ok((Prompt::Closed, Next::Redraw)),
            Input::Backspace => {
                text.pop();
                Ok((Prompt::Open(text), Next::Redraw))
            }
            Input::Char(c) => {
                text.push(c);
                Ok((Prompt::Open(text), Next::Redraw))
            }
            _ => Ok((Prompt::Open(text), Next::Skip)),
        }
    }
}

fn next_of(step: Step) -> Next {
    match step {
        Step::Render(frame) => Next::Show(frame),
        Step::Quit => Next::Quit,
    }
}

fn running(input: String) -> impl FnOnce(BoardControllerError) -> TuiDriverError {
    move |source| TuiDriverError::Controller { input, source }
}

fn draw(
    screen: &(dyn Screen + Send + Sync),
    frame: &Frame,
    prompt: &Prompt,
) -> Result<(), TuiDriverError> {
    screen
        .draw(frame, prompt)
        .map_err(|source| TuiDriverError::Draw { source })
}

pub fn opens_line(input: &Input) -> bool {
    matches!(input, Input::Enter)
}

pub fn bind_key(input: &Input) -> Option<Key> {
    match input {
        Input::Char('h') | Input::Left => Some(Key::Left),
        Input::Char('j') | Input::Down => Some(Key::Down),
        Input::Char('k') | Input::Up => Some(Key::Up),
        Input::Char('l') | Input::Right => Some(Key::Right),
        Input::Char('a') => Some(Key::Act),
        Input::Char(' ') => Some(Key::EndTurn),
        Input::Char('q') => Some(Key::Quit),
        _ => None,
    }
}

impl Drop for TuiDriver {
    fn drop(&mut self) {
        if !self.screen_open {
            return;
        }

        if let Err(error) = self.screen.leave() {
            eprintln!(
                "leaving the terminal of the tui driver dropped while its screen was open: {}",
                error_chain(&error)
            );
        }
    }
}

pub fn error_chain(error: &dyn std::error::Error) -> String {
    let mut parts = vec![error.to_string()];
    let mut source = error.source();

    while let Some(current) = source {
        parts.push(current.to_string());
        source = current.source();
    }

    parts.join(": ")
}
